// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"cubicle/services/ontology-service/ent/migrate"

	"cubicle/services/ontology-service/ent/document"
	"cubicle/services/ontology-service/ent/documentfragment"
	"cubicle/services/ontology-service/ent/evidence"
	"cubicle/services/ontology-service/ent/message"
	"cubicle/services/ontology-service/ent/person"
	"cubicle/services/ontology-service/ent/pullrequest"
	"cubicle/services/ontology-service/ent/ticket"
	"cubicle/services/ontology-service/ent/ticketdocumentfragment"
	"cubicle/services/ontology-service/ent/ticketmessage"
	"cubicle/services/ontology-service/ent/ticketpullrequest"
	"cubicle/services/ontology-service/ent/workarea"
	"cubicle/services/ontology-service/ent/workstream"
	"cubicle/services/ontology-service/ent/workstreamticket"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Document is the client for interacting with the Document builders.
	Document *DocumentClient
	// DocumentFragment is the client for interacting with the DocumentFragment builders.
	DocumentFragment *DocumentFragmentClient
	// Evidence is the client for interacting with the Evidence builders.
	Evidence *EvidenceClient
	// Message is the client for interacting with the Message builders.
	Message *MessageClient
	// Person is the client for interacting with the Person builders.
	Person *PersonClient
	// PullRequest is the client for interacting with the PullRequest builders.
	PullRequest *PullRequestClient
	// Ticket is the client for interacting with the Ticket builders.
	Ticket *TicketClient
	// TicketDocumentFragment is the client for interacting with the TicketDocumentFragment builders.
	TicketDocumentFragment *TicketDocumentFragmentClient
	// TicketMessage is the client for interacting with the TicketMessage builders.
	TicketMessage *TicketMessageClient
	// TicketPullRequest is the client for interacting with the TicketPullRequest builders.
	TicketPullRequest *TicketPullRequestClient
	// WorkArea is the client for interacting with the WorkArea builders.
	WorkArea *WorkAreaClient
	// Workstream is the client for interacting with the Workstream builders.
	Workstream *WorkstreamClient
	// WorkstreamTicket is the client for interacting with the WorkstreamTicket builders.
	WorkstreamTicket *WorkstreamTicketClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Document = NewDocumentClient(c.config)
	c.DocumentFragment = NewDocumentFragmentClient(c.config)
	c.Evidence = NewEvidenceClient(c.config)
	c.Message = NewMessageClient(c.config)
	c.Person = NewPersonClient(c.config)
	c.PullRequest = NewPullRequestClient(c.config)
	c.Ticket = NewTicketClient(c.config)
	c.TicketDocumentFragment = NewTicketDocumentFragmentClient(c.config)
	c.TicketMessage = NewTicketMessageClient(c.config)
	c.TicketPullRequest = NewTicketPullRequestClient(c.config)
	c.WorkArea = NewWorkAreaClient(c.config)
	c.Workstream = NewWorkstreamClient(c.config)
	c.WorkstreamTicket = NewWorkstreamTicketClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                    ctx,
		config:                 cfg,
		Document:               NewDocumentClient(cfg),
		DocumentFragment:       NewDocumentFragmentClient(cfg),
		Evidence:               NewEvidenceClient(cfg),
		Message:                NewMessageClient(cfg),
		Person:                 NewPersonClient(cfg),
		PullRequest:            NewPullRequestClient(cfg),
		Ticket:                 NewTicketClient(cfg),
		TicketDocumentFragment: NewTicketDocumentFragmentClient(cfg),
		TicketMessage:          NewTicketMessageClient(cfg),
		TicketPullRequest:      NewTicketPullRequestClient(cfg),
		WorkArea:               NewWorkAreaClient(cfg),
		Workstream:             NewWorkstreamClient(cfg),
		WorkstreamTicket:       NewWorkstreamTicketClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                    ctx,
		config:                 cfg,
		Document:               NewDocumentClient(cfg),
		DocumentFragment:       NewDocumentFragmentClient(cfg),
		Evidence:               NewEvidenceClient(cfg),
		Message:                NewMessageClient(cfg),
		Person:                 NewPersonClient(cfg),
		PullRequest:            NewPullRequestClient(cfg),
		Ticket:                 NewTicketClient(cfg),
		TicketDocumentFragment: NewTicketDocumentFragmentClient(cfg),
		TicketMessage:          NewTicketMessageClient(cfg),
		TicketPullRequest:      NewTicketPullRequestClient(cfg),
		WorkArea:               NewWorkAreaClient(cfg),
		Workstream:             NewWorkstreamClient(cfg),
		WorkstreamTicket:       NewWorkstreamTicketClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Document.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Document, c.DocumentFragment, c.Evidence, c.Message, c.Person, c.PullRequest,
		c.Ticket, c.TicketDocumentFragment, c.TicketMessage, c.TicketPullRequest,
		c.WorkArea, c.Workstream, c.WorkstreamTicket,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Document, c.DocumentFragment, c.Evidence, c.Message, c.Person, c.PullRequest,
		c.Ticket, c.TicketDocumentFragment, c.TicketMessage, c.TicketPullRequest,
		c.WorkArea, c.Workstream, c.WorkstreamTicket,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *DocumentMutation:
		return c.Document.mutate(ctx, m)
	case *DocumentFragmentMutation:
		return c.DocumentFragment.mutate(ctx, m)
	case *EvidenceMutation:
		return c.Evidence.mutate(ctx, m)
	case *MessageMutation:
		return c.Message.mutate(ctx, m)
	case *PersonMutation:
		return c.Person.mutate(ctx, m)
	case *PullRequestMutation:
		return c.PullRequest.mutate(ctx, m)
	case *TicketMutation:
		return c.Ticket.mutate(ctx, m)
	case *TicketDocumentFragmentMutation:
		return c.TicketDocumentFragment.mutate(ctx, m)
	case *TicketMessageMutation:
		return c.TicketMessage.mutate(ctx, m)
	case *TicketPullRequestMutation:
		return c.TicketPullRequest.mutate(ctx, m)
	case *WorkAreaMutation:
		return c.WorkArea.mutate(ctx, m)
	case *WorkstreamMutation:
		return c.Workstream.mutate(ctx, m)
	case *WorkstreamTicketMutation:
		return c.WorkstreamTicket.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// DocumentClient is a client for the Document schema.
type DocumentClient struct {
	config
}

// NewDocumentClient returns a client for the Document from the given config.
func NewDocumentClient(c config) *DocumentClient {
	return &DocumentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `document.Hooks(f(g(h())))`.
func (c *DocumentClient) Use(hooks ...Hook) {
	c.hooks.Document = append(c.hooks.Document, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `document.Intercept(f(g(h())))`.
func (c *DocumentClient) Intercept(interceptors ...Interceptor) {
	c.inters.Document = append(c.inters.Document, interceptors...)
}

// Create returns a builder for creating a Document entity.
func (c *DocumentClient) Create() *DocumentCreate {
	mutation := newDocumentMutation(c.config, OpCreate)
	return &DocumentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Document entities.
func (c *DocumentClient) CreateBulk(builders ...*DocumentCreate) *DocumentCreateBulk {
	return &DocumentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DocumentClient) MapCreateBulk(slice any, setFunc func(*DocumentCreate, int)) *DocumentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DocumentCreateBulk{err: fmt.Errorf("calling to DocumentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DocumentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DocumentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Document.
func (c *DocumentClient) Update() *DocumentUpdate {
	mutation := newDocumentMutation(c.config, OpUpdate)
	return &DocumentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DocumentClient) UpdateOne(_m *Document) *DocumentUpdateOne {
	mutation := newDocumentMutation(c.config, OpUpdateOne, withDocument(_m))
	return &DocumentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DocumentClient) UpdateOneID(id int) *DocumentUpdateOne {
	mutation := newDocumentMutation(c.config, OpUpdateOne, withDocumentID(id))
	return &DocumentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Document.
func (c *DocumentClient) Delete() *DocumentDelete {
	mutation := newDocumentMutation(c.config, OpDelete)
	return &DocumentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DocumentClient) DeleteOne(_m *Document) *DocumentDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DocumentClient) DeleteOneID(id int) *DocumentDeleteOne {
	builder := c.Delete().Where(document.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DocumentDeleteOne{builder}
}

// Query returns a query builder for Document.
func (c *DocumentClient) Query() *DocumentQuery {
	return &DocumentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDocument},
		inters: c.Interceptors(),
	}
}

// Get returns a Document entity by its id.
func (c *DocumentClient) Get(ctx context.Context, id int) (*Document, error) {
	return c.Query().Where(document.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DocumentClient) GetX(ctx context.Context, id int) *Document {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryFragments queries the fragments edge of a Document.
func (c *DocumentClient) QueryFragments(_m *Document) *DocumentFragmentQuery {
	query := (&DocumentFragmentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(document.Table, document.FieldID, id),
			sqlgraph.To(documentfragment.Table, documentfragment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, document.FragmentsTable, document.FragmentsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DocumentClient) Hooks() []Hook {
	return c.hooks.Document
}

// Interceptors returns the client interceptors.
func (c *DocumentClient) Interceptors() []Interceptor {
	return c.inters.Document
}

func (c *DocumentClient) mutate(ctx context.Context, m *DocumentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DocumentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DocumentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DocumentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DocumentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Document mutation op: %q", m.Op())
	}
}

// DocumentFragmentClient is a client for the DocumentFragment schema.
type DocumentFragmentClient struct {
	config
}

// NewDocumentFragmentClient returns a client for the DocumentFragment from the given config.
func NewDocumentFragmentClient(c config) *DocumentFragmentClient {
	return &DocumentFragmentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `documentfragment.Hooks(f(g(h())))`.
func (c *DocumentFragmentClient) Use(hooks ...Hook) {
	c.hooks.DocumentFragment = append(c.hooks.DocumentFragment, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `documentfragment.Intercept(f(g(h())))`.
func (c *DocumentFragmentClient) Intercept(interceptors ...Interceptor) {
	c.inters.DocumentFragment = append(c.inters.DocumentFragment, interceptors...)
}

// Create returns a builder for creating a DocumentFragment entity.
func (c *DocumentFragmentClient) Create() *DocumentFragmentCreate {
	mutation := newDocumentFragmentMutation(c.config, OpCreate)
	return &DocumentFragmentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DocumentFragment entities.
func (c *DocumentFragmentClient) CreateBulk(builders ...*DocumentFragmentCreate) *DocumentFragmentCreateBulk {
	return &DocumentFragmentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DocumentFragmentClient) MapCreateBulk(slice any, setFunc func(*DocumentFragmentCreate, int)) *DocumentFragmentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DocumentFragmentCreateBulk{err: fmt.Errorf("calling to DocumentFragmentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DocumentFragmentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DocumentFragmentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DocumentFragment.
func (c *DocumentFragmentClient) Update() *DocumentFragmentUpdate {
	mutation := newDocumentFragmentMutation(c.config, OpUpdate)
	return &DocumentFragmentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DocumentFragmentClient) UpdateOne(_m *DocumentFragment) *DocumentFragmentUpdateOne {
	mutation := newDocumentFragmentMutation(c.config, OpUpdateOne, withDocumentFragment(_m))
	return &DocumentFragmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DocumentFragmentClient) UpdateOneID(id int) *DocumentFragmentUpdateOne {
	mutation := newDocumentFragmentMutation(c.config, OpUpdateOne, withDocumentFragmentID(id))
	return &DocumentFragmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DocumentFragment.
func (c *DocumentFragmentClient) Delete() *DocumentFragmentDelete {
	mutation := newDocumentFragmentMutation(c.config, OpDelete)
	return &DocumentFragmentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DocumentFragmentClient) DeleteOne(_m *DocumentFragment) *DocumentFragmentDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DocumentFragmentClient) DeleteOneID(id int) *DocumentFragmentDeleteOne {
	builder := c.Delete().Where(documentfragment.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DocumentFragmentDeleteOne{builder}
}

// Query returns a query builder for DocumentFragment.
func (c *DocumentFragmentClient) Query() *DocumentFragmentQuery {
	return &DocumentFragmentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDocumentFragment},
		inters: c.Interceptors(),
	}
}

// Get returns a DocumentFragment entity by its id.
func (c *DocumentFragmentClient) Get(ctx context.Context, id int) (*DocumentFragment, error) {
	return c.Query().Where(documentfragment.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DocumentFragmentClient) GetX(ctx context.Context, id int) *DocumentFragment {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryDocument queries the document edge of a DocumentFragment.
func (c *DocumentFragmentClient) QueryDocument(_m *DocumentFragment) *DocumentQuery {
	query := (&DocumentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(documentfragment.Table, documentfragment.FieldID, id),
			sqlgraph.To(document.Table, document.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, documentfragment.DocumentTable, documentfragment.DocumentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTickets queries the tickets edge of a DocumentFragment.
func (c *DocumentFragmentClient) QueryTickets(_m *DocumentFragment) *TicketQuery {
	query := (&TicketClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(documentfragment.Table, documentfragment.FieldID, id),
			sqlgraph.To(ticket.Table, ticket.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, documentfragment.TicketsTable, documentfragment.TicketsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DocumentFragmentClient) Hooks() []Hook {
	return c.hooks.DocumentFragment
}

// Interceptors returns the client interceptors.
func (c *DocumentFragmentClient) Interceptors() []Interceptor {
	return c.inters.DocumentFragment
}

func (c *DocumentFragmentClient) mutate(ctx context.Context, m *DocumentFragmentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DocumentFragmentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DocumentFragmentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DocumentFragmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DocumentFragmentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DocumentFragment mutation op: %q", m.Op())
	}
}

// EvidenceClient is a client for the Evidence schema.
type EvidenceClient struct {
	config
}

// NewEvidenceClient returns a client for the Evidence from the given config.
func NewEvidenceClient(c config) *EvidenceClient {
	return &EvidenceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `evidence.Hooks(f(g(h())))`.
func (c *EvidenceClient) Use(hooks ...Hook) {
	c.hooks.Evidence = append(c.hooks.Evidence, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `evidence.Intercept(f(g(h())))`.
func (c *EvidenceClient) Intercept(interceptors ...Interceptor) {
	c.inters.Evidence = append(c.inters.Evidence, interceptors...)
}

// Create returns a builder for creating a Evidence entity.
func (c *EvidenceClient) Create() *EvidenceCreate {
	mutation := newEvidenceMutation(c.config, OpCreate)
	return &EvidenceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Evidence entities.
func (c *EvidenceClient) CreateBulk(builders ...*EvidenceCreate) *EvidenceCreateBulk {
	return &EvidenceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EvidenceClient) MapCreateBulk(slice any, setFunc func(*EvidenceCreate, int)) *EvidenceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EvidenceCreateBulk{err: fmt.Errorf("calling to EvidenceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EvidenceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EvidenceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Evidence.
func (c *EvidenceClient) Update() *EvidenceUpdate {
	mutation := newEvidenceMutation(c.config, OpUpdate)
	return &EvidenceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EvidenceClient) UpdateOne(_m *Evidence) *EvidenceUpdateOne {
	mutation := newEvidenceMutation(c.config, OpUpdateOne, withEvidence(_m))
	return &EvidenceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EvidenceClient) UpdateOneID(id int) *EvidenceUpdateOne {
	mutation := newEvidenceMutation(c.config, OpUpdateOne, withEvidenceID(id))
	return &EvidenceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Evidence.
func (c *EvidenceClient) Delete() *EvidenceDelete {
	mutation := newEvidenceMutation(c.config, OpDelete)
	return &EvidenceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EvidenceClient) DeleteOne(_m *Evidence) *EvidenceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EvidenceClient) DeleteOneID(id int) *EvidenceDeleteOne {
	builder := c.Delete().Where(evidence.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EvidenceDeleteOne{builder}
}

// Query returns a query builder for Evidence.
func (c *EvidenceClient) Query() *EvidenceQuery {
	return &EvidenceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEvidence},
		inters: c.Interceptors(),
	}
}

// Get returns a Evidence entity by its id.
func (c *EvidenceClient) Get(ctx context.Context, id int) (*Evidence, error) {
	return c.Query().Where(evidence.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EvidenceClient) GetX(ctx context.Context, id int) *Evidence {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *EvidenceClient) Hooks() []Hook {
	return c.hooks.Evidence
}

// Interceptors returns the client interceptors.
func (c *EvidenceClient) Interceptors() []Interceptor {
	return c.inters.Evidence
}

func (c *EvidenceClient) mutate(ctx context.Context, m *EvidenceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EvidenceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EvidenceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EvidenceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EvidenceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Evidence mutation op: %q", m.Op())
	}
}

// MessageClient is a client for the Message schema.
type MessageClient struct {
	config
}

// NewMessageClient returns a client for the Message from the given config.
func NewMessageClient(c config) *MessageClient {
	return &MessageClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `message.Hooks(f(g(h())))`.
func (c *MessageClient) Use(hooks ...Hook) {
	c.hooks.Message = append(c.hooks.Message, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `message.Intercept(f(g(h())))`.
func (c *MessageClient) Intercept(interceptors ...Interceptor) {
	c.inters.Message = append(c.inters.Message, interceptors...)
}

// Create returns a builder for creating a Message entity.
func (c *MessageClient) Create() *MessageCreate {
	mutation := newMessageMutation(c.config, OpCreate)
	return &MessageCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Message entities.
func (c *MessageClient) CreateBulk(builders ...*MessageCreate) *MessageCreateBulk {
	return &MessageCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MessageClient) MapCreateBulk(slice any, setFunc func(*MessageCreate, int)) *MessageCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MessageCreateBulk{err: fmt.Errorf("calling to MessageClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MessageCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MessageCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Message.
func (c *MessageClient) Update() *MessageUpdate {
	mutation := newMessageMutation(c.config, OpUpdate)
	return &MessageUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MessageClient) UpdateOne(_m *Message) *MessageUpdateOne {
	mutation := newMessageMutation(c.config, OpUpdateOne, withMessage(_m))
	return &MessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MessageClient) UpdateOneID(id int) *MessageUpdateOne {
	mutation := newMessageMutation(c.config, OpUpdateOne, withMessageID(id))
	return &MessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Message.
func (c *MessageClient) Delete() *MessageDelete {
	mutation := newMessageMutation(c.config, OpDelete)
	return &MessageDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MessageClient) DeleteOne(_m *Message) *MessageDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MessageClient) DeleteOneID(id int) *MessageDeleteOne {
	builder := c.Delete().Where(message.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MessageDeleteOne{builder}
}

// Query returns a query builder for Message.
func (c *MessageClient) Query() *MessageQuery {
	return &MessageQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMessage},
		inters: c.Interceptors(),
	}
}

// Get returns a Message entity by its id.
func (c *MessageClient) Get(ctx context.Context, id int) (*Message, error) {
	return c.Query().Where(message.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MessageClient) GetX(ctx context.Context, id int) *Message {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTickets queries the tickets edge of a Message.
func (c *MessageClient) QueryTickets(_m *Message) *TicketQuery {
	query := (&TicketClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(message.Table, message.FieldID, id),
			sqlgraph.To(ticket.Table, ticket.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, message.TicketsTable, message.TicketsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MessageClient) Hooks() []Hook {
	return c.hooks.Message
}

// Interceptors returns the client interceptors.
func (c *MessageClient) Interceptors() []Interceptor {
	return c.inters.Message
}

func (c *MessageClient) mutate(ctx context.Context, m *MessageMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MessageCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MessageUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MessageDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Message mutation op: %q", m.Op())
	}
}

// PersonClient is a client for the Person schema.
type PersonClient struct {
	config
}

// NewPersonClient returns a client for the Person from the given config.
func NewPersonClient(c config) *PersonClient {
	return &PersonClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `person.Hooks(f(g(h())))`.
func (c *PersonClient) Use(hooks ...Hook) {
	c.hooks.Person = append(c.hooks.Person, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `person.Intercept(f(g(h())))`.
func (c *PersonClient) Intercept(interceptors ...Interceptor) {
	c.inters.Person = append(c.inters.Person, interceptors...)
}

// Create returns a builder for creating a Person entity.
func (c *PersonClient) Create() *PersonCreate {
	mutation := newPersonMutation(c.config, OpCreate)
	return &PersonCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Person entities.
func (c *PersonClient) CreateBulk(builders ...*PersonCreate) *PersonCreateBulk {
	return &PersonCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PersonClient) MapCreateBulk(slice any, setFunc func(*PersonCreate, int)) *PersonCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PersonCreateBulk{err: fmt.Errorf("calling to PersonClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PersonCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PersonCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Person.
func (c *PersonClient) Update() *PersonUpdate {
	mutation := newPersonMutation(c.config, OpUpdate)
	return &PersonUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PersonClient) UpdateOne(_m *Person) *PersonUpdateOne {
	mutation := newPersonMutation(c.config, OpUpdateOne, withPerson(_m))
	return &PersonUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PersonClient) UpdateOneID(id int) *PersonUpdateOne {
	mutation := newPersonMutation(c.config, OpUpdateOne, withPersonID(id))
	return &PersonUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Person.
func (c *PersonClient) Delete() *PersonDelete {
	mutation := newPersonMutation(c.config, OpDelete)
	return &PersonDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PersonClient) DeleteOne(_m *Person) *PersonDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PersonClient) DeleteOneID(id int) *PersonDeleteOne {
	builder := c.Delete().Where(person.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PersonDeleteOne{builder}
}

// Query returns a query builder for Person.
func (c *PersonClient) Query() *PersonQuery {
	return &PersonQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePerson},
		inters: c.Interceptors(),
	}
}

// Get returns a Person entity by its id.
func (c *PersonClient) Get(ctx context.Context, id int) (*Person, error) {
	return c.Query().Where(person.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PersonClient) GetX(ctx context.Context, id int) *Person {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryWorkAreas queries the work_areas edge of a Person.
func (c *PersonClient) QueryWorkAreas(_m *Person) *WorkAreaQuery {
	query := (&WorkAreaClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(person.Table, person.FieldID, id),
			sqlgraph.To(workarea.Table, workarea.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, person.WorkAreasTable, person.WorkAreasColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PersonClient) Hooks() []Hook {
	return c.hooks.Person
}

// Interceptors returns the client interceptors.
func (c *PersonClient) Interceptors() []Interceptor {
	return c.inters.Person
}

func (c *PersonClient) mutate(ctx context.Context, m *PersonMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PersonCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PersonUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PersonUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PersonDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Person mutation op: %q", m.Op())
	}
}

// PullRequestClient is a client for the PullRequest schema.
type PullRequestClient struct {
	config
}

// NewPullRequestClient returns a client for the PullRequest from the given config.
func NewPullRequestClient(c config) *PullRequestClient {
	return &PullRequestClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `pullrequest.Hooks(f(g(h())))`.
func (c *PullRequestClient) Use(hooks ...Hook) {
	c.hooks.PullRequest = append(c.hooks.PullRequest, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `pullrequest.Intercept(f(g(h())))`.
func (c *PullRequestClient) Intercept(interceptors ...Interceptor) {
	c.inters.PullRequest = append(c.inters.PullRequest, interceptors...)
}

// Create returns a builder for creating a PullRequest entity.
func (c *PullRequestClient) Create() *PullRequestCreate {
	mutation := newPullRequestMutation(c.config, OpCreate)
	return &PullRequestCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PullRequest entities.
func (c *PullRequestClient) CreateBulk(builders ...*PullRequestCreate) *PullRequestCreateBulk {
	return &PullRequestCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PullRequestClient) MapCreateBulk(slice any, setFunc func(*PullRequestCreate, int)) *PullRequestCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PullRequestCreateBulk{err: fmt.Errorf("calling to PullRequestClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PullRequestCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PullRequestCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PullRequest.
func (c *PullRequestClient) Update() *PullRequestUpdate {
	mutation := newPullRequestMutation(c.config, OpUpdate)
	return &PullRequestUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PullRequestClient) UpdateOne(_m *PullRequest) *PullRequestUpdateOne {
	mutation := newPullRequestMutation(c.config, OpUpdateOne, withPullRequest(_m))
	return &PullRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PullRequestClient) UpdateOneID(id int) *PullRequestUpdateOne {
	mutation := newPullRequestMutation(c.config, OpUpdateOne, withPullRequestID(id))
	return &PullRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PullRequest.
func (c *PullRequestClient) Delete() *PullRequestDelete {
	mutation := newPullRequestMutation(c.config, OpDelete)
	return &PullRequestDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PullRequestClient) DeleteOne(_m *PullRequest) *PullRequestDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PullRequestClient) DeleteOneID(id int) *PullRequestDeleteOne {
	builder := c.Delete().Where(pullrequest.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PullRequestDeleteOne{builder}
}

// Query returns a query builder for PullRequest.
func (c *PullRequestClient) Query() *PullRequestQuery {
	return &PullRequestQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePullRequest},
		inters: c.Interceptors(),
	}
}

// Get returns a PullRequest entity by its id.
func (c *PullRequestClient) Get(ctx context.Context, id int) (*PullRequest, error) {
	return c.Query().Where(pullrequest.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PullRequestClient) GetX(ctx context.Context, id int) *PullRequest {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTickets queries the tickets edge of a PullRequest.
func (c *PullRequestClient) QueryTickets(_m *PullRequest) *TicketQuery {
	query := (&TicketClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pullrequest.Table, pullrequest.FieldID, id),
			sqlgraph.To(ticket.Table, ticket.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, pullrequest.TicketsTable, pullrequest.TicketsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PullRequestClient) Hooks() []Hook {
	return c.hooks.PullRequest
}

// Interceptors returns the client interceptors.
func (c *PullRequestClient) Interceptors() []Interceptor {
	return c.inters.PullRequest
}

func (c *PullRequestClient) mutate(ctx context.Context, m *PullRequestMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PullRequestCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PullRequestUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PullRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PullRequestDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PullRequest mutation op: %q", m.Op())
	}
}

// TicketClient is a client for the Ticket schema.
type TicketClient struct {
	config
}

// NewTicketClient returns a client for the Ticket from the given config.
func NewTicketClient(c config) *TicketClient {
	return &TicketClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ticket.Hooks(f(g(h())))`.
func (c *TicketClient) Use(hooks ...Hook) {
	c.hooks.Ticket = append(c.hooks.Ticket, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ticket.Intercept(f(g(h())))`.
func (c *TicketClient) Intercept(interceptors ...Interceptor) {
	c.inters.Ticket = append(c.inters.Ticket, interceptors...)
}

// Create returns a builder for creating a Ticket entity.
func (c *TicketClient) Create() *TicketCreate {
	mutation := newTicketMutation(c.config, OpCreate)
	return &TicketCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Ticket entities.
func (c *TicketClient) CreateBulk(builders ...*TicketCreate) *TicketCreateBulk {
	return &TicketCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TicketClient) MapCreateBulk(slice any, setFunc func(*TicketCreate, int)) *TicketCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TicketCreateBulk{err: fmt.Errorf("calling to TicketClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TicketCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TicketCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Ticket.
func (c *TicketClient) Update() *TicketUpdate {
	mutation := newTicketMutation(c.config, OpUpdate)
	return &TicketUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TicketClient) UpdateOne(_m *Ticket) *TicketUpdateOne {
	mutation := newTicketMutation(c.config, OpUpdateOne, withTicket(_m))
	return &TicketUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TicketClient) UpdateOneID(id int) *TicketUpdateOne {
	mutation := newTicketMutation(c.config, OpUpdateOne, withTicketID(id))
	return &TicketUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Ticket.
func (c *TicketClient) Delete() *TicketDelete {
	mutation := newTicketMutation(c.config, OpDelete)
	return &TicketDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TicketClient) DeleteOne(_m *Ticket) *TicketDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TicketClient) DeleteOneID(id int) *TicketDeleteOne {
	builder := c.Delete().Where(ticket.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TicketDeleteOne{builder}
}

// Query returns a query builder for Ticket.
func (c *TicketClient) Query() *TicketQuery {
	return &TicketQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTicket},
		inters: c.Interceptors(),
	}
}

// Get returns a Ticket entity by its id.
func (c *TicketClient) Get(ctx context.Context, id int) (*Ticket, error) {
	return c.Query().Where(ticket.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TicketClient) GetX(ctx context.Context, id int) *Ticket {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryWorkstreams queries the workstreams edge of a Ticket.
func (c *TicketClient) QueryWorkstreams(_m *Ticket) *WorkstreamQuery {
	query := (&WorkstreamClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ticket.Table, ticket.FieldID, id),
			sqlgraph.To(workstream.Table, workstream.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, ticket.WorkstreamsTable, ticket.WorkstreamsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPullRequests queries the pull_requests edge of a Ticket.
func (c *TicketClient) QueryPullRequests(_m *Ticket) *PullRequestQuery {
	query := (&PullRequestClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ticket.Table, ticket.FieldID, id),
			sqlgraph.To(pullrequest.Table, pullrequest.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, ticket.PullRequestsTable, ticket.PullRequestsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDocumentFragments queries the document_fragments edge of a Ticket.
func (c *TicketClient) QueryDocumentFragments(_m *Ticket) *DocumentFragmentQuery {
	query := (&DocumentFragmentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ticket.Table, ticket.FieldID, id),
			sqlgraph.To(documentfragment.Table, documentfragment.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, ticket.DocumentFragmentsTable, ticket.DocumentFragmentsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMessages queries the messages edge of a Ticket.
func (c *TicketClient) QueryMessages(_m *Ticket) *MessageQuery {
	query := (&MessageClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ticket.Table, ticket.FieldID, id),
			sqlgraph.To(message.Table, message.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, ticket.MessagesTable, ticket.MessagesPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTicketPullRequests queries the ticket_pull_requests edge of a Ticket.
func (c *TicketClient) QueryTicketPullRequests(_m *Ticket) *TicketPullRequestQuery {
	query := (&TicketPullRequestClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ticket.Table, ticket.FieldID, id),
			sqlgraph.To(ticketpullrequest.Table, ticketpullrequest.TicketColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, ticket.TicketPullRequestsTable, ticket.TicketPullRequestsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTicketDocumentFragments queries the ticket_document_fragments edge of a Ticket.
func (c *TicketClient) QueryTicketDocumentFragments(_m *Ticket) *TicketDocumentFragmentQuery {
	query := (&TicketDocumentFragmentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ticket.Table, ticket.FieldID, id),
			sqlgraph.To(ticketdocumentfragment.Table, ticketdocumentfragment.TicketColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, ticket.TicketDocumentFragmentsTable, ticket.TicketDocumentFragmentsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTicketMessages queries the ticket_messages edge of a Ticket.
func (c *TicketClient) QueryTicketMessages(_m *Ticket) *TicketMessageQuery {
	query := (&TicketMessageClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ticket.Table, ticket.FieldID, id),
			sqlgraph.To(ticketmessage.Table, ticketmessage.TicketColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, ticket.TicketMessagesTable, ticket.TicketMessagesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TicketClient) Hooks() []Hook {
	return c.hooks.Ticket
}

// Interceptors returns the client interceptors.
func (c *TicketClient) Interceptors() []Interceptor {
	return c.inters.Ticket
}

func (c *TicketClient) mutate(ctx context.Context, m *TicketMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TicketCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TicketUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TicketUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TicketDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Ticket mutation op: %q", m.Op())
	}
}

// TicketDocumentFragmentClient is a client for the TicketDocumentFragment schema.
type TicketDocumentFragmentClient struct {
	config
}

// NewTicketDocumentFragmentClient returns a client for the TicketDocumentFragment from the given config.
func NewTicketDocumentFragmentClient(c config) *TicketDocumentFragmentClient {
	return &TicketDocumentFragmentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ticketdocumentfragment.Hooks(f(g(h())))`.
func (c *TicketDocumentFragmentClient) Use(hooks ...Hook) {
	c.hooks.TicketDocumentFragment = append(c.hooks.TicketDocumentFragment, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ticketdocumentfragment.Intercept(f(g(h())))`.
func (c *TicketDocumentFragmentClient) Intercept(interceptors ...Interceptor) {
	c.inters.TicketDocumentFragment = append(c.inters.TicketDocumentFragment, interceptors...)
}

// Create returns a builder for creating a TicketDocumentFragment entity.
func (c *TicketDocumentFragmentClient) Create() *TicketDocumentFragmentCreate {
	mutation := newTicketDocumentFragmentMutation(c.config, OpCreate)
	return &TicketDocumentFragmentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TicketDocumentFragment entities.
func (c *TicketDocumentFragmentClient) CreateBulk(builders ...*TicketDocumentFragmentCreate) *TicketDocumentFragmentCreateBulk {
	return &TicketDocumentFragmentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TicketDocumentFragmentClient) MapCreateBulk(slice any, setFunc func(*TicketDocumentFragmentCreate, int)) *TicketDocumentFragmentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TicketDocumentFragmentCreateBulk{err: fmt.Errorf("calling to TicketDocumentFragmentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TicketDocumentFragmentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TicketDocumentFragmentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TicketDocumentFragment.
func (c *TicketDocumentFragmentClient) Update() *TicketDocumentFragmentUpdate {
	mutation := newTicketDocumentFragmentMutation(c.config, OpUpdate)
	return &TicketDocumentFragmentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TicketDocumentFragmentClient) UpdateOne(_m *TicketDocumentFragment) *TicketDocumentFragmentUpdateOne {
	mutation := newTicketDocumentFragmentMutation(c.config, OpUpdateOne)
	mutation.ticket = &_m.TicketID
	mutation.document_fragment = &_m.DocumentFragmentID
	return &TicketDocumentFragmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TicketDocumentFragment.
func (c *TicketDocumentFragmentClient) Delete() *TicketDocumentFragmentDelete {
	mutation := newTicketDocumentFragmentMutation(c.config, OpDelete)
	return &TicketDocumentFragmentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Query returns a query builder for TicketDocumentFragment.
func (c *TicketDocumentFragmentClient) Query() *TicketDocumentFragmentQuery {
	return &TicketDocumentFragmentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTicketDocumentFragment},
		inters: c.Interceptors(),
	}
}

// QueryTicket queries the ticket edge of a TicketDocumentFragment.
func (c *TicketDocumentFragmentClient) QueryTicket(_m *TicketDocumentFragment) *TicketQuery {
	return c.Query().
		Where(ticketdocumentfragment.TicketID(_m.TicketID), ticketdocumentfragment.DocumentFragmentID(_m.DocumentFragmentID)).
		QueryTicket()
}

// QueryDocumentFragment queries the document_fragment edge of a TicketDocumentFragment.
func (c *TicketDocumentFragmentClient) QueryDocumentFragment(_m *TicketDocumentFragment) *DocumentFragmentQuery {
	return c.Query().
		Where(ticketdocumentfragment.TicketID(_m.TicketID), ticketdocumentfragment.DocumentFragmentID(_m.DocumentFragmentID)).
		QueryDocumentFragment()
}

// QueryLatestEvidence queries the latest_evidence edge of a TicketDocumentFragment.
func (c *TicketDocumentFragmentClient) QueryLatestEvidence(_m *TicketDocumentFragment) *EvidenceQuery {
	return c.Query().
		Where(ticketdocumentfragment.TicketID(_m.TicketID), ticketdocumentfragment.DocumentFragmentID(_m.DocumentFragmentID)).
		QueryLatestEvidence()
}

// Hooks returns the client hooks.
func (c *TicketDocumentFragmentClient) Hooks() []Hook {
	return c.hooks.TicketDocumentFragment
}

// Interceptors returns the client interceptors.
func (c *TicketDocumentFragmentClient) Interceptors() []Interceptor {
	return c.inters.TicketDocumentFragment
}

func (c *TicketDocumentFragmentClient) mutate(ctx context.Context, m *TicketDocumentFragmentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TicketDocumentFragmentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TicketDocumentFragmentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TicketDocumentFragmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TicketDocumentFragmentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TicketDocumentFragment mutation op: %q", m.Op())
	}
}

// TicketMessageClient is a client for the TicketMessage schema.
type TicketMessageClient struct {
	config
}

// NewTicketMessageClient returns a client for the TicketMessage from the given config.
func NewTicketMessageClient(c config) *TicketMessageClient {
	return &TicketMessageClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ticketmessage.Hooks(f(g(h())))`.
func (c *TicketMessageClient) Use(hooks ...Hook) {
	c.hooks.TicketMessage = append(c.hooks.TicketMessage, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ticketmessage.Intercept(f(g(h())))`.
func (c *TicketMessageClient) Intercept(interceptors ...Interceptor) {
	c.inters.TicketMessage = append(c.inters.TicketMessage, interceptors...)
}

// Create returns a builder for creating a TicketMessage entity.
func (c *TicketMessageClient) Create() *TicketMessageCreate {
	mutation := newTicketMessageMutation(c.config, OpCreate)
	return &TicketMessageCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TicketMessage entities.
func (c *TicketMessageClient) CreateBulk(builders ...*TicketMessageCreate) *TicketMessageCreateBulk {
	return &TicketMessageCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TicketMessageClient) MapCreateBulk(slice any, setFunc func(*TicketMessageCreate, int)) *TicketMessageCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TicketMessageCreateBulk{err: fmt.Errorf("calling to TicketMessageClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TicketMessageCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TicketMessageCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TicketMessage.
func (c *TicketMessageClient) Update() *TicketMessageUpdate {
	mutation := newTicketMessageMutation(c.config, OpUpdate)
	return &TicketMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TicketMessageClient) UpdateOne(_m *TicketMessage) *TicketMessageUpdateOne {
	mutation := newTicketMessageMutation(c.config, OpUpdateOne)
	mutation.ticket = &_m.TicketID
	mutation.message = &_m.MessageID
	return &TicketMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TicketMessage.
func (c *TicketMessageClient) Delete() *TicketMessageDelete {
	mutation := newTicketMessageMutation(c.config, OpDelete)
	return &TicketMessageDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Query returns a query builder for TicketMessage.
func (c *TicketMessageClient) Query() *TicketMessageQuery {
	return &TicketMessageQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTicketMessage},
		inters: c.Interceptors(),
	}
}

// QueryTicket queries the ticket edge of a TicketMessage.
func (c *TicketMessageClient) QueryTicket(_m *TicketMessage) *TicketQuery {
	return c.Query().
		Where(ticketmessage.TicketID(_m.TicketID), ticketmessage.MessageID(_m.MessageID)).
		QueryTicket()
}

// QueryMessage queries the message edge of a TicketMessage.
func (c *TicketMessageClient) QueryMessage(_m *TicketMessage) *MessageQuery {
	return c.Query().
		Where(ticketmessage.TicketID(_m.TicketID), ticketmessage.MessageID(_m.MessageID)).
		QueryMessage()
}

// QueryLatestEvidence queries the latest_evidence edge of a TicketMessage.
func (c *TicketMessageClient) QueryLatestEvidence(_m *TicketMessage) *EvidenceQuery {
	return c.Query().
		Where(ticketmessage.TicketID(_m.TicketID), ticketmessage.MessageID(_m.MessageID)).
		QueryLatestEvidence()
}

// Hooks returns the client hooks.
func (c *TicketMessageClient) Hooks() []Hook {
	return c.hooks.TicketMessage
}

// Interceptors returns the client interceptors.
func (c *TicketMessageClient) Interceptors() []Interceptor {
	return c.inters.TicketMessage
}

func (c *TicketMessageClient) mutate(ctx context.Context, m *TicketMessageMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TicketMessageCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TicketMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TicketMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TicketMessageDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TicketMessage mutation op: %q", m.Op())
	}
}

// TicketPullRequestClient is a client for the TicketPullRequest schema.
type TicketPullRequestClient struct {
	config
}

// NewTicketPullRequestClient returns a client for the TicketPullRequest from the given config.
func NewTicketPullRequestClient(c config) *TicketPullRequestClient {
	return &TicketPullRequestClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ticketpullrequest.Hooks(f(g(h())))`.
func (c *TicketPullRequestClient) Use(hooks ...Hook) {
	c.hooks.TicketPullRequest = append(c.hooks.TicketPullRequest, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ticketpullrequest.Intercept(f(g(h())))`.
func (c *TicketPullRequestClient) Intercept(interceptors ...Interceptor) {
	c.inters.TicketPullRequest = append(c.inters.TicketPullRequest, interceptors...)
}

// Create returns a builder for creating a TicketPullRequest entity.
func (c *TicketPullRequestClient) Create() *TicketPullRequestCreate {
	mutation := newTicketPullRequestMutation(c.config, OpCreate)
	return &TicketPullRequestCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TicketPullRequest entities.
func (c *TicketPullRequestClient) CreateBulk(builders ...*TicketPullRequestCreate) *TicketPullRequestCreateBulk {
	return &TicketPullRequestCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TicketPullRequestClient) MapCreateBulk(slice any, setFunc func(*TicketPullRequestCreate, int)) *TicketPullRequestCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TicketPullRequestCreateBulk{err: fmt.Errorf("calling to TicketPullRequestClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TicketPullRequestCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TicketPullRequestCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TicketPullRequest.
func (c *TicketPullRequestClient) Update() *TicketPullRequestUpdate {
	mutation := newTicketPullRequestMutation(c.config, OpUpdate)
	return &TicketPullRequestUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TicketPullRequestClient) UpdateOne(_m *TicketPullRequest) *TicketPullRequestUpdateOne {
	mutation := newTicketPullRequestMutation(c.config, OpUpdateOne)
	mutation.ticket = &_m.TicketID
	mutation.pull_request = &_m.PullRequestID
	return &TicketPullRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TicketPullRequest.
func (c *TicketPullRequestClient) Delete() *TicketPullRequestDelete {
	mutation := newTicketPullRequestMutation(c.config, OpDelete)
	return &TicketPullRequestDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Query returns a query builder for TicketPullRequest.
func (c *TicketPullRequestClient) Query() *TicketPullRequestQuery {
	return &TicketPullRequestQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTicketPullRequest},
		inters: c.Interceptors(),
	}
}

// QueryTicket queries the ticket edge of a TicketPullRequest.
func (c *TicketPullRequestClient) QueryTicket(_m *TicketPullRequest) *TicketQuery {
	return c.Query().
		Where(ticketpullrequest.TicketID(_m.TicketID), ticketpullrequest.PullRequestID(_m.PullRequestID)).
		QueryTicket()
}

// QueryPullRequest queries the pull_request edge of a TicketPullRequest.
func (c *TicketPullRequestClient) QueryPullRequest(_m *TicketPullRequest) *PullRequestQuery {
	return c.Query().
		Where(ticketpullrequest.TicketID(_m.TicketID), ticketpullrequest.PullRequestID(_m.PullRequestID)).
		QueryPullRequest()
}

// QueryLatestEvidence queries the latest_evidence edge of a TicketPullRequest.
func (c *TicketPullRequestClient) QueryLatestEvidence(_m *TicketPullRequest) *EvidenceQuery {
	return c.Query().
		Where(ticketpullrequest.TicketID(_m.TicketID), ticketpullrequest.PullRequestID(_m.PullRequestID)).
		QueryLatestEvidence()
}

// Hooks returns the client hooks.
func (c *TicketPullRequestClient) Hooks() []Hook {
	return c.hooks.TicketPullRequest
}

// Interceptors returns the client interceptors.
func (c *TicketPullRequestClient) Interceptors() []Interceptor {
	return c.inters.TicketPullRequest
}

func (c *TicketPullRequestClient) mutate(ctx context.Context, m *TicketPullRequestMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TicketPullRequestCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TicketPullRequestUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TicketPullRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TicketPullRequestDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TicketPullRequest mutation op: %q", m.Op())
	}
}

// WorkAreaClient is a client for the WorkArea schema.
type WorkAreaClient struct {
	config
}

// NewWorkAreaClient returns a client for the WorkArea from the given config.
func NewWorkAreaClient(c config) *WorkAreaClient {
	return &WorkAreaClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `workarea.Hooks(f(g(h())))`.
func (c *WorkAreaClient) Use(hooks ...Hook) {
	c.hooks.WorkArea = append(c.hooks.WorkArea, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `workarea.Intercept(f(g(h())))`.
func (c *WorkAreaClient) Intercept(interceptors ...Interceptor) {
	c.inters.WorkArea = append(c.inters.WorkArea, interceptors...)
}

// Create returns a builder for creating a WorkArea entity.
func (c *WorkAreaClient) Create() *WorkAreaCreate {
	mutation := newWorkAreaMutation(c.config, OpCreate)
	return &WorkAreaCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of WorkArea entities.
func (c *WorkAreaClient) CreateBulk(builders ...*WorkAreaCreate) *WorkAreaCreateBulk {
	return &WorkAreaCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WorkAreaClient) MapCreateBulk(slice any, setFunc func(*WorkAreaCreate, int)) *WorkAreaCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WorkAreaCreateBulk{err: fmt.Errorf("calling to WorkAreaClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WorkAreaCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WorkAreaCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for WorkArea.
func (c *WorkAreaClient) Update() *WorkAreaUpdate {
	mutation := newWorkAreaMutation(c.config, OpUpdate)
	return &WorkAreaUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WorkAreaClient) UpdateOne(_m *WorkArea) *WorkAreaUpdateOne {
	mutation := newWorkAreaMutation(c.config, OpUpdateOne, withWorkArea(_m))
	return &WorkAreaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WorkAreaClient) UpdateOneID(id int) *WorkAreaUpdateOne {
	mutation := newWorkAreaMutation(c.config, OpUpdateOne, withWorkAreaID(id))
	return &WorkAreaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for WorkArea.
func (c *WorkAreaClient) Delete() *WorkAreaDelete {
	mutation := newWorkAreaMutation(c.config, OpDelete)
	return &WorkAreaDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WorkAreaClient) DeleteOne(_m *WorkArea) *WorkAreaDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WorkAreaClient) DeleteOneID(id int) *WorkAreaDeleteOne {
	builder := c.Delete().Where(workarea.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WorkAreaDeleteOne{builder}
}

// Query returns a query builder for WorkArea.
func (c *WorkAreaClient) Query() *WorkAreaQuery {
	return &WorkAreaQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWorkArea},
		inters: c.Interceptors(),
	}
}

// Get returns a WorkArea entity by its id.
func (c *WorkAreaClient) Get(ctx context.Context, id int) (*WorkArea, error) {
	return c.Query().Where(workarea.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WorkAreaClient) GetX(ctx context.Context, id int) *WorkArea {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPerson queries the person edge of a WorkArea.
func (c *WorkAreaClient) QueryPerson(_m *WorkArea) *PersonQuery {
	query := (&PersonClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(workarea.Table, workarea.FieldID, id),
			sqlgraph.To(person.Table, person.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, workarea.PersonTable, workarea.PersonColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *WorkAreaClient) Hooks() []Hook {
	return c.hooks.WorkArea
}

// Interceptors returns the client interceptors.
func (c *WorkAreaClient) Interceptors() []Interceptor {
	return c.inters.WorkArea
}

func (c *WorkAreaClient) mutate(ctx context.Context, m *WorkAreaMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WorkAreaCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WorkAreaUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WorkAreaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WorkAreaDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown WorkArea mutation op: %q", m.Op())
	}
}

// WorkstreamClient is a client for the Workstream schema.
type WorkstreamClient struct {
	config
}

// NewWorkstreamClient returns a client for the Workstream from the given config.
func NewWorkstreamClient(c config) *WorkstreamClient {
	return &WorkstreamClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `workstream.Hooks(f(g(h())))`.
func (c *WorkstreamClient) Use(hooks ...Hook) {
	c.hooks.Workstream = append(c.hooks.Workstream, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `workstream.Intercept(f(g(h())))`.
func (c *WorkstreamClient) Intercept(interceptors ...Interceptor) {
	c.inters.Workstream = append(c.inters.Workstream, interceptors...)
}

// Create returns a builder for creating a Workstream entity.
func (c *WorkstreamClient) Create() *WorkstreamCreate {
	mutation := newWorkstreamMutation(c.config, OpCreate)
	return &WorkstreamCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Workstream entities.
func (c *WorkstreamClient) CreateBulk(builders ...*WorkstreamCreate) *WorkstreamCreateBulk {
	return &WorkstreamCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WorkstreamClient) MapCreateBulk(slice any, setFunc func(*WorkstreamCreate, int)) *WorkstreamCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WorkstreamCreateBulk{err: fmt.Errorf("calling to WorkstreamClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WorkstreamCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WorkstreamCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Workstream.
func (c *WorkstreamClient) Update() *WorkstreamUpdate {
	mutation := newWorkstreamMutation(c.config, OpUpdate)
	return &WorkstreamUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WorkstreamClient) UpdateOne(_m *Workstream) *WorkstreamUpdateOne {
	mutation := newWorkstreamMutation(c.config, OpUpdateOne, withWorkstream(_m))
	return &WorkstreamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WorkstreamClient) UpdateOneID(id int) *WorkstreamUpdateOne {
	mutation := newWorkstreamMutation(c.config, OpUpdateOne, withWorkstreamID(id))
	return &WorkstreamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Workstream.
func (c *WorkstreamClient) Delete() *WorkstreamDelete {
	mutation := newWorkstreamMutation(c.config, OpDelete)
	return &WorkstreamDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WorkstreamClient) DeleteOne(_m *Workstream) *WorkstreamDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WorkstreamClient) DeleteOneID(id int) *WorkstreamDeleteOne {
	builder := c.Delete().Where(workstream.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WorkstreamDeleteOne{builder}
}

// Query returns a query builder for Workstream.
func (c *WorkstreamClient) Query() *WorkstreamQuery {
	return &WorkstreamQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWorkstream},
		inters: c.Interceptors(),
	}
}

// Get returns a Workstream entity by its id.
func (c *WorkstreamClient) Get(ctx context.Context, id int) (*Workstream, error) {
	return c.Query().Where(workstream.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WorkstreamClient) GetX(ctx context.Context, id int) *Workstream {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTickets queries the tickets edge of a Workstream.
func (c *WorkstreamClient) QueryTickets(_m *Workstream) *TicketQuery {
	query := (&TicketClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(workstream.Table, workstream.FieldID, id),
			sqlgraph.To(ticket.Table, ticket.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, workstream.TicketsTable, workstream.TicketsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryWorkstreamTickets queries the workstream_tickets edge of a Workstream.
func (c *WorkstreamClient) QueryWorkstreamTickets(_m *Workstream) *WorkstreamTicketQuery {
	query := (&WorkstreamTicketClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(workstream.Table, workstream.FieldID, id),
			sqlgraph.To(workstreamticket.Table, workstreamticket.WorkstreamColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, workstream.WorkstreamTicketsTable, workstream.WorkstreamTicketsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *WorkstreamClient) Hooks() []Hook {
	return c.hooks.Workstream
}

// Interceptors returns the client interceptors.
func (c *WorkstreamClient) Interceptors() []Interceptor {
	return c.inters.Workstream
}

func (c *WorkstreamClient) mutate(ctx context.Context, m *WorkstreamMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WorkstreamCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WorkstreamUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WorkstreamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WorkstreamDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Workstream mutation op: %q", m.Op())
	}
}

// WorkstreamTicketClient is a client for the WorkstreamTicket schema.
type WorkstreamTicketClient struct {
	config
}

// NewWorkstreamTicketClient returns a client for the WorkstreamTicket from the given config.
func NewWorkstreamTicketClient(c config) *WorkstreamTicketClient {
	return &WorkstreamTicketClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `workstreamticket.Hooks(f(g(h())))`.
func (c *WorkstreamTicketClient) Use(hooks ...Hook) {
	c.hooks.WorkstreamTicket = append(c.hooks.WorkstreamTicket, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `workstreamticket.Intercept(f(g(h())))`.
func (c *WorkstreamTicketClient) Intercept(interceptors ...Interceptor) {
	c.inters.WorkstreamTicket = append(c.inters.WorkstreamTicket, interceptors...)
}

// Create returns a builder for creating a WorkstreamTicket entity.
func (c *WorkstreamTicketClient) Create() *WorkstreamTicketCreate {
	mutation := newWorkstreamTicketMutation(c.config, OpCreate)
	return &WorkstreamTicketCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of WorkstreamTicket entities.
func (c *WorkstreamTicketClient) CreateBulk(builders ...*WorkstreamTicketCreate) *WorkstreamTicketCreateBulk {
	return &WorkstreamTicketCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WorkstreamTicketClient) MapCreateBulk(slice any, setFunc func(*WorkstreamTicketCreate, int)) *WorkstreamTicketCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WorkstreamTicketCreateBulk{err: fmt.Errorf("calling to WorkstreamTicketClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WorkstreamTicketCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WorkstreamTicketCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for WorkstreamTicket.
func (c *WorkstreamTicketClient) Update() *WorkstreamTicketUpdate {
	mutation := newWorkstreamTicketMutation(c.config, OpUpdate)
	return &WorkstreamTicketUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WorkstreamTicketClient) UpdateOne(_m *WorkstreamTicket) *WorkstreamTicketUpdateOne {
	mutation := newWorkstreamTicketMutation(c.config, OpUpdateOne)
	mutation.workstream = &_m.WorkstreamID
	mutation.ticket = &_m.TicketID
	return &WorkstreamTicketUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for WorkstreamTicket.
func (c *WorkstreamTicketClient) Delete() *WorkstreamTicketDelete {
	mutation := newWorkstreamTicketMutation(c.config, OpDelete)
	return &WorkstreamTicketDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Query returns a query builder for WorkstreamTicket.
func (c *WorkstreamTicketClient) Query() *WorkstreamTicketQuery {
	return &WorkstreamTicketQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWorkstreamTicket},
		inters: c.Interceptors(),
	}
}

// QueryWorkstream queries the workstream edge of a WorkstreamTicket.
func (c *WorkstreamTicketClient) QueryWorkstream(_m *WorkstreamTicket) *WorkstreamQuery {
	return c.Query().
		Where(workstreamticket.WorkstreamID(_m.WorkstreamID), workstreamticket.TicketID(_m.TicketID)).
		QueryWorkstream()
}

// QueryTicket queries the ticket edge of a WorkstreamTicket.
func (c *WorkstreamTicketClient) QueryTicket(_m *WorkstreamTicket) *TicketQuery {
	return c.Query().
		Where(workstreamticket.WorkstreamID(_m.WorkstreamID), workstreamticket.TicketID(_m.TicketID)).
		QueryTicket()
}

// QueryLatestEvidence queries the latest_evidence edge of a WorkstreamTicket.
func (c *WorkstreamTicketClient) QueryLatestEvidence(_m *WorkstreamTicket) *EvidenceQuery {
	return c.Query().
		Where(workstreamticket.WorkstreamID(_m.WorkstreamID), workstreamticket.TicketID(_m.TicketID)).
		QueryLatestEvidence()
}

// Hooks returns the client hooks.
func (c *WorkstreamTicketClient) Hooks() []Hook {
	return c.hooks.WorkstreamTicket
}

// Interceptors returns the client interceptors.
func (c *WorkstreamTicketClient) Interceptors() []Interceptor {
	return c.inters.WorkstreamTicket
}

func (c *WorkstreamTicketClient) mutate(ctx context.Context, m *WorkstreamTicketMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WorkstreamTicketCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WorkstreamTicketUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WorkstreamTicketUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WorkstreamTicketDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown WorkstreamTicket mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Document, DocumentFragment, Evidence, Message, Person, PullRequest, Ticket,
		TicketDocumentFragment, TicketMessage, TicketPullRequest, WorkArea, Workstream,
		WorkstreamTicket []ent.Hook
	}
	inters struct {
		Document, DocumentFragment, Evidence, Message, Person, PullRequest, Ticket,
		TicketDocumentFragment, TicketMessage, TicketPullRequest, WorkArea, Workstream,
		WorkstreamTicket []ent.Interceptor
	}
)
