// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cubicle/services/ontology-service/ent/documentlensresult"
	"cubicle/services/ontology-service/ent/evidence"
	"cubicle/services/ontology-service/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DocumentLensResultUpdate is the builder for updating DocumentLensResult entities.
type DocumentLensResultUpdate struct {
	config
	hooks    []Hook
	mutation *DocumentLensResultMutation
}

// Where appends a list predicates to the DocumentLensResultUpdate builder.
func (_u *DocumentLensResultUpdate) Where(ps ...predicate.DocumentLensResult) *DocumentLensResultUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLatestEvidenceID sets the "latest_evidence_id" field.
func (_u *DocumentLensResultUpdate) SetLatestEvidenceID(v int) *DocumentLensResultUpdate {
	_u.mutation.SetLatestEvidenceID(v)
	return _u
}

// SetNillableLatestEvidenceID sets the "latest_evidence_id" field if the given value is not nil.
func (_u *DocumentLensResultUpdate) SetNillableLatestEvidenceID(v *int) *DocumentLensResultUpdate {
	if v != nil {
		_u.SetLatestEvidenceID(*v)
	}
	return _u
}

// ClearLatestEvidenceID clears the value of the "latest_evidence_id" field.
func (_u *DocumentLensResultUpdate) ClearLatestEvidenceID() *DocumentLensResultUpdate {
	_u.mutation.ClearLatestEvidenceID()
	return _u
}

// SetEvidenceCount sets the "evidence_count" field.
func (_u *DocumentLensResultUpdate) SetEvidenceCount(v int) *DocumentLensResultUpdate {
	_u.mutation.ResetEvidenceCount()
	_u.mutation.SetEvidenceCount(v)
	return _u
}

// SetNillableEvidenceCount sets the "evidence_count" field if the given value is not nil.
func (_u *DocumentLensResultUpdate) SetNillableEvidenceCount(v *int) *DocumentLensResultUpdate {
	if v != nil {
		_u.SetEvidenceCount(*v)
	}
	return _u
}

// AddEvidenceCount adds value to the "evidence_count" field.
func (_u *DocumentLensResultUpdate) AddEvidenceCount(v int) *DocumentLensResultUpdate {
	_u.mutation.AddEvidenceCount(v)
	return _u
}

// SetEventCount sets the "event_count" field.
func (_u *DocumentLensResultUpdate) SetEventCount(v int) *DocumentLensResultUpdate {
	_u.mutation.ResetEventCount()
	_u.mutation.SetEventCount(v)
	return _u
}

// SetNillableEventCount sets the "event_count" field if the given value is not nil.
func (_u *DocumentLensResultUpdate) SetNillableEventCount(v *int) *DocumentLensResultUpdate {
	if v != nil {
		_u.SetEventCount(*v)
	}
	return _u
}

// AddEventCount adds value to the "event_count" field.
func (_u *DocumentLensResultUpdate) AddEventCount(v int) *DocumentLensResultUpdate {
	_u.mutation.AddEventCount(v)
	return _u
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_u *DocumentLensResultUpdate) SetFirstSeenAt(v time.Time) *DocumentLensResultUpdate {
	_u.mutation.SetFirstSeenAt(v)
	return _u
}

// SetNillableFirstSeenAt sets the "first_seen_at" field if the given value is not nil.
func (_u *DocumentLensResultUpdate) SetNillableFirstSeenAt(v *time.Time) *DocumentLensResultUpdate {
	if v != nil {
		_u.SetFirstSeenAt(*v)
	}
	return _u
}

// ClearFirstSeenAt clears the value of the "first_seen_at" field.
func (_u *DocumentLensResultUpdate) ClearFirstSeenAt() *DocumentLensResultUpdate {
	_u.mutation.ClearFirstSeenAt()
	return _u
}

// SetLastActivityAt sets the "last_activity_at" field.
func (_u *DocumentLensResultUpdate) SetLastActivityAt(v time.Time) *DocumentLensResultUpdate {
	_u.mutation.SetLastActivityAt(v)
	return _u
}

// SetNillableLastActivityAt sets the "last_activity_at" field if the given value is not nil.
func (_u *DocumentLensResultUpdate) SetNillableLastActivityAt(v *time.Time) *DocumentLensResultUpdate {
	if v != nil {
		_u.SetLastActivityAt(*v)
	}
	return _u
}

// ClearLastActivityAt clears the value of the "last_activity_at" field.
func (_u *DocumentLensResultUpdate) ClearLastActivityAt() *DocumentLensResultUpdate {
	_u.mutation.ClearLastActivityAt()
	return _u
}

// SetRankScore sets the "rank_score" field.
func (_u *DocumentLensResultUpdate) SetRankScore(v float64) *DocumentLensResultUpdate {
	_u.mutation.ResetRankScore()
	_u.mutation.SetRankScore(v)
	return _u
}

// SetNillableRankScore sets the "rank_score" field if the given value is not nil.
func (_u *DocumentLensResultUpdate) SetNillableRankScore(v *float64) *DocumentLensResultUpdate {
	if v != nil {
		_u.SetRankScore(*v)
	}
	return _u
}

// AddRankScore adds value to the "rank_score" field.
func (_u *DocumentLensResultUpdate) AddRankScore(v float64) *DocumentLensResultUpdate {
	_u.mutation.AddRankScore(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *DocumentLensResultUpdate) SetSource(v string) *DocumentLensResultUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *DocumentLensResultUpdate) SetNillableSource(v *string) *DocumentLensResultUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// ClearSource clears the value of the "source" field.
func (_u *DocumentLensResultUpdate) ClearSource() *DocumentLensResultUpdate {
	_u.mutation.ClearSource()
	return _u
}

// SetSourceInstance sets the "source_instance" field.
func (_u *DocumentLensResultUpdate) SetSourceInstance(v string) *DocumentLensResultUpdate {
	_u.mutation.SetSourceInstance(v)
	return _u
}

// SetNillableSourceInstance sets the "source_instance" field if the given value is not nil.
func (_u *DocumentLensResultUpdate) SetNillableSourceInstance(v *string) *DocumentLensResultUpdate {
	if v != nil {
		_u.SetSourceInstance(*v)
	}
	return _u
}

// ClearSourceInstance clears the value of the "source_instance" field.
func (_u *DocumentLensResultUpdate) ClearSourceInstance() *DocumentLensResultUpdate {
	_u.mutation.ClearSourceInstance()
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *DocumentLensResultUpdate) SetExternalID(v string) *DocumentLensResultUpdate {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *DocumentLensResultUpdate) SetNillableExternalID(v *string) *DocumentLensResultUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// ClearExternalID clears the value of the "external_id" field.
func (_u *DocumentLensResultUpdate) ClearExternalID() *DocumentLensResultUpdate {
	_u.mutation.ClearExternalID()
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *DocumentLensResultUpdate) SetSourceURL(v string) *DocumentLensResultUpdate {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *DocumentLensResultUpdate) SetNillableSourceURL(v *string) *DocumentLensResultUpdate {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// ClearSourceURL clears the value of the "source_url" field.
func (_u *DocumentLensResultUpdate) ClearSourceURL() *DocumentLensResultUpdate {
	_u.mutation.ClearSourceURL()
	return _u
}

// SetFreshnessState sets the "freshness_state" field.
func (_u *DocumentLensResultUpdate) SetFreshnessState(v documentlensresult.FreshnessState) *DocumentLensResultUpdate {
	_u.mutation.SetFreshnessState(v)
	return _u
}

// SetNillableFreshnessState sets the "freshness_state" field if the given value is not nil.
func (_u *DocumentLensResultUpdate) SetNillableFreshnessState(v *documentlensresult.FreshnessState) *DocumentLensResultUpdate {
	if v != nil {
		_u.SetFreshnessState(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *DocumentLensResultUpdate) SetVisibility(v documentlensresult.Visibility) *DocumentLensResultUpdate {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *DocumentLensResultUpdate) SetNillableVisibility(v *documentlensresult.Visibility) *DocumentLensResultUpdate {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetConfidence sets the "confidence" field.
func (_u *DocumentLensResultUpdate) SetConfidence(v float64) *DocumentLensResultUpdate {
	_u.mutation.ResetConfidence()
	_u.mutation.SetConfidence(v)
	return _u
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_u *DocumentLensResultUpdate) SetNillableConfidence(v *float64) *DocumentLensResultUpdate {
	if v != nil {
		_u.SetConfidence(*v)
	}
	return _u
}

// AddConfidence adds value to the "confidence" field.
func (_u *DocumentLensResultUpdate) AddConfidence(v float64) *DocumentLensResultUpdate {
	_u.mutation.AddConfidence(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DocumentLensResultUpdate) SetUpdatedAt(v time.Time) *DocumentLensResultUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLatestEvidence sets the "latest_evidence" edge to the Evidence entity.
func (_u *DocumentLensResultUpdate) SetLatestEvidence(v *Evidence) *DocumentLensResultUpdate {
	return _u.SetLatestEvidenceID(v.ID)
}

// Mutation returns the DocumentLensResultMutation object of the builder.
func (_u *DocumentLensResultUpdate) Mutation() *DocumentLensResultMutation {
	return _u.mutation
}

// ClearLatestEvidence clears the "latest_evidence" edge to the Evidence entity.
func (_u *DocumentLensResultUpdate) ClearLatestEvidence() *DocumentLensResultUpdate {
	_u.mutation.ClearLatestEvidence()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DocumentLensResultUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentLensResultUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DocumentLensResultUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentLensResultUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DocumentLensResultUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := documentlensresult.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentLensResultUpdate) check() error {
	if v, ok := _u.mutation.FreshnessState(); ok {
		if err := documentlensresult.FreshnessStateValidator(v); err != nil {
			return &ValidationError{Name: "freshness_state", err: fmt.Errorf(`ent: validator failed for field "DocumentLensResult.freshness_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visibility(); ok {
		if err := documentlensresult.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "DocumentLensResult.visibility": %w`, err)}
		}
	}
	if _u.mutation.LensCleared() && len(_u.mutation.LensIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DocumentLensResult.lens"`)
	}
	if _u.mutation.DocumentCleared() && len(_u.mutation.DocumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DocumentLensResult.document"`)
	}
	return nil
}

func (_u *DocumentLensResultUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(documentlensresult.Table, documentlensresult.Columns, sqlgraph.NewFieldSpec(documentlensresult.FieldWorkLensID, field.TypeInt), sqlgraph.NewFieldSpec(documentlensresult.FieldDocumentID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EvidenceCount(); ok {
		_spec.SetField(documentlensresult.FieldEvidenceCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEvidenceCount(); ok {
		_spec.AddField(documentlensresult.FieldEvidenceCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EventCount(); ok {
		_spec.SetField(documentlensresult.FieldEventCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEventCount(); ok {
		_spec.AddField(documentlensresult.FieldEventCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FirstSeenAt(); ok {
		_spec.SetField(documentlensresult.FieldFirstSeenAt, field.TypeTime, value)
	}
	if _u.mutation.FirstSeenAtCleared() {
		_spec.ClearField(documentlensresult.FieldFirstSeenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastActivityAt(); ok {
		_spec.SetField(documentlensresult.FieldLastActivityAt, field.TypeTime, value)
	}
	if _u.mutation.LastActivityAtCleared() {
		_spec.ClearField(documentlensresult.FieldLastActivityAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RankScore(); ok {
		_spec.SetField(documentlensresult.FieldRankScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRankScore(); ok {
		_spec.AddField(documentlensresult.FieldRankScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(documentlensresult.FieldSource, field.TypeString, value)
	}
	if _u.mutation.SourceCleared() {
		_spec.ClearField(documentlensresult.FieldSource, field.TypeString)
	}
	if value, ok := _u.mutation.SourceInstance(); ok {
		_spec.SetField(documentlensresult.FieldSourceInstance, field.TypeString, value)
	}
	if _u.mutation.SourceInstanceCleared() {
		_spec.ClearField(documentlensresult.FieldSourceInstance, field.TypeString)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(documentlensresult.FieldExternalID, field.TypeString, value)
	}
	if _u.mutation.ExternalIDCleared() {
		_spec.ClearField(documentlensresult.FieldExternalID, field.TypeString)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(documentlensresult.FieldSourceURL, field.TypeString, value)
	}
	if _u.mutation.SourceURLCleared() {
		_spec.ClearField(documentlensresult.FieldSourceURL, field.TypeString)
	}
	if value, ok := _u.mutation.FreshnessState(); ok {
		_spec.SetField(documentlensresult.FieldFreshnessState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(documentlensresult.FieldVisibility, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Confidence(); ok {
		_spec.SetField(documentlensresult.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConfidence(); ok {
		_spec.AddField(documentlensresult.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(documentlensresult.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.LatestEvidenceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   documentlensresult.LatestEvidenceTable,
			Columns: []string{documentlensresult.LatestEvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LatestEvidenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   documentlensresult.LatestEvidenceTable,
			Columns: []string{documentlensresult.LatestEvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{documentlensresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DocumentLensResultUpdateOne is the builder for updating a single DocumentLensResult entity.
type DocumentLensResultUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DocumentLensResultMutation
}

// SetLatestEvidenceID sets the "latest_evidence_id" field.
func (_u *DocumentLensResultUpdateOne) SetLatestEvidenceID(v int) *DocumentLensResultUpdateOne {
	_u.mutation.SetLatestEvidenceID(v)
	return _u
}

// SetNillableLatestEvidenceID sets the "latest_evidence_id" field if the given value is not nil.
func (_u *DocumentLensResultUpdateOne) SetNillableLatestEvidenceID(v *int) *DocumentLensResultUpdateOne {
	if v != nil {
		_u.SetLatestEvidenceID(*v)
	}
	return _u
}

// ClearLatestEvidenceID clears the value of the "latest_evidence_id" field.
func (_u *DocumentLensResultUpdateOne) ClearLatestEvidenceID() *DocumentLensResultUpdateOne {
	_u.mutation.ClearLatestEvidenceID()
	return _u
}

// SetEvidenceCount sets the "evidence_count" field.
func (_u *DocumentLensResultUpdateOne) SetEvidenceCount(v int) *DocumentLensResultUpdateOne {
	_u.mutation.ResetEvidenceCount()
	_u.mutation.SetEvidenceCount(v)
	return _u
}

// SetNillableEvidenceCount sets the "evidence_count" field if the given value is not nil.
func (_u *DocumentLensResultUpdateOne) SetNillableEvidenceCount(v *int) *DocumentLensResultUpdateOne {
	if v != nil {
		_u.SetEvidenceCount(*v)
	}
	return _u
}

// AddEvidenceCount adds value to the "evidence_count" field.
func (_u *DocumentLensResultUpdateOne) AddEvidenceCount(v int) *DocumentLensResultUpdateOne {
	_u.mutation.AddEvidenceCount(v)
	return _u
}

// SetEventCount sets the "event_count" field.
func (_u *DocumentLensResultUpdateOne) SetEventCount(v int) *DocumentLensResultUpdateOne {
	_u.mutation.ResetEventCount()
	_u.mutation.SetEventCount(v)
	return _u
}

// SetNillableEventCount sets the "event_count" field if the given value is not nil.
func (_u *DocumentLensResultUpdateOne) SetNillableEventCount(v *int) *DocumentLensResultUpdateOne {
	if v != nil {
		_u.SetEventCount(*v)
	}
	return _u
}

// AddEventCount adds value to the "event_count" field.
func (_u *DocumentLensResultUpdateOne) AddEventCount(v int) *DocumentLensResultUpdateOne {
	_u.mutation.AddEventCount(v)
	return _u
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_u *DocumentLensResultUpdateOne) SetFirstSeenAt(v time.Time) *DocumentLensResultUpdateOne {
	_u.mutation.SetFirstSeenAt(v)
	return _u
}

// SetNillableFirstSeenAt sets the "first_seen_at" field if the given value is not nil.
func (_u *DocumentLensResultUpdateOne) SetNillableFirstSeenAt(v *time.Time) *DocumentLensResultUpdateOne {
	if v != nil {
		_u.SetFirstSeenAt(*v)
	}
	return _u
}

// ClearFirstSeenAt clears the value of the "first_seen_at" field.
func (_u *DocumentLensResultUpdateOne) ClearFirstSeenAt() *DocumentLensResultUpdateOne {
	_u.mutation.ClearFirstSeenAt()
	return _u
}

// SetLastActivityAt sets the "last_activity_at" field.
func (_u *DocumentLensResultUpdateOne) SetLastActivityAt(v time.Time) *DocumentLensResultUpdateOne {
	_u.mutation.SetLastActivityAt(v)
	return _u
}

// SetNillableLastActivityAt sets the "last_activity_at" field if the given value is not nil.
func (_u *DocumentLensResultUpdateOne) SetNillableLastActivityAt(v *time.Time) *DocumentLensResultUpdateOne {
	if v != nil {
		_u.SetLastActivityAt(*v)
	}
	return _u
}

// ClearLastActivityAt clears the value of the "last_activity_at" field.
func (_u *DocumentLensResultUpdateOne) ClearLastActivityAt() *DocumentLensResultUpdateOne {
	_u.mutation.ClearLastActivityAt()
	return _u
}

// SetRankScore sets the "rank_score" field.
func (_u *DocumentLensResultUpdateOne) SetRankScore(v float64) *DocumentLensResultUpdateOne {
	_u.mutation.ResetRankScore()
	_u.mutation.SetRankScore(v)
	return _u
}

// SetNillableRankScore sets the "rank_score" field if the given value is not nil.
func (_u *DocumentLensResultUpdateOne) SetNillableRankScore(v *float64) *DocumentLensResultUpdateOne {
	if v != nil {
		_u.SetRankScore(*v)
	}
	return _u
}

// AddRankScore adds value to the "rank_score" field.
func (_u *DocumentLensResultUpdateOne) AddRankScore(v float64) *DocumentLensResultUpdateOne {
	_u.mutation.AddRankScore(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *DocumentLensResultUpdateOne) SetSource(v string) *DocumentLensResultUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *DocumentLensResultUpdateOne) SetNillableSource(v *string) *DocumentLensResultUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// ClearSource clears the value of the "source" field.
func (_u *DocumentLensResultUpdateOne) ClearSource() *DocumentLensResultUpdateOne {
	_u.mutation.ClearSource()
	return _u
}

// SetSourceInstance sets the "source_instance" field.
func (_u *DocumentLensResultUpdateOne) SetSourceInstance(v string) *DocumentLensResultUpdateOne {
	_u.mutation.SetSourceInstance(v)
	return _u
}

// SetNillableSourceInstance sets the "source_instance" field if the given value is not nil.
func (_u *DocumentLensResultUpdateOne) SetNillableSourceInstance(v *string) *DocumentLensResultUpdateOne {
	if v != nil {
		_u.SetSourceInstance(*v)
	}
	return _u
}

// ClearSourceInstance clears the value of the "source_instance" field.
func (_u *DocumentLensResultUpdateOne) ClearSourceInstance() *DocumentLensResultUpdateOne {
	_u.mutation.ClearSourceInstance()
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *DocumentLensResultUpdateOne) SetExternalID(v string) *DocumentLensResultUpdateOne {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *DocumentLensResultUpdateOne) SetNillableExternalID(v *string) *DocumentLensResultUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// ClearExternalID clears the value of the "external_id" field.
func (_u *DocumentLensResultUpdateOne) ClearExternalID() *DocumentLensResultUpdateOne {
	_u.mutation.ClearExternalID()
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *DocumentLensResultUpdateOne) SetSourceURL(v string) *DocumentLensResultUpdateOne {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *DocumentLensResultUpdateOne) SetNillableSourceURL(v *string) *DocumentLensResultUpdateOne {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// ClearSourceURL clears the value of the "source_url" field.
func (_u *DocumentLensResultUpdateOne) ClearSourceURL() *DocumentLensResultUpdateOne {
	_u.mutation.ClearSourceURL()
	return _u
}

// SetFreshnessState sets the "freshness_state" field.
func (_u *DocumentLensResultUpdateOne) SetFreshnessState(v documentlensresult.FreshnessState) *DocumentLensResultUpdateOne {
	_u.mutation.SetFreshnessState(v)
	return _u
}

// SetNillableFreshnessState sets the "freshness_state" field if the given value is not nil.
func (_u *DocumentLensResultUpdateOne) SetNillableFreshnessState(v *documentlensresult.FreshnessState) *DocumentLensResultUpdateOne {
	if v != nil {
		_u.SetFreshnessState(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *DocumentLensResultUpdateOne) SetVisibility(v documentlensresult.Visibility) *DocumentLensResultUpdateOne {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *DocumentLensResultUpdateOne) SetNillableVisibility(v *documentlensresult.Visibility) *DocumentLensResultUpdateOne {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetConfidence sets the "confidence" field.
func (_u *DocumentLensResultUpdateOne) SetConfidence(v float64) *DocumentLensResultUpdateOne {
	_u.mutation.ResetConfidence()
	_u.mutation.SetConfidence(v)
	return _u
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_u *DocumentLensResultUpdateOne) SetNillableConfidence(v *float64) *DocumentLensResultUpdateOne {
	if v != nil {
		_u.SetConfidence(*v)
	}
	return _u
}

// AddConfidence adds value to the "confidence" field.
func (_u *DocumentLensResultUpdateOne) AddConfidence(v float64) *DocumentLensResultUpdateOne {
	_u.mutation.AddConfidence(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DocumentLensResultUpdateOne) SetUpdatedAt(v time.Time) *DocumentLensResultUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLatestEvidence sets the "latest_evidence" edge to the Evidence entity.
func (_u *DocumentLensResultUpdateOne) SetLatestEvidence(v *Evidence) *DocumentLensResultUpdateOne {
	return _u.SetLatestEvidenceID(v.ID)
}

// Mutation returns the DocumentLensResultMutation object of the builder.
func (_u *DocumentLensResultUpdateOne) Mutation() *DocumentLensResultMutation {
	return _u.mutation
}

// ClearLatestEvidence clears the "latest_evidence" edge to the Evidence entity.
func (_u *DocumentLensResultUpdateOne) ClearLatestEvidence() *DocumentLensResultUpdateOne {
	_u.mutation.ClearLatestEvidence()
	return _u
}

// Where appends a list predicates to the DocumentLensResultUpdate builder.
func (_u *DocumentLensResultUpdateOne) Where(ps ...predicate.DocumentLensResult) *DocumentLensResultUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DocumentLensResultUpdateOne) Select(field string, fields ...string) *DocumentLensResultUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DocumentLensResult entity.
func (_u *DocumentLensResultUpdateOne) Save(ctx context.Context) (*DocumentLensResult, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentLensResultUpdateOne) SaveX(ctx context.Context) *DocumentLensResult {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DocumentLensResultUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentLensResultUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DocumentLensResultUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := documentlensresult.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentLensResultUpdateOne) check() error {
	if v, ok := _u.mutation.FreshnessState(); ok {
		if err := documentlensresult.FreshnessStateValidator(v); err != nil {
			return &ValidationError{Name: "freshness_state", err: fmt.Errorf(`ent: validator failed for field "DocumentLensResult.freshness_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visibility(); ok {
		if err := documentlensresult.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "DocumentLensResult.visibility": %w`, err)}
		}
	}
	if _u.mutation.LensCleared() && len(_u.mutation.LensIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DocumentLensResult.lens"`)
	}
	if _u.mutation.DocumentCleared() && len(_u.mutation.DocumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DocumentLensResult.document"`)
	}
	return nil
}

func (_u *DocumentLensResultUpdateOne) sqlSave(ctx context.Context) (_node *DocumentLensResult, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(documentlensresult.Table, documentlensresult.Columns, sqlgraph.NewFieldSpec(documentlensresult.FieldWorkLensID, field.TypeInt), sqlgraph.NewFieldSpec(documentlensresult.FieldDocumentID, field.TypeInt))
	if id, ok := _u.mutation.WorkLensID(); !ok {
		return nil, &ValidationError{Name: "work_lens_id", err: errors.New(`ent: missing "DocumentLensResult.work_lens_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.DocumentID(); !ok {
		return nil, &ValidationError{Name: "document_id", err: errors.New(`ent: missing "DocumentLensResult.document_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !documentlensresult.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EvidenceCount(); ok {
		_spec.SetField(documentlensresult.FieldEvidenceCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEvidenceCount(); ok {
		_spec.AddField(documentlensresult.FieldEvidenceCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EventCount(); ok {
		_spec.SetField(documentlensresult.FieldEventCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEventCount(); ok {
		_spec.AddField(documentlensresult.FieldEventCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FirstSeenAt(); ok {
		_spec.SetField(documentlensresult.FieldFirstSeenAt, field.TypeTime, value)
	}
	if _u.mutation.FirstSeenAtCleared() {
		_spec.ClearField(documentlensresult.FieldFirstSeenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastActivityAt(); ok {
		_spec.SetField(documentlensresult.FieldLastActivityAt, field.TypeTime, value)
	}
	if _u.mutation.LastActivityAtCleared() {
		_spec.ClearField(documentlensresult.FieldLastActivityAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RankScore(); ok {
		_spec.SetField(documentlensresult.FieldRankScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRankScore(); ok {
		_spec.AddField(documentlensresult.FieldRankScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(documentlensresult.FieldSource, field.TypeString, value)
	}
	if _u.mutation.SourceCleared() {
		_spec.ClearField(documentlensresult.FieldSource, field.TypeString)
	}
	if value, ok := _u.mutation.SourceInstance(); ok {
		_spec.SetField(documentlensresult.FieldSourceInstance, field.TypeString, value)
	}
	if _u.mutation.SourceInstanceCleared() {
		_spec.ClearField(documentlensresult.FieldSourceInstance, field.TypeString)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(documentlensresult.FieldExternalID, field.TypeString, value)
	}
	if _u.mutation.ExternalIDCleared() {
		_spec.ClearField(documentlensresult.FieldExternalID, field.TypeString)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(documentlensresult.FieldSourceURL, field.TypeString, value)
	}
	if _u.mutation.SourceURLCleared() {
		_spec.ClearField(documentlensresult.FieldSourceURL, field.TypeString)
	}
	if value, ok := _u.mutation.FreshnessState(); ok {
		_spec.SetField(documentlensresult.FieldFreshnessState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(documentlensresult.FieldVisibility, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Confidence(); ok {
		_spec.SetField(documentlensresult.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConfidence(); ok {
		_spec.AddField(documentlensresult.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(documentlensresult.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.LatestEvidenceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   documentlensresult.LatestEvidenceTable,
			Columns: []string{documentlensresult.LatestEvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LatestEvidenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   documentlensresult.LatestEvidenceTable,
			Columns: []string{documentlensresult.LatestEvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DocumentLensResult{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{documentlensresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
