// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cubicle/services/ontology-service/ent/predicate"
	"cubicle/services/ontology-service/ent/sourcesnapshot"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SourceSnapshotUpdate is the builder for updating SourceSnapshot entities.
type SourceSnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *SourceSnapshotMutation
}

// Where appends a list predicates to the SourceSnapshotUpdate builder.
func (_u *SourceSnapshotUpdate) Where(ps ...predicate.SourceSnapshot) *SourceSnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSnapshotKey sets the "snapshot_key" field.
func (_u *SourceSnapshotUpdate) SetSnapshotKey(v string) *SourceSnapshotUpdate {
	_u.mutation.SetSnapshotKey(v)
	return _u
}

// SetNillableSnapshotKey sets the "snapshot_key" field if the given value is not nil.
func (_u *SourceSnapshotUpdate) SetNillableSnapshotKey(v *string) *SourceSnapshotUpdate {
	if v != nil {
		_u.SetSnapshotKey(*v)
	}
	return _u
}

// SetRunKey sets the "run_key" field.
func (_u *SourceSnapshotUpdate) SetRunKey(v string) *SourceSnapshotUpdate {
	_u.mutation.SetRunKey(v)
	return _u
}

// SetNillableRunKey sets the "run_key" field if the given value is not nil.
func (_u *SourceSnapshotUpdate) SetNillableRunKey(v *string) *SourceSnapshotUpdate {
	if v != nil {
		_u.SetRunKey(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *SourceSnapshotUpdate) SetSource(v string) *SourceSnapshotUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *SourceSnapshotUpdate) SetNillableSource(v *string) *SourceSnapshotUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSourceInstance sets the "source_instance" field.
func (_u *SourceSnapshotUpdate) SetSourceInstance(v string) *SourceSnapshotUpdate {
	_u.mutation.SetSourceInstance(v)
	return _u
}

// SetNillableSourceInstance sets the "source_instance" field if the given value is not nil.
func (_u *SourceSnapshotUpdate) SetNillableSourceInstance(v *string) *SourceSnapshotUpdate {
	if v != nil {
		_u.SetSourceInstance(*v)
	}
	return _u
}

// SetSourceObjectType sets the "source_object_type" field.
func (_u *SourceSnapshotUpdate) SetSourceObjectType(v string) *SourceSnapshotUpdate {
	_u.mutation.SetSourceObjectType(v)
	return _u
}

// SetNillableSourceObjectType sets the "source_object_type" field if the given value is not nil.
func (_u *SourceSnapshotUpdate) SetNillableSourceObjectType(v *string) *SourceSnapshotUpdate {
	if v != nil {
		_u.SetSourceObjectType(*v)
	}
	return _u
}

// SetSourceObjectID sets the "source_object_id" field.
func (_u *SourceSnapshotUpdate) SetSourceObjectID(v string) *SourceSnapshotUpdate {
	_u.mutation.SetSourceObjectID(v)
	return _u
}

// SetNillableSourceObjectID sets the "source_object_id" field if the given value is not nil.
func (_u *SourceSnapshotUpdate) SetNillableSourceObjectID(v *string) *SourceSnapshotUpdate {
	if v != nil {
		_u.SetSourceObjectID(*v)
	}
	return _u
}

// SetBodySha256 sets the "body_sha256" field.
func (_u *SourceSnapshotUpdate) SetBodySha256(v string) *SourceSnapshotUpdate {
	_u.mutation.SetBodySha256(v)
	return _u
}

// SetNillableBodySha256 sets the "body_sha256" field if the given value is not nil.
func (_u *SourceSnapshotUpdate) SetNillableBodySha256(v *string) *SourceSnapshotUpdate {
	if v != nil {
		_u.SetBodySha256(*v)
	}
	return _u
}

// SetBodyRef sets the "body_ref" field.
func (_u *SourceSnapshotUpdate) SetBodyRef(v string) *SourceSnapshotUpdate {
	_u.mutation.SetBodyRef(v)
	return _u
}

// SetNillableBodyRef sets the "body_ref" field if the given value is not nil.
func (_u *SourceSnapshotUpdate) SetNillableBodyRef(v *string) *SourceSnapshotUpdate {
	if v != nil {
		_u.SetBodyRef(*v)
	}
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *SourceSnapshotUpdate) SetSourceURL(v string) *SourceSnapshotUpdate {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *SourceSnapshotUpdate) SetNillableSourceURL(v *string) *SourceSnapshotUpdate {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// SetFetchedAt sets the "fetched_at" field.
func (_u *SourceSnapshotUpdate) SetFetchedAt(v time.Time) *SourceSnapshotUpdate {
	_u.mutation.SetFetchedAt(v)
	return _u
}

// SetNillableFetchedAt sets the "fetched_at" field if the given value is not nil.
func (_u *SourceSnapshotUpdate) SetNillableFetchedAt(v *time.Time) *SourceSnapshotUpdate {
	if v != nil {
		_u.SetFetchedAt(*v)
	}
	return _u
}

// SetHeadersJSON sets the "headers_json" field.
func (_u *SourceSnapshotUpdate) SetHeadersJSON(v string) *SourceSnapshotUpdate {
	_u.mutation.SetHeadersJSON(v)
	return _u
}

// SetNillableHeadersJSON sets the "headers_json" field if the given value is not nil.
func (_u *SourceSnapshotUpdate) SetNillableHeadersJSON(v *string) *SourceSnapshotUpdate {
	if v != nil {
		_u.SetHeadersJSON(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SourceSnapshotUpdate) SetCreatedAt(v time.Time) *SourceSnapshotUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SourceSnapshotUpdate) SetNillableCreatedAt(v *time.Time) *SourceSnapshotUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the SourceSnapshotMutation object of the builder.
func (_u *SourceSnapshotUpdate) Mutation() *SourceSnapshotMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SourceSnapshotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SourceSnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SourceSnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SourceSnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SourceSnapshotUpdate) check() error {
	if v, ok := _u.mutation.SnapshotKey(); ok {
		if err := sourcesnapshot.SnapshotKeyValidator(v); err != nil {
			return &ValidationError{Name: "snapshot_key", err: fmt.Errorf(`ent: validator failed for field "SourceSnapshot.snapshot_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RunKey(); ok {
		if err := sourcesnapshot.RunKeyValidator(v); err != nil {
			return &ValidationError{Name: "run_key", err: fmt.Errorf(`ent: validator failed for field "SourceSnapshot.run_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := sourcesnapshot.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "SourceSnapshot.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceInstance(); ok {
		if err := sourcesnapshot.SourceInstanceValidator(v); err != nil {
			return &ValidationError{Name: "source_instance", err: fmt.Errorf(`ent: validator failed for field "SourceSnapshot.source_instance": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BodySha256(); ok {
		if err := sourcesnapshot.BodySha256Validator(v); err != nil {
			return &ValidationError{Name: "body_sha256", err: fmt.Errorf(`ent: validator failed for field "SourceSnapshot.body_sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BodyRef(); ok {
		if err := sourcesnapshot.BodyRefValidator(v); err != nil {
			return &ValidationError{Name: "body_ref", err: fmt.Errorf(`ent: validator failed for field "SourceSnapshot.body_ref": %w`, err)}
		}
	}
	return nil
}

func (_u *SourceSnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sourcesnapshot.Table, sourcesnapshot.Columns, sqlgraph.NewFieldSpec(sourcesnapshot.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SnapshotKey(); ok {
		_spec.SetField(sourcesnapshot.FieldSnapshotKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunKey(); ok {
		_spec.SetField(sourcesnapshot.FieldRunKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(sourcesnapshot.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceInstance(); ok {
		_spec.SetField(sourcesnapshot.FieldSourceInstance, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceObjectType(); ok {
		_spec.SetField(sourcesnapshot.FieldSourceObjectType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceObjectID(); ok {
		_spec.SetField(sourcesnapshot.FieldSourceObjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BodySha256(); ok {
		_spec.SetField(sourcesnapshot.FieldBodySha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.BodyRef(); ok {
		_spec.SetField(sourcesnapshot.FieldBodyRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(sourcesnapshot.FieldSourceURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.FetchedAt(); ok {
		_spec.SetField(sourcesnapshot.FieldFetchedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.HeadersJSON(); ok {
		_spec.SetField(sourcesnapshot.FieldHeadersJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(sourcesnapshot.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sourcesnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SourceSnapshotUpdateOne is the builder for updating a single SourceSnapshot entity.
type SourceSnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SourceSnapshotMutation
}

// SetSnapshotKey sets the "snapshot_key" field.
func (_u *SourceSnapshotUpdateOne) SetSnapshotKey(v string) *SourceSnapshotUpdateOne {
	_u.mutation.SetSnapshotKey(v)
	return _u
}

// SetNillableSnapshotKey sets the "snapshot_key" field if the given value is not nil.
func (_u *SourceSnapshotUpdateOne) SetNillableSnapshotKey(v *string) *SourceSnapshotUpdateOne {
	if v != nil {
		_u.SetSnapshotKey(*v)
	}
	return _u
}

// SetRunKey sets the "run_key" field.
func (_u *SourceSnapshotUpdateOne) SetRunKey(v string) *SourceSnapshotUpdateOne {
	_u.mutation.SetRunKey(v)
	return _u
}

// SetNillableRunKey sets the "run_key" field if the given value is not nil.
func (_u *SourceSnapshotUpdateOne) SetNillableRunKey(v *string) *SourceSnapshotUpdateOne {
	if v != nil {
		_u.SetRunKey(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *SourceSnapshotUpdateOne) SetSource(v string) *SourceSnapshotUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *SourceSnapshotUpdateOne) SetNillableSource(v *string) *SourceSnapshotUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSourceInstance sets the "source_instance" field.
func (_u *SourceSnapshotUpdateOne) SetSourceInstance(v string) *SourceSnapshotUpdateOne {
	_u.mutation.SetSourceInstance(v)
	return _u
}

// SetNillableSourceInstance sets the "source_instance" field if the given value is not nil.
func (_u *SourceSnapshotUpdateOne) SetNillableSourceInstance(v *string) *SourceSnapshotUpdateOne {
	if v != nil {
		_u.SetSourceInstance(*v)
	}
	return _u
}

// SetSourceObjectType sets the "source_object_type" field.
func (_u *SourceSnapshotUpdateOne) SetSourceObjectType(v string) *SourceSnapshotUpdateOne {
	_u.mutation.SetSourceObjectType(v)
	return _u
}

// SetNillableSourceObjectType sets the "source_object_type" field if the given value is not nil.
func (_u *SourceSnapshotUpdateOne) SetNillableSourceObjectType(v *string) *SourceSnapshotUpdateOne {
	if v != nil {
		_u.SetSourceObjectType(*v)
	}
	return _u
}

// SetSourceObjectID sets the "source_object_id" field.
func (_u *SourceSnapshotUpdateOne) SetSourceObjectID(v string) *SourceSnapshotUpdateOne {
	_u.mutation.SetSourceObjectID(v)
	return _u
}

// SetNillableSourceObjectID sets the "source_object_id" field if the given value is not nil.
func (_u *SourceSnapshotUpdateOne) SetNillableSourceObjectID(v *string) *SourceSnapshotUpdateOne {
	if v != nil {
		_u.SetSourceObjectID(*v)
	}
	return _u
}

// SetBodySha256 sets the "body_sha256" field.
func (_u *SourceSnapshotUpdateOne) SetBodySha256(v string) *SourceSnapshotUpdateOne {
	_u.mutation.SetBodySha256(v)
	return _u
}

// SetNillableBodySha256 sets the "body_sha256" field if the given value is not nil.
func (_u *SourceSnapshotUpdateOne) SetNillableBodySha256(v *string) *SourceSnapshotUpdateOne {
	if v != nil {
		_u.SetBodySha256(*v)
	}
	return _u
}

// SetBodyRef sets the "body_ref" field.
func (_u *SourceSnapshotUpdateOne) SetBodyRef(v string) *SourceSnapshotUpdateOne {
	_u.mutation.SetBodyRef(v)
	return _u
}

// SetNillableBodyRef sets the "body_ref" field if the given value is not nil.
func (_u *SourceSnapshotUpdateOne) SetNillableBodyRef(v *string) *SourceSnapshotUpdateOne {
	if v != nil {
		_u.SetBodyRef(*v)
	}
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *SourceSnapshotUpdateOne) SetSourceURL(v string) *SourceSnapshotUpdateOne {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *SourceSnapshotUpdateOne) SetNillableSourceURL(v *string) *SourceSnapshotUpdateOne {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// SetFetchedAt sets the "fetched_at" field.
func (_u *SourceSnapshotUpdateOne) SetFetchedAt(v time.Time) *SourceSnapshotUpdateOne {
	_u.mutation.SetFetchedAt(v)
	return _u
}

// SetNillableFetchedAt sets the "fetched_at" field if the given value is not nil.
func (_u *SourceSnapshotUpdateOne) SetNillableFetchedAt(v *time.Time) *SourceSnapshotUpdateOne {
	if v != nil {
		_u.SetFetchedAt(*v)
	}
	return _u
}

// SetHeadersJSON sets the "headers_json" field.
func (_u *SourceSnapshotUpdateOne) SetHeadersJSON(v string) *SourceSnapshotUpdateOne {
	_u.mutation.SetHeadersJSON(v)
	return _u
}

// SetNillableHeadersJSON sets the "headers_json" field if the given value is not nil.
func (_u *SourceSnapshotUpdateOne) SetNillableHeadersJSON(v *string) *SourceSnapshotUpdateOne {
	if v != nil {
		_u.SetHeadersJSON(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SourceSnapshotUpdateOne) SetCreatedAt(v time.Time) *SourceSnapshotUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SourceSnapshotUpdateOne) SetNillableCreatedAt(v *time.Time) *SourceSnapshotUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the SourceSnapshotMutation object of the builder.
func (_u *SourceSnapshotUpdateOne) Mutation() *SourceSnapshotMutation {
	return _u.mutation
}

// Where appends a list predicates to the SourceSnapshotUpdate builder.
func (_u *SourceSnapshotUpdateOne) Where(ps ...predicate.SourceSnapshot) *SourceSnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SourceSnapshotUpdateOne) Select(field string, fields ...string) *SourceSnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SourceSnapshot entity.
func (_u *SourceSnapshotUpdateOne) Save(ctx context.Context) (*SourceSnapshot, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SourceSnapshotUpdateOne) SaveX(ctx context.Context) *SourceSnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SourceSnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SourceSnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SourceSnapshotUpdateOne) check() error {
	if v, ok := _u.mutation.SnapshotKey(); ok {
		if err := sourcesnapshot.SnapshotKeyValidator(v); err != nil {
			return &ValidationError{Name: "snapshot_key", err: fmt.Errorf(`ent: validator failed for field "SourceSnapshot.snapshot_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RunKey(); ok {
		if err := sourcesnapshot.RunKeyValidator(v); err != nil {
			return &ValidationError{Name: "run_key", err: fmt.Errorf(`ent: validator failed for field "SourceSnapshot.run_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := sourcesnapshot.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "SourceSnapshot.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceInstance(); ok {
		if err := sourcesnapshot.SourceInstanceValidator(v); err != nil {
			return &ValidationError{Name: "source_instance", err: fmt.Errorf(`ent: validator failed for field "SourceSnapshot.source_instance": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BodySha256(); ok {
		if err := sourcesnapshot.BodySha256Validator(v); err != nil {
			return &ValidationError{Name: "body_sha256", err: fmt.Errorf(`ent: validator failed for field "SourceSnapshot.body_sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BodyRef(); ok {
		if err := sourcesnapshot.BodyRefValidator(v); err != nil {
			return &ValidationError{Name: "body_ref", err: fmt.Errorf(`ent: validator failed for field "SourceSnapshot.body_ref": %w`, err)}
		}
	}
	return nil
}

func (_u *SourceSnapshotUpdateOne) sqlSave(ctx context.Context) (_node *SourceSnapshot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sourcesnapshot.Table, sourcesnapshot.Columns, sqlgraph.NewFieldSpec(sourcesnapshot.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SourceSnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sourcesnapshot.FieldID)
		for _, f := range fields {
			if !sourcesnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sourcesnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SnapshotKey(); ok {
		_spec.SetField(sourcesnapshot.FieldSnapshotKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunKey(); ok {
		_spec.SetField(sourcesnapshot.FieldRunKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(sourcesnapshot.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceInstance(); ok {
		_spec.SetField(sourcesnapshot.FieldSourceInstance, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceObjectType(); ok {
		_spec.SetField(sourcesnapshot.FieldSourceObjectType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceObjectID(); ok {
		_spec.SetField(sourcesnapshot.FieldSourceObjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BodySha256(); ok {
		_spec.SetField(sourcesnapshot.FieldBodySha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.BodyRef(); ok {
		_spec.SetField(sourcesnapshot.FieldBodyRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(sourcesnapshot.FieldSourceURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.FetchedAt(); ok {
		_spec.SetField(sourcesnapshot.FieldFetchedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.HeadersJSON(); ok {
		_spec.SetField(sourcesnapshot.FieldHeadersJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(sourcesnapshot.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &SourceSnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sourcesnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
