// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cubicle/services/ontology-service/ent/evidence"
	"cubicle/services/ontology-service/ent/pullrequest"
	"cubicle/services/ontology-service/ent/ticket"
	"cubicle/services/ontology-service/ent/ticketpullrequest"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TicketPullRequestCreate is the builder for creating a TicketPullRequest entity.
type TicketPullRequestCreate struct {
	config
	mutation *TicketPullRequestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTicketID sets the "ticket_id" field.
func (_c *TicketPullRequestCreate) SetTicketID(v int) *TicketPullRequestCreate {
	_c.mutation.SetTicketID(v)
	return _c
}

// SetPullRequestID sets the "pull_request_id" field.
func (_c *TicketPullRequestCreate) SetPullRequestID(v int) *TicketPullRequestCreate {
	_c.mutation.SetPullRequestID(v)
	return _c
}

// SetTicketPullRequestKind sets the "ticket_pull_request_kind" field.
func (_c *TicketPullRequestCreate) SetTicketPullRequestKind(v ticketpullrequest.TicketPullRequestKind) *TicketPullRequestCreate {
	_c.mutation.SetTicketPullRequestKind(v)
	return _c
}

// SetLatestEvidenceID sets the "latest_evidence_id" field.
func (_c *TicketPullRequestCreate) SetLatestEvidenceID(v int) *TicketPullRequestCreate {
	_c.mutation.SetLatestEvidenceID(v)
	return _c
}

// SetNillableLatestEvidenceID sets the "latest_evidence_id" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableLatestEvidenceID(v *int) *TicketPullRequestCreate {
	if v != nil {
		_c.SetLatestEvidenceID(*v)
	}
	return _c
}

// SetEvidenceCount sets the "evidence_count" field.
func (_c *TicketPullRequestCreate) SetEvidenceCount(v int) *TicketPullRequestCreate {
	_c.mutation.SetEvidenceCount(v)
	return _c
}

// SetNillableEvidenceCount sets the "evidence_count" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableEvidenceCount(v *int) *TicketPullRequestCreate {
	if v != nil {
		_c.SetEvidenceCount(*v)
	}
	return _c
}

// SetEventCount sets the "event_count" field.
func (_c *TicketPullRequestCreate) SetEventCount(v int) *TicketPullRequestCreate {
	_c.mutation.SetEventCount(v)
	return _c
}

// SetNillableEventCount sets the "event_count" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableEventCount(v *int) *TicketPullRequestCreate {
	if v != nil {
		_c.SetEventCount(*v)
	}
	return _c
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_c *TicketPullRequestCreate) SetFirstSeenAt(v time.Time) *TicketPullRequestCreate {
	_c.mutation.SetFirstSeenAt(v)
	return _c
}

// SetNillableFirstSeenAt sets the "first_seen_at" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableFirstSeenAt(v *time.Time) *TicketPullRequestCreate {
	if v != nil {
		_c.SetFirstSeenAt(*v)
	}
	return _c
}

// SetLastActivityAt sets the "last_activity_at" field.
func (_c *TicketPullRequestCreate) SetLastActivityAt(v time.Time) *TicketPullRequestCreate {
	_c.mutation.SetLastActivityAt(v)
	return _c
}

// SetNillableLastActivityAt sets the "last_activity_at" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableLastActivityAt(v *time.Time) *TicketPullRequestCreate {
	if v != nil {
		_c.SetLastActivityAt(*v)
	}
	return _c
}

// SetRankScore sets the "rank_score" field.
func (_c *TicketPullRequestCreate) SetRankScore(v float64) *TicketPullRequestCreate {
	_c.mutation.SetRankScore(v)
	return _c
}

// SetNillableRankScore sets the "rank_score" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableRankScore(v *float64) *TicketPullRequestCreate {
	if v != nil {
		_c.SetRankScore(*v)
	}
	return _c
}

// SetSourceSystem sets the "source_system" field.
func (_c *TicketPullRequestCreate) SetSourceSystem(v string) *TicketPullRequestCreate {
	_c.mutation.SetSourceSystem(v)
	return _c
}

// SetNillableSourceSystem sets the "source_system" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableSourceSystem(v *string) *TicketPullRequestCreate {
	if v != nil {
		_c.SetSourceSystem(*v)
	}
	return _c
}

// SetSourceInstance sets the "source_instance" field.
func (_c *TicketPullRequestCreate) SetSourceInstance(v string) *TicketPullRequestCreate {
	_c.mutation.SetSourceInstance(v)
	return _c
}

// SetNillableSourceInstance sets the "source_instance" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableSourceInstance(v *string) *TicketPullRequestCreate {
	if v != nil {
		_c.SetSourceInstance(*v)
	}
	return _c
}

// SetExternalKind sets the "external_kind" field.
func (_c *TicketPullRequestCreate) SetExternalKind(v string) *TicketPullRequestCreate {
	_c.mutation.SetExternalKind(v)
	return _c
}

// SetNillableExternalKind sets the "external_kind" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableExternalKind(v *string) *TicketPullRequestCreate {
	if v != nil {
		_c.SetExternalKind(*v)
	}
	return _c
}

// SetExternalID sets the "external_id" field.
func (_c *TicketPullRequestCreate) SetExternalID(v string) *TicketPullRequestCreate {
	_c.mutation.SetExternalID(v)
	return _c
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableExternalID(v *string) *TicketPullRequestCreate {
	if v != nil {
		_c.SetExternalID(*v)
	}
	return _c
}

// SetSourceURL sets the "source_url" field.
func (_c *TicketPullRequestCreate) SetSourceURL(v string) *TicketPullRequestCreate {
	_c.mutation.SetSourceURL(v)
	return _c
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableSourceURL(v *string) *TicketPullRequestCreate {
	if v != nil {
		_c.SetSourceURL(*v)
	}
	return _c
}

// SetSourceVersion sets the "source_version" field.
func (_c *TicketPullRequestCreate) SetSourceVersion(v string) *TicketPullRequestCreate {
	_c.mutation.SetSourceVersion(v)
	return _c
}

// SetNillableSourceVersion sets the "source_version" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableSourceVersion(v *string) *TicketPullRequestCreate {
	if v != nil {
		_c.SetSourceVersion(*v)
	}
	return _c
}

// SetSourceUpdatedAt sets the "source_updated_at" field.
func (_c *TicketPullRequestCreate) SetSourceUpdatedAt(v time.Time) *TicketPullRequestCreate {
	_c.mutation.SetSourceUpdatedAt(v)
	return _c
}

// SetNillableSourceUpdatedAt sets the "source_updated_at" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableSourceUpdatedAt(v *time.Time) *TicketPullRequestCreate {
	if v != nil {
		_c.SetSourceUpdatedAt(*v)
	}
	return _c
}

// SetContentHash sets the "content_hash" field.
func (_c *TicketPullRequestCreate) SetContentHash(v string) *TicketPullRequestCreate {
	_c.mutation.SetContentHash(v)
	return _c
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableContentHash(v *string) *TicketPullRequestCreate {
	if v != nil {
		_c.SetContentHash(*v)
	}
	return _c
}

// SetDeletionState sets the "deletion_state" field.
func (_c *TicketPullRequestCreate) SetDeletionState(v ticketpullrequest.DeletionState) *TicketPullRequestCreate {
	_c.mutation.SetDeletionState(v)
	return _c
}

// SetNillableDeletionState sets the "deletion_state" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableDeletionState(v *ticketpullrequest.DeletionState) *TicketPullRequestCreate {
	if v != nil {
		_c.SetDeletionState(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *TicketPullRequestCreate) SetDeletedAt(v time.Time) *TicketPullRequestCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableDeletedAt(v *time.Time) *TicketPullRequestCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetACLPolicyKey sets the "acl_policy_key" field.
func (_c *TicketPullRequestCreate) SetACLPolicyKey(v string) *TicketPullRequestCreate {
	_c.mutation.SetACLPolicyKey(v)
	return _c
}

// SetNillableACLPolicyKey sets the "acl_policy_key" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableACLPolicyKey(v *string) *TicketPullRequestCreate {
	if v != nil {
		_c.SetACLPolicyKey(*v)
	}
	return _c
}

// SetVisibilityHash sets the "visibility_hash" field.
func (_c *TicketPullRequestCreate) SetVisibilityHash(v string) *TicketPullRequestCreate {
	_c.mutation.SetVisibilityHash(v)
	return _c
}

// SetNillableVisibilityHash sets the "visibility_hash" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableVisibilityHash(v *string) *TicketPullRequestCreate {
	if v != nil {
		_c.SetVisibilityHash(*v)
	}
	return _c
}

// SetACLState sets the "acl_state" field.
func (_c *TicketPullRequestCreate) SetACLState(v ticketpullrequest.ACLState) *TicketPullRequestCreate {
	_c.mutation.SetACLState(v)
	return _c
}

// SetNillableACLState sets the "acl_state" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableACLState(v *ticketpullrequest.ACLState) *TicketPullRequestCreate {
	if v != nil {
		_c.SetACLState(*v)
	}
	return _c
}

// SetACLCheckedAt sets the "acl_checked_at" field.
func (_c *TicketPullRequestCreate) SetACLCheckedAt(v time.Time) *TicketPullRequestCreate {
	_c.mutation.SetACLCheckedAt(v)
	return _c
}

// SetNillableACLCheckedAt sets the "acl_checked_at" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableACLCheckedAt(v *time.Time) *TicketPullRequestCreate {
	if v != nil {
		_c.SetACLCheckedAt(*v)
	}
	return _c
}

// SetFreshnessCheckedAt sets the "freshness_checked_at" field.
func (_c *TicketPullRequestCreate) SetFreshnessCheckedAt(v time.Time) *TicketPullRequestCreate {
	_c.mutation.SetFreshnessCheckedAt(v)
	return _c
}

// SetNillableFreshnessCheckedAt sets the "freshness_checked_at" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableFreshnessCheckedAt(v *time.Time) *TicketPullRequestCreate {
	if v != nil {
		_c.SetFreshnessCheckedAt(*v)
	}
	return _c
}

// SetSourceScopeStateID sets the "source_scope_state_id" field.
func (_c *TicketPullRequestCreate) SetSourceScopeStateID(v int) *TicketPullRequestCreate {
	_c.mutation.SetSourceScopeStateID(v)
	return _c
}

// SetNillableSourceScopeStateID sets the "source_scope_state_id" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableSourceScopeStateID(v *int) *TicketPullRequestCreate {
	if v != nil {
		_c.SetSourceScopeStateID(*v)
	}
	return _c
}

// SetLastConfirmedAt sets the "last_confirmed_at" field.
func (_c *TicketPullRequestCreate) SetLastConfirmedAt(v time.Time) *TicketPullRequestCreate {
	_c.mutation.SetLastConfirmedAt(v)
	return _c
}

// SetNillableLastConfirmedAt sets the "last_confirmed_at" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableLastConfirmedAt(v *time.Time) *TicketPullRequestCreate {
	if v != nil {
		_c.SetLastConfirmedAt(*v)
	}
	return _c
}

// SetLastChangedAt sets the "last_changed_at" field.
func (_c *TicketPullRequestCreate) SetLastChangedAt(v time.Time) *TicketPullRequestCreate {
	_c.mutation.SetLastChangedAt(v)
	return _c
}

// SetNillableLastChangedAt sets the "last_changed_at" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableLastChangedAt(v *time.Time) *TicketPullRequestCreate {
	if v != nil {
		_c.SetLastChangedAt(*v)
	}
	return _c
}

// SetFreshnessState sets the "freshness_state" field.
func (_c *TicketPullRequestCreate) SetFreshnessState(v ticketpullrequest.FreshnessState) *TicketPullRequestCreate {
	_c.mutation.SetFreshnessState(v)
	return _c
}

// SetNillableFreshnessState sets the "freshness_state" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableFreshnessState(v *ticketpullrequest.FreshnessState) *TicketPullRequestCreate {
	if v != nil {
		_c.SetFreshnessState(*v)
	}
	return _c
}

// SetVisibility sets the "visibility" field.
func (_c *TicketPullRequestCreate) SetVisibility(v ticketpullrequest.Visibility) *TicketPullRequestCreate {
	_c.mutation.SetVisibility(v)
	return _c
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableVisibility(v *ticketpullrequest.Visibility) *TicketPullRequestCreate {
	if v != nil {
		_c.SetVisibility(*v)
	}
	return _c
}

// SetConfidence sets the "confidence" field.
func (_c *TicketPullRequestCreate) SetConfidence(v float64) *TicketPullRequestCreate {
	_c.mutation.SetConfidence(v)
	return _c
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableConfidence(v *float64) *TicketPullRequestCreate {
	if v != nil {
		_c.SetConfidence(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TicketPullRequestCreate) SetCreatedAt(v time.Time) *TicketPullRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableCreatedAt(v *time.Time) *TicketPullRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TicketPullRequestCreate) SetUpdatedAt(v time.Time) *TicketPullRequestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TicketPullRequestCreate) SetNillableUpdatedAt(v *time.Time) *TicketPullRequestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTicket sets the "ticket" edge to the Ticket entity.
func (_c *TicketPullRequestCreate) SetTicket(v *Ticket) *TicketPullRequestCreate {
	return _c.SetTicketID(v.ID)
}

// SetPullRequest sets the "pull_request" edge to the PullRequest entity.
func (_c *TicketPullRequestCreate) SetPullRequest(v *PullRequest) *TicketPullRequestCreate {
	return _c.SetPullRequestID(v.ID)
}

// SetLatestEvidence sets the "latest_evidence" edge to the Evidence entity.
func (_c *TicketPullRequestCreate) SetLatestEvidence(v *Evidence) *TicketPullRequestCreate {
	return _c.SetLatestEvidenceID(v.ID)
}

// Mutation returns the TicketPullRequestMutation object of the builder.
func (_c *TicketPullRequestCreate) Mutation() *TicketPullRequestMutation {
	return _c.mutation
}

// Save creates the TicketPullRequest in the database.
func (_c *TicketPullRequestCreate) Save(ctx context.Context) (*TicketPullRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TicketPullRequestCreate) SaveX(ctx context.Context) *TicketPullRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketPullRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketPullRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TicketPullRequestCreate) defaults() {
	if _, ok := _c.mutation.EvidenceCount(); !ok {
		v := ticketpullrequest.DefaultEvidenceCount
		_c.mutation.SetEvidenceCount(v)
	}
	if _, ok := _c.mutation.EventCount(); !ok {
		v := ticketpullrequest.DefaultEventCount
		_c.mutation.SetEventCount(v)
	}
	if _, ok := _c.mutation.RankScore(); !ok {
		v := ticketpullrequest.DefaultRankScore
		_c.mutation.SetRankScore(v)
	}
	if _, ok := _c.mutation.DeletionState(); !ok {
		v := ticketpullrequest.DefaultDeletionState
		_c.mutation.SetDeletionState(v)
	}
	if _, ok := _c.mutation.ACLState(); !ok {
		v := ticketpullrequest.DefaultACLState
		_c.mutation.SetACLState(v)
	}
	if _, ok := _c.mutation.FreshnessState(); !ok {
		v := ticketpullrequest.DefaultFreshnessState
		_c.mutation.SetFreshnessState(v)
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		v := ticketpullrequest.DefaultVisibility
		_c.mutation.SetVisibility(v)
	}
	if _, ok := _c.mutation.Confidence(); !ok {
		v := ticketpullrequest.DefaultConfidence
		_c.mutation.SetConfidence(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ticketpullrequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ticketpullrequest.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TicketPullRequestCreate) check() error {
	if _, ok := _c.mutation.TicketID(); !ok {
		return &ValidationError{Name: "ticket_id", err: errors.New(`ent: missing required field "TicketPullRequest.ticket_id"`)}
	}
	if _, ok := _c.mutation.PullRequestID(); !ok {
		return &ValidationError{Name: "pull_request_id", err: errors.New(`ent: missing required field "TicketPullRequest.pull_request_id"`)}
	}
	if _, ok := _c.mutation.TicketPullRequestKind(); !ok {
		return &ValidationError{Name: "ticket_pull_request_kind", err: errors.New(`ent: missing required field "TicketPullRequest.ticket_pull_request_kind"`)}
	}
	if v, ok := _c.mutation.TicketPullRequestKind(); ok {
		if err := ticketpullrequest.TicketPullRequestKindValidator(v); err != nil {
			return &ValidationError{Name: "ticket_pull_request_kind", err: fmt.Errorf(`ent: validator failed for field "TicketPullRequest.ticket_pull_request_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EvidenceCount(); !ok {
		return &ValidationError{Name: "evidence_count", err: errors.New(`ent: missing required field "TicketPullRequest.evidence_count"`)}
	}
	if _, ok := _c.mutation.EventCount(); !ok {
		return &ValidationError{Name: "event_count", err: errors.New(`ent: missing required field "TicketPullRequest.event_count"`)}
	}
	if _, ok := _c.mutation.RankScore(); !ok {
		return &ValidationError{Name: "rank_score", err: errors.New(`ent: missing required field "TicketPullRequest.rank_score"`)}
	}
	if _, ok := _c.mutation.DeletionState(); !ok {
		return &ValidationError{Name: "deletion_state", err: errors.New(`ent: missing required field "TicketPullRequest.deletion_state"`)}
	}
	if v, ok := _c.mutation.DeletionState(); ok {
		if err := ticketpullrequest.DeletionStateValidator(v); err != nil {
			return &ValidationError{Name: "deletion_state", err: fmt.Errorf(`ent: validator failed for field "TicketPullRequest.deletion_state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ACLState(); !ok {
		return &ValidationError{Name: "acl_state", err: errors.New(`ent: missing required field "TicketPullRequest.acl_state"`)}
	}
	if v, ok := _c.mutation.ACLState(); ok {
		if err := ticketpullrequest.ACLStateValidator(v); err != nil {
			return &ValidationError{Name: "acl_state", err: fmt.Errorf(`ent: validator failed for field "TicketPullRequest.acl_state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FreshnessState(); !ok {
		return &ValidationError{Name: "freshness_state", err: errors.New(`ent: missing required field "TicketPullRequest.freshness_state"`)}
	}
	if v, ok := _c.mutation.FreshnessState(); ok {
		if err := ticketpullrequest.FreshnessStateValidator(v); err != nil {
			return &ValidationError{Name: "freshness_state", err: fmt.Errorf(`ent: validator failed for field "TicketPullRequest.freshness_state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		return &ValidationError{Name: "visibility", err: errors.New(`ent: missing required field "TicketPullRequest.visibility"`)}
	}
	if v, ok := _c.mutation.Visibility(); ok {
		if err := ticketpullrequest.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "TicketPullRequest.visibility": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Confidence(); !ok {
		return &ValidationError{Name: "confidence", err: errors.New(`ent: missing required field "TicketPullRequest.confidence"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TicketPullRequest.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TicketPullRequest.updated_at"`)}
	}
	if len(_c.mutation.TicketIDs()) == 0 {
		return &ValidationError{Name: "ticket", err: errors.New(`ent: missing required edge "TicketPullRequest.ticket"`)}
	}
	if len(_c.mutation.PullRequestIDs()) == 0 {
		return &ValidationError{Name: "pull_request", err: errors.New(`ent: missing required edge "TicketPullRequest.pull_request"`)}
	}
	return nil
}

func (_c *TicketPullRequestCreate) sqlSave(ctx context.Context) (*TicketPullRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TicketPullRequestCreate) createSpec() (*TicketPullRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &TicketPullRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ticketpullrequest.Table, sqlgraph.NewFieldSpec(ticketpullrequest.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.TicketPullRequestKind(); ok {
		_spec.SetField(ticketpullrequest.FieldTicketPullRequestKind, field.TypeEnum, value)
		_node.TicketPullRequestKind = value
	}
	if value, ok := _c.mutation.EvidenceCount(); ok {
		_spec.SetField(ticketpullrequest.FieldEvidenceCount, field.TypeInt, value)
		_node.EvidenceCount = value
	}
	if value, ok := _c.mutation.EventCount(); ok {
		_spec.SetField(ticketpullrequest.FieldEventCount, field.TypeInt, value)
		_node.EventCount = value
	}
	if value, ok := _c.mutation.FirstSeenAt(); ok {
		_spec.SetField(ticketpullrequest.FieldFirstSeenAt, field.TypeTime, value)
		_node.FirstSeenAt = value
	}
	if value, ok := _c.mutation.LastActivityAt(); ok {
		_spec.SetField(ticketpullrequest.FieldLastActivityAt, field.TypeTime, value)
		_node.LastActivityAt = value
	}
	if value, ok := _c.mutation.RankScore(); ok {
		_spec.SetField(ticketpullrequest.FieldRankScore, field.TypeFloat64, value)
		_node.RankScore = value
	}
	if value, ok := _c.mutation.SourceSystem(); ok {
		_spec.SetField(ticketpullrequest.FieldSourceSystem, field.TypeString, value)
		_node.SourceSystem = value
	}
	if value, ok := _c.mutation.SourceInstance(); ok {
		_spec.SetField(ticketpullrequest.FieldSourceInstance, field.TypeString, value)
		_node.SourceInstance = value
	}
	if value, ok := _c.mutation.ExternalKind(); ok {
		_spec.SetField(ticketpullrequest.FieldExternalKind, field.TypeString, value)
		_node.ExternalKind = value
	}
	if value, ok := _c.mutation.ExternalID(); ok {
		_spec.SetField(ticketpullrequest.FieldExternalID, field.TypeString, value)
		_node.ExternalID = value
	}
	if value, ok := _c.mutation.SourceURL(); ok {
		_spec.SetField(ticketpullrequest.FieldSourceURL, field.TypeString, value)
		_node.SourceURL = value
	}
	if value, ok := _c.mutation.SourceVersion(); ok {
		_spec.SetField(ticketpullrequest.FieldSourceVersion, field.TypeString, value)
		_node.SourceVersion = value
	}
	if value, ok := _c.mutation.SourceUpdatedAt(); ok {
		_spec.SetField(ticketpullrequest.FieldSourceUpdatedAt, field.TypeTime, value)
		_node.SourceUpdatedAt = value
	}
	if value, ok := _c.mutation.ContentHash(); ok {
		_spec.SetField(ticketpullrequest.FieldContentHash, field.TypeString, value)
		_node.ContentHash = value
	}
	if value, ok := _c.mutation.DeletionState(); ok {
		_spec.SetField(ticketpullrequest.FieldDeletionState, field.TypeEnum, value)
		_node.DeletionState = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(ticketpullrequest.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.ACLPolicyKey(); ok {
		_spec.SetField(ticketpullrequest.FieldACLPolicyKey, field.TypeString, value)
		_node.ACLPolicyKey = value
	}
	if value, ok := _c.mutation.VisibilityHash(); ok {
		_spec.SetField(ticketpullrequest.FieldVisibilityHash, field.TypeString, value)
		_node.VisibilityHash = value
	}
	if value, ok := _c.mutation.ACLState(); ok {
		_spec.SetField(ticketpullrequest.FieldACLState, field.TypeEnum, value)
		_node.ACLState = value
	}
	if value, ok := _c.mutation.ACLCheckedAt(); ok {
		_spec.SetField(ticketpullrequest.FieldACLCheckedAt, field.TypeTime, value)
		_node.ACLCheckedAt = value
	}
	if value, ok := _c.mutation.FreshnessCheckedAt(); ok {
		_spec.SetField(ticketpullrequest.FieldFreshnessCheckedAt, field.TypeTime, value)
		_node.FreshnessCheckedAt = value
	}
	if value, ok := _c.mutation.SourceScopeStateID(); ok {
		_spec.SetField(ticketpullrequest.FieldSourceScopeStateID, field.TypeInt, value)
		_node.SourceScopeStateID = value
	}
	if value, ok := _c.mutation.LastConfirmedAt(); ok {
		_spec.SetField(ticketpullrequest.FieldLastConfirmedAt, field.TypeTime, value)
		_node.LastConfirmedAt = value
	}
	if value, ok := _c.mutation.LastChangedAt(); ok {
		_spec.SetField(ticketpullrequest.FieldLastChangedAt, field.TypeTime, value)
		_node.LastChangedAt = value
	}
	if value, ok := _c.mutation.FreshnessState(); ok {
		_spec.SetField(ticketpullrequest.FieldFreshnessState, field.TypeEnum, value)
		_node.FreshnessState = value
	}
	if value, ok := _c.mutation.Visibility(); ok {
		_spec.SetField(ticketpullrequest.FieldVisibility, field.TypeEnum, value)
		_node.Visibility = value
	}
	if value, ok := _c.mutation.Confidence(); ok {
		_spec.SetField(ticketpullrequest.FieldConfidence, field.TypeFloat64, value)
		_node.Confidence = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ticketpullrequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ticketpullrequest.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ticketpullrequest.TicketTable,
			Columns: []string{ticketpullrequest.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TicketID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PullRequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ticketpullrequest.PullRequestTable,
			Columns: []string{ticketpullrequest.PullRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pullrequest.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PullRequestID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LatestEvidenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ticketpullrequest.LatestEvidenceTable,
			Columns: []string{ticketpullrequest.LatestEvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LatestEvidenceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TicketPullRequest.Create().
//		SetTicketID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketPullRequestUpsert) {
//			SetTicketID(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketPullRequestCreate) OnConflict(opts ...sql.ConflictOption) *TicketPullRequestUpsertOne {
	_c.conflict = opts
	return &TicketPullRequestUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TicketPullRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketPullRequestCreate) OnConflictColumns(columns ...string) *TicketPullRequestUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketPullRequestUpsertOne{
		create: _c,
	}
}

type (
	// TicketPullRequestUpsertOne is the builder for "upsert"-ing
	//  one TicketPullRequest node.
	TicketPullRequestUpsertOne struct {
		create *TicketPullRequestCreate
	}

	// TicketPullRequestUpsert is the "OnConflict" setter.
	TicketPullRequestUpsert struct {
		*sql.UpdateSet
	}
)

// SetLatestEvidenceID sets the "latest_evidence_id" field.
func (u *TicketPullRequestUpsert) SetLatestEvidenceID(v int) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldLatestEvidenceID, v)
	return u
}

// UpdateLatestEvidenceID sets the "latest_evidence_id" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateLatestEvidenceID() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldLatestEvidenceID)
	return u
}

// ClearLatestEvidenceID clears the value of the "latest_evidence_id" field.
func (u *TicketPullRequestUpsert) ClearLatestEvidenceID() *TicketPullRequestUpsert {
	u.SetNull(ticketpullrequest.FieldLatestEvidenceID)
	return u
}

// SetEvidenceCount sets the "evidence_count" field.
func (u *TicketPullRequestUpsert) SetEvidenceCount(v int) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldEvidenceCount, v)
	return u
}

// UpdateEvidenceCount sets the "evidence_count" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateEvidenceCount() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldEvidenceCount)
	return u
}

// AddEvidenceCount adds v to the "evidence_count" field.
func (u *TicketPullRequestUpsert) AddEvidenceCount(v int) *TicketPullRequestUpsert {
	u.Add(ticketpullrequest.FieldEvidenceCount, v)
	return u
}

// SetEventCount sets the "event_count" field.
func (u *TicketPullRequestUpsert) SetEventCount(v int) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldEventCount, v)
	return u
}

// UpdateEventCount sets the "event_count" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateEventCount() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldEventCount)
	return u
}

// AddEventCount adds v to the "event_count" field.
func (u *TicketPullRequestUpsert) AddEventCount(v int) *TicketPullRequestUpsert {
	u.Add(ticketpullrequest.FieldEventCount, v)
	return u
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (u *TicketPullRequestUpsert) SetFirstSeenAt(v time.Time) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldFirstSeenAt, v)
	return u
}

// UpdateFirstSeenAt sets the "first_seen_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateFirstSeenAt() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldFirstSeenAt)
	return u
}

// ClearFirstSeenAt clears the value of the "first_seen_at" field.
func (u *TicketPullRequestUpsert) ClearFirstSeenAt() *TicketPullRequestUpsert {
	u.SetNull(ticketpullrequest.FieldFirstSeenAt)
	return u
}

// SetLastActivityAt sets the "last_activity_at" field.
func (u *TicketPullRequestUpsert) SetLastActivityAt(v time.Time) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldLastActivityAt, v)
	return u
}

// UpdateLastActivityAt sets the "last_activity_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateLastActivityAt() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldLastActivityAt)
	return u
}

// ClearLastActivityAt clears the value of the "last_activity_at" field.
func (u *TicketPullRequestUpsert) ClearLastActivityAt() *TicketPullRequestUpsert {
	u.SetNull(ticketpullrequest.FieldLastActivityAt)
	return u
}

// SetRankScore sets the "rank_score" field.
func (u *TicketPullRequestUpsert) SetRankScore(v float64) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldRankScore, v)
	return u
}

// UpdateRankScore sets the "rank_score" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateRankScore() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldRankScore)
	return u
}

// AddRankScore adds v to the "rank_score" field.
func (u *TicketPullRequestUpsert) AddRankScore(v float64) *TicketPullRequestUpsert {
	u.Add(ticketpullrequest.FieldRankScore, v)
	return u
}

// SetSourceSystem sets the "source_system" field.
func (u *TicketPullRequestUpsert) SetSourceSystem(v string) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldSourceSystem, v)
	return u
}

// UpdateSourceSystem sets the "source_system" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateSourceSystem() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldSourceSystem)
	return u
}

// ClearSourceSystem clears the value of the "source_system" field.
func (u *TicketPullRequestUpsert) ClearSourceSystem() *TicketPullRequestUpsert {
	u.SetNull(ticketpullrequest.FieldSourceSystem)
	return u
}

// SetSourceInstance sets the "source_instance" field.
func (u *TicketPullRequestUpsert) SetSourceInstance(v string) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldSourceInstance, v)
	return u
}

// UpdateSourceInstance sets the "source_instance" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateSourceInstance() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldSourceInstance)
	return u
}

// ClearSourceInstance clears the value of the "source_instance" field.
func (u *TicketPullRequestUpsert) ClearSourceInstance() *TicketPullRequestUpsert {
	u.SetNull(ticketpullrequest.FieldSourceInstance)
	return u
}

// SetExternalKind sets the "external_kind" field.
func (u *TicketPullRequestUpsert) SetExternalKind(v string) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldExternalKind, v)
	return u
}

// UpdateExternalKind sets the "external_kind" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateExternalKind() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldExternalKind)
	return u
}

// ClearExternalKind clears the value of the "external_kind" field.
func (u *TicketPullRequestUpsert) ClearExternalKind() *TicketPullRequestUpsert {
	u.SetNull(ticketpullrequest.FieldExternalKind)
	return u
}

// SetExternalID sets the "external_id" field.
func (u *TicketPullRequestUpsert) SetExternalID(v string) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldExternalID, v)
	return u
}

// UpdateExternalID sets the "external_id" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateExternalID() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldExternalID)
	return u
}

// ClearExternalID clears the value of the "external_id" field.
func (u *TicketPullRequestUpsert) ClearExternalID() *TicketPullRequestUpsert {
	u.SetNull(ticketpullrequest.FieldExternalID)
	return u
}

// SetSourceURL sets the "source_url" field.
func (u *TicketPullRequestUpsert) SetSourceURL(v string) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldSourceURL, v)
	return u
}

// UpdateSourceURL sets the "source_url" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateSourceURL() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldSourceURL)
	return u
}

// ClearSourceURL clears the value of the "source_url" field.
func (u *TicketPullRequestUpsert) ClearSourceURL() *TicketPullRequestUpsert {
	u.SetNull(ticketpullrequest.FieldSourceURL)
	return u
}

// SetSourceVersion sets the "source_version" field.
func (u *TicketPullRequestUpsert) SetSourceVersion(v string) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldSourceVersion, v)
	return u
}

// UpdateSourceVersion sets the "source_version" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateSourceVersion() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldSourceVersion)
	return u
}

// ClearSourceVersion clears the value of the "source_version" field.
func (u *TicketPullRequestUpsert) ClearSourceVersion() *TicketPullRequestUpsert {
	u.SetNull(ticketpullrequest.FieldSourceVersion)
	return u
}

// SetSourceUpdatedAt sets the "source_updated_at" field.
func (u *TicketPullRequestUpsert) SetSourceUpdatedAt(v time.Time) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldSourceUpdatedAt, v)
	return u
}

// UpdateSourceUpdatedAt sets the "source_updated_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateSourceUpdatedAt() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldSourceUpdatedAt)
	return u
}

// ClearSourceUpdatedAt clears the value of the "source_updated_at" field.
func (u *TicketPullRequestUpsert) ClearSourceUpdatedAt() *TicketPullRequestUpsert {
	u.SetNull(ticketpullrequest.FieldSourceUpdatedAt)
	return u
}

// SetContentHash sets the "content_hash" field.
func (u *TicketPullRequestUpsert) SetContentHash(v string) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldContentHash, v)
	return u
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateContentHash() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldContentHash)
	return u
}

// ClearContentHash clears the value of the "content_hash" field.
func (u *TicketPullRequestUpsert) ClearContentHash() *TicketPullRequestUpsert {
	u.SetNull(ticketpullrequest.FieldContentHash)
	return u
}

// SetDeletionState sets the "deletion_state" field.
func (u *TicketPullRequestUpsert) SetDeletionState(v ticketpullrequest.DeletionState) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldDeletionState, v)
	return u
}

// UpdateDeletionState sets the "deletion_state" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateDeletionState() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldDeletionState)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TicketPullRequestUpsert) SetDeletedAt(v time.Time) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateDeletedAt() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TicketPullRequestUpsert) ClearDeletedAt() *TicketPullRequestUpsert {
	u.SetNull(ticketpullrequest.FieldDeletedAt)
	return u
}

// SetACLPolicyKey sets the "acl_policy_key" field.
func (u *TicketPullRequestUpsert) SetACLPolicyKey(v string) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldACLPolicyKey, v)
	return u
}

// UpdateACLPolicyKey sets the "acl_policy_key" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateACLPolicyKey() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldACLPolicyKey)
	return u
}

// ClearACLPolicyKey clears the value of the "acl_policy_key" field.
func (u *TicketPullRequestUpsert) ClearACLPolicyKey() *TicketPullRequestUpsert {
	u.SetNull(ticketpullrequest.FieldACLPolicyKey)
	return u
}

// SetVisibilityHash sets the "visibility_hash" field.
func (u *TicketPullRequestUpsert) SetVisibilityHash(v string) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldVisibilityHash, v)
	return u
}

// UpdateVisibilityHash sets the "visibility_hash" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateVisibilityHash() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldVisibilityHash)
	return u
}

// ClearVisibilityHash clears the value of the "visibility_hash" field.
func (u *TicketPullRequestUpsert) ClearVisibilityHash() *TicketPullRequestUpsert {
	u.SetNull(ticketpullrequest.FieldVisibilityHash)
	return u
}

// SetACLState sets the "acl_state" field.
func (u *TicketPullRequestUpsert) SetACLState(v ticketpullrequest.ACLState) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldACLState, v)
	return u
}

// UpdateACLState sets the "acl_state" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateACLState() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldACLState)
	return u
}

// SetACLCheckedAt sets the "acl_checked_at" field.
func (u *TicketPullRequestUpsert) SetACLCheckedAt(v time.Time) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldACLCheckedAt, v)
	return u
}

// UpdateACLCheckedAt sets the "acl_checked_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateACLCheckedAt() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldACLCheckedAt)
	return u
}

// ClearACLCheckedAt clears the value of the "acl_checked_at" field.
func (u *TicketPullRequestUpsert) ClearACLCheckedAt() *TicketPullRequestUpsert {
	u.SetNull(ticketpullrequest.FieldACLCheckedAt)
	return u
}

// SetFreshnessCheckedAt sets the "freshness_checked_at" field.
func (u *TicketPullRequestUpsert) SetFreshnessCheckedAt(v time.Time) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldFreshnessCheckedAt, v)
	return u
}

// UpdateFreshnessCheckedAt sets the "freshness_checked_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateFreshnessCheckedAt() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldFreshnessCheckedAt)
	return u
}

// ClearFreshnessCheckedAt clears the value of the "freshness_checked_at" field.
func (u *TicketPullRequestUpsert) ClearFreshnessCheckedAt() *TicketPullRequestUpsert {
	u.SetNull(ticketpullrequest.FieldFreshnessCheckedAt)
	return u
}

// SetSourceScopeStateID sets the "source_scope_state_id" field.
func (u *TicketPullRequestUpsert) SetSourceScopeStateID(v int) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldSourceScopeStateID, v)
	return u
}

// UpdateSourceScopeStateID sets the "source_scope_state_id" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateSourceScopeStateID() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldSourceScopeStateID)
	return u
}

// AddSourceScopeStateID adds v to the "source_scope_state_id" field.
func (u *TicketPullRequestUpsert) AddSourceScopeStateID(v int) *TicketPullRequestUpsert {
	u.Add(ticketpullrequest.FieldSourceScopeStateID, v)
	return u
}

// ClearSourceScopeStateID clears the value of the "source_scope_state_id" field.
func (u *TicketPullRequestUpsert) ClearSourceScopeStateID() *TicketPullRequestUpsert {
	u.SetNull(ticketpullrequest.FieldSourceScopeStateID)
	return u
}

// SetLastConfirmedAt sets the "last_confirmed_at" field.
func (u *TicketPullRequestUpsert) SetLastConfirmedAt(v time.Time) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldLastConfirmedAt, v)
	return u
}

// UpdateLastConfirmedAt sets the "last_confirmed_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateLastConfirmedAt() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldLastConfirmedAt)
	return u
}

// ClearLastConfirmedAt clears the value of the "last_confirmed_at" field.
func (u *TicketPullRequestUpsert) ClearLastConfirmedAt() *TicketPullRequestUpsert {
	u.SetNull(ticketpullrequest.FieldLastConfirmedAt)
	return u
}

// SetLastChangedAt sets the "last_changed_at" field.
func (u *TicketPullRequestUpsert) SetLastChangedAt(v time.Time) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldLastChangedAt, v)
	return u
}

// UpdateLastChangedAt sets the "last_changed_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateLastChangedAt() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldLastChangedAt)
	return u
}

// ClearLastChangedAt clears the value of the "last_changed_at" field.
func (u *TicketPullRequestUpsert) ClearLastChangedAt() *TicketPullRequestUpsert {
	u.SetNull(ticketpullrequest.FieldLastChangedAt)
	return u
}

// SetFreshnessState sets the "freshness_state" field.
func (u *TicketPullRequestUpsert) SetFreshnessState(v ticketpullrequest.FreshnessState) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldFreshnessState, v)
	return u
}

// UpdateFreshnessState sets the "freshness_state" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateFreshnessState() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldFreshnessState)
	return u
}

// SetVisibility sets the "visibility" field.
func (u *TicketPullRequestUpsert) SetVisibility(v ticketpullrequest.Visibility) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldVisibility, v)
	return u
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateVisibility() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldVisibility)
	return u
}

// SetConfidence sets the "confidence" field.
func (u *TicketPullRequestUpsert) SetConfidence(v float64) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldConfidence, v)
	return u
}

// UpdateConfidence sets the "confidence" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateConfidence() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldConfidence)
	return u
}

// AddConfidence adds v to the "confidence" field.
func (u *TicketPullRequestUpsert) AddConfidence(v float64) *TicketPullRequestUpsert {
	u.Add(ticketpullrequest.FieldConfidence, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TicketPullRequestUpsert) SetUpdatedAt(v time.Time) *TicketPullRequestUpsert {
	u.Set(ticketpullrequest.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsert) UpdateUpdatedAt() *TicketPullRequestUpsert {
	u.SetExcluded(ticketpullrequest.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TicketPullRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TicketPullRequestUpsertOne) UpdateNewValues() *TicketPullRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.TicketID(); exists {
			s.SetIgnore(ticketpullrequest.FieldTicketID)
		}
		if _, exists := u.create.mutation.PullRequestID(); exists {
			s.SetIgnore(ticketpullrequest.FieldPullRequestID)
		}
		if _, exists := u.create.mutation.TicketPullRequestKind(); exists {
			s.SetIgnore(ticketpullrequest.FieldTicketPullRequestKind)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ticketpullrequest.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TicketPullRequest.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TicketPullRequestUpsertOne) Ignore() *TicketPullRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketPullRequestUpsertOne) DoNothing() *TicketPullRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketPullRequestCreate.OnConflict
// documentation for more info.
func (u *TicketPullRequestUpsertOne) Update(set func(*TicketPullRequestUpsert)) *TicketPullRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketPullRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetLatestEvidenceID sets the "latest_evidence_id" field.
func (u *TicketPullRequestUpsertOne) SetLatestEvidenceID(v int) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetLatestEvidenceID(v)
	})
}

// UpdateLatestEvidenceID sets the "latest_evidence_id" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateLatestEvidenceID() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateLatestEvidenceID()
	})
}

// ClearLatestEvidenceID clears the value of the "latest_evidence_id" field.
func (u *TicketPullRequestUpsertOne) ClearLatestEvidenceID() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearLatestEvidenceID()
	})
}

// SetEvidenceCount sets the "evidence_count" field.
func (u *TicketPullRequestUpsertOne) SetEvidenceCount(v int) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetEvidenceCount(v)
	})
}

// AddEvidenceCount adds v to the "evidence_count" field.
func (u *TicketPullRequestUpsertOne) AddEvidenceCount(v int) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.AddEvidenceCount(v)
	})
}

// UpdateEvidenceCount sets the "evidence_count" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateEvidenceCount() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateEvidenceCount()
	})
}

// SetEventCount sets the "event_count" field.
func (u *TicketPullRequestUpsertOne) SetEventCount(v int) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetEventCount(v)
	})
}

// AddEventCount adds v to the "event_count" field.
func (u *TicketPullRequestUpsertOne) AddEventCount(v int) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.AddEventCount(v)
	})
}

// UpdateEventCount sets the "event_count" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateEventCount() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateEventCount()
	})
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (u *TicketPullRequestUpsertOne) SetFirstSeenAt(v time.Time) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetFirstSeenAt(v)
	})
}

// UpdateFirstSeenAt sets the "first_seen_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateFirstSeenAt() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateFirstSeenAt()
	})
}

// ClearFirstSeenAt clears the value of the "first_seen_at" field.
func (u *TicketPullRequestUpsertOne) ClearFirstSeenAt() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearFirstSeenAt()
	})
}

// SetLastActivityAt sets the "last_activity_at" field.
func (u *TicketPullRequestUpsertOne) SetLastActivityAt(v time.Time) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetLastActivityAt(v)
	})
}

// UpdateLastActivityAt sets the "last_activity_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateLastActivityAt() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateLastActivityAt()
	})
}

// ClearLastActivityAt clears the value of the "last_activity_at" field.
func (u *TicketPullRequestUpsertOne) ClearLastActivityAt() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearLastActivityAt()
	})
}

// SetRankScore sets the "rank_score" field.
func (u *TicketPullRequestUpsertOne) SetRankScore(v float64) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetRankScore(v)
	})
}

// AddRankScore adds v to the "rank_score" field.
func (u *TicketPullRequestUpsertOne) AddRankScore(v float64) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.AddRankScore(v)
	})
}

// UpdateRankScore sets the "rank_score" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateRankScore() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateRankScore()
	})
}

// SetSourceSystem sets the "source_system" field.
func (u *TicketPullRequestUpsertOne) SetSourceSystem(v string) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetSourceSystem(v)
	})
}

// UpdateSourceSystem sets the "source_system" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateSourceSystem() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateSourceSystem()
	})
}

// ClearSourceSystem clears the value of the "source_system" field.
func (u *TicketPullRequestUpsertOne) ClearSourceSystem() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearSourceSystem()
	})
}

// SetSourceInstance sets the "source_instance" field.
func (u *TicketPullRequestUpsertOne) SetSourceInstance(v string) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetSourceInstance(v)
	})
}

// UpdateSourceInstance sets the "source_instance" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateSourceInstance() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateSourceInstance()
	})
}

// ClearSourceInstance clears the value of the "source_instance" field.
func (u *TicketPullRequestUpsertOne) ClearSourceInstance() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearSourceInstance()
	})
}

// SetExternalKind sets the "external_kind" field.
func (u *TicketPullRequestUpsertOne) SetExternalKind(v string) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetExternalKind(v)
	})
}

// UpdateExternalKind sets the "external_kind" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateExternalKind() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateExternalKind()
	})
}

// ClearExternalKind clears the value of the "external_kind" field.
func (u *TicketPullRequestUpsertOne) ClearExternalKind() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearExternalKind()
	})
}

// SetExternalID sets the "external_id" field.
func (u *TicketPullRequestUpsertOne) SetExternalID(v string) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetExternalID(v)
	})
}

// UpdateExternalID sets the "external_id" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateExternalID() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateExternalID()
	})
}

// ClearExternalID clears the value of the "external_id" field.
func (u *TicketPullRequestUpsertOne) ClearExternalID() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearExternalID()
	})
}

// SetSourceURL sets the "source_url" field.
func (u *TicketPullRequestUpsertOne) SetSourceURL(v string) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetSourceURL(v)
	})
}

// UpdateSourceURL sets the "source_url" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateSourceURL() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateSourceURL()
	})
}

// ClearSourceURL clears the value of the "source_url" field.
func (u *TicketPullRequestUpsertOne) ClearSourceURL() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearSourceURL()
	})
}

// SetSourceVersion sets the "source_version" field.
func (u *TicketPullRequestUpsertOne) SetSourceVersion(v string) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetSourceVersion(v)
	})
}

// UpdateSourceVersion sets the "source_version" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateSourceVersion() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateSourceVersion()
	})
}

// ClearSourceVersion clears the value of the "source_version" field.
func (u *TicketPullRequestUpsertOne) ClearSourceVersion() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearSourceVersion()
	})
}

// SetSourceUpdatedAt sets the "source_updated_at" field.
func (u *TicketPullRequestUpsertOne) SetSourceUpdatedAt(v time.Time) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetSourceUpdatedAt(v)
	})
}

// UpdateSourceUpdatedAt sets the "source_updated_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateSourceUpdatedAt() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateSourceUpdatedAt()
	})
}

// ClearSourceUpdatedAt clears the value of the "source_updated_at" field.
func (u *TicketPullRequestUpsertOne) ClearSourceUpdatedAt() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearSourceUpdatedAt()
	})
}

// SetContentHash sets the "content_hash" field.
func (u *TicketPullRequestUpsertOne) SetContentHash(v string) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetContentHash(v)
	})
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateContentHash() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateContentHash()
	})
}

// ClearContentHash clears the value of the "content_hash" field.
func (u *TicketPullRequestUpsertOne) ClearContentHash() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearContentHash()
	})
}

// SetDeletionState sets the "deletion_state" field.
func (u *TicketPullRequestUpsertOne) SetDeletionState(v ticketpullrequest.DeletionState) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetDeletionState(v)
	})
}

// UpdateDeletionState sets the "deletion_state" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateDeletionState() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateDeletionState()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TicketPullRequestUpsertOne) SetDeletedAt(v time.Time) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateDeletedAt() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TicketPullRequestUpsertOne) ClearDeletedAt() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearDeletedAt()
	})
}

// SetACLPolicyKey sets the "acl_policy_key" field.
func (u *TicketPullRequestUpsertOne) SetACLPolicyKey(v string) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetACLPolicyKey(v)
	})
}

// UpdateACLPolicyKey sets the "acl_policy_key" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateACLPolicyKey() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateACLPolicyKey()
	})
}

// ClearACLPolicyKey clears the value of the "acl_policy_key" field.
func (u *TicketPullRequestUpsertOne) ClearACLPolicyKey() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearACLPolicyKey()
	})
}

// SetVisibilityHash sets the "visibility_hash" field.
func (u *TicketPullRequestUpsertOne) SetVisibilityHash(v string) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetVisibilityHash(v)
	})
}

// UpdateVisibilityHash sets the "visibility_hash" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateVisibilityHash() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateVisibilityHash()
	})
}

// ClearVisibilityHash clears the value of the "visibility_hash" field.
func (u *TicketPullRequestUpsertOne) ClearVisibilityHash() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearVisibilityHash()
	})
}

// SetACLState sets the "acl_state" field.
func (u *TicketPullRequestUpsertOne) SetACLState(v ticketpullrequest.ACLState) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetACLState(v)
	})
}

// UpdateACLState sets the "acl_state" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateACLState() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateACLState()
	})
}

// SetACLCheckedAt sets the "acl_checked_at" field.
func (u *TicketPullRequestUpsertOne) SetACLCheckedAt(v time.Time) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetACLCheckedAt(v)
	})
}

// UpdateACLCheckedAt sets the "acl_checked_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateACLCheckedAt() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateACLCheckedAt()
	})
}

// ClearACLCheckedAt clears the value of the "acl_checked_at" field.
func (u *TicketPullRequestUpsertOne) ClearACLCheckedAt() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearACLCheckedAt()
	})
}

// SetFreshnessCheckedAt sets the "freshness_checked_at" field.
func (u *TicketPullRequestUpsertOne) SetFreshnessCheckedAt(v time.Time) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetFreshnessCheckedAt(v)
	})
}

// UpdateFreshnessCheckedAt sets the "freshness_checked_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateFreshnessCheckedAt() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateFreshnessCheckedAt()
	})
}

// ClearFreshnessCheckedAt clears the value of the "freshness_checked_at" field.
func (u *TicketPullRequestUpsertOne) ClearFreshnessCheckedAt() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearFreshnessCheckedAt()
	})
}

// SetSourceScopeStateID sets the "source_scope_state_id" field.
func (u *TicketPullRequestUpsertOne) SetSourceScopeStateID(v int) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetSourceScopeStateID(v)
	})
}

// AddSourceScopeStateID adds v to the "source_scope_state_id" field.
func (u *TicketPullRequestUpsertOne) AddSourceScopeStateID(v int) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.AddSourceScopeStateID(v)
	})
}

// UpdateSourceScopeStateID sets the "source_scope_state_id" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateSourceScopeStateID() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateSourceScopeStateID()
	})
}

// ClearSourceScopeStateID clears the value of the "source_scope_state_id" field.
func (u *TicketPullRequestUpsertOne) ClearSourceScopeStateID() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearSourceScopeStateID()
	})
}

// SetLastConfirmedAt sets the "last_confirmed_at" field.
func (u *TicketPullRequestUpsertOne) SetLastConfirmedAt(v time.Time) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetLastConfirmedAt(v)
	})
}

// UpdateLastConfirmedAt sets the "last_confirmed_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateLastConfirmedAt() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateLastConfirmedAt()
	})
}

// ClearLastConfirmedAt clears the value of the "last_confirmed_at" field.
func (u *TicketPullRequestUpsertOne) ClearLastConfirmedAt() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearLastConfirmedAt()
	})
}

// SetLastChangedAt sets the "last_changed_at" field.
func (u *TicketPullRequestUpsertOne) SetLastChangedAt(v time.Time) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetLastChangedAt(v)
	})
}

// UpdateLastChangedAt sets the "last_changed_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateLastChangedAt() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateLastChangedAt()
	})
}

// ClearLastChangedAt clears the value of the "last_changed_at" field.
func (u *TicketPullRequestUpsertOne) ClearLastChangedAt() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearLastChangedAt()
	})
}

// SetFreshnessState sets the "freshness_state" field.
func (u *TicketPullRequestUpsertOne) SetFreshnessState(v ticketpullrequest.FreshnessState) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetFreshnessState(v)
	})
}

// UpdateFreshnessState sets the "freshness_state" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateFreshnessState() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateFreshnessState()
	})
}

// SetVisibility sets the "visibility" field.
func (u *TicketPullRequestUpsertOne) SetVisibility(v ticketpullrequest.Visibility) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetVisibility(v)
	})
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateVisibility() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateVisibility()
	})
}

// SetConfidence sets the "confidence" field.
func (u *TicketPullRequestUpsertOne) SetConfidence(v float64) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetConfidence(v)
	})
}

// AddConfidence adds v to the "confidence" field.
func (u *TicketPullRequestUpsertOne) AddConfidence(v float64) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.AddConfidence(v)
	})
}

// UpdateConfidence sets the "confidence" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateConfidence() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateConfidence()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TicketPullRequestUpsertOne) SetUpdatedAt(v time.Time) *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsertOne) UpdateUpdatedAt() *TicketPullRequestUpsertOne {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TicketPullRequestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketPullRequestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketPullRequestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TicketPullRequestUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TicketPullRequestUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TicketPullRequestCreateBulk is the builder for creating many TicketPullRequest entities in bulk.
type TicketPullRequestCreateBulk struct {
	config
	err      error
	builders []*TicketPullRequestCreate
	conflict []sql.ConflictOption
}

// Save creates the TicketPullRequest entities in the database.
func (_c *TicketPullRequestCreateBulk) Save(ctx context.Context) ([]*TicketPullRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TicketPullRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TicketPullRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TicketPullRequestCreateBulk) SaveX(ctx context.Context) []*TicketPullRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketPullRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketPullRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TicketPullRequest.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketPullRequestUpsert) {
//			SetTicketID(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketPullRequestCreateBulk) OnConflict(opts ...sql.ConflictOption) *TicketPullRequestUpsertBulk {
	_c.conflict = opts
	return &TicketPullRequestUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TicketPullRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketPullRequestCreateBulk) OnConflictColumns(columns ...string) *TicketPullRequestUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketPullRequestUpsertBulk{
		create: _c,
	}
}

// TicketPullRequestUpsertBulk is the builder for "upsert"-ing
// a bulk of TicketPullRequest nodes.
type TicketPullRequestUpsertBulk struct {
	create *TicketPullRequestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TicketPullRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TicketPullRequestUpsertBulk) UpdateNewValues() *TicketPullRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.TicketID(); exists {
				s.SetIgnore(ticketpullrequest.FieldTicketID)
			}
			if _, exists := b.mutation.PullRequestID(); exists {
				s.SetIgnore(ticketpullrequest.FieldPullRequestID)
			}
			if _, exists := b.mutation.TicketPullRequestKind(); exists {
				s.SetIgnore(ticketpullrequest.FieldTicketPullRequestKind)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ticketpullrequest.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TicketPullRequest.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TicketPullRequestUpsertBulk) Ignore() *TicketPullRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketPullRequestUpsertBulk) DoNothing() *TicketPullRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketPullRequestCreateBulk.OnConflict
// documentation for more info.
func (u *TicketPullRequestUpsertBulk) Update(set func(*TicketPullRequestUpsert)) *TicketPullRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketPullRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetLatestEvidenceID sets the "latest_evidence_id" field.
func (u *TicketPullRequestUpsertBulk) SetLatestEvidenceID(v int) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetLatestEvidenceID(v)
	})
}

// UpdateLatestEvidenceID sets the "latest_evidence_id" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateLatestEvidenceID() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateLatestEvidenceID()
	})
}

// ClearLatestEvidenceID clears the value of the "latest_evidence_id" field.
func (u *TicketPullRequestUpsertBulk) ClearLatestEvidenceID() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearLatestEvidenceID()
	})
}

// SetEvidenceCount sets the "evidence_count" field.
func (u *TicketPullRequestUpsertBulk) SetEvidenceCount(v int) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetEvidenceCount(v)
	})
}

// AddEvidenceCount adds v to the "evidence_count" field.
func (u *TicketPullRequestUpsertBulk) AddEvidenceCount(v int) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.AddEvidenceCount(v)
	})
}

// UpdateEvidenceCount sets the "evidence_count" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateEvidenceCount() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateEvidenceCount()
	})
}

// SetEventCount sets the "event_count" field.
func (u *TicketPullRequestUpsertBulk) SetEventCount(v int) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetEventCount(v)
	})
}

// AddEventCount adds v to the "event_count" field.
func (u *TicketPullRequestUpsertBulk) AddEventCount(v int) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.AddEventCount(v)
	})
}

// UpdateEventCount sets the "event_count" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateEventCount() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateEventCount()
	})
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (u *TicketPullRequestUpsertBulk) SetFirstSeenAt(v time.Time) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetFirstSeenAt(v)
	})
}

// UpdateFirstSeenAt sets the "first_seen_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateFirstSeenAt() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateFirstSeenAt()
	})
}

// ClearFirstSeenAt clears the value of the "first_seen_at" field.
func (u *TicketPullRequestUpsertBulk) ClearFirstSeenAt() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearFirstSeenAt()
	})
}

// SetLastActivityAt sets the "last_activity_at" field.
func (u *TicketPullRequestUpsertBulk) SetLastActivityAt(v time.Time) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetLastActivityAt(v)
	})
}

// UpdateLastActivityAt sets the "last_activity_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateLastActivityAt() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateLastActivityAt()
	})
}

// ClearLastActivityAt clears the value of the "last_activity_at" field.
func (u *TicketPullRequestUpsertBulk) ClearLastActivityAt() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearLastActivityAt()
	})
}

// SetRankScore sets the "rank_score" field.
func (u *TicketPullRequestUpsertBulk) SetRankScore(v float64) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetRankScore(v)
	})
}

// AddRankScore adds v to the "rank_score" field.
func (u *TicketPullRequestUpsertBulk) AddRankScore(v float64) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.AddRankScore(v)
	})
}

// UpdateRankScore sets the "rank_score" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateRankScore() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateRankScore()
	})
}

// SetSourceSystem sets the "source_system" field.
func (u *TicketPullRequestUpsertBulk) SetSourceSystem(v string) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetSourceSystem(v)
	})
}

// UpdateSourceSystem sets the "source_system" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateSourceSystem() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateSourceSystem()
	})
}

// ClearSourceSystem clears the value of the "source_system" field.
func (u *TicketPullRequestUpsertBulk) ClearSourceSystem() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearSourceSystem()
	})
}

// SetSourceInstance sets the "source_instance" field.
func (u *TicketPullRequestUpsertBulk) SetSourceInstance(v string) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetSourceInstance(v)
	})
}

// UpdateSourceInstance sets the "source_instance" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateSourceInstance() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateSourceInstance()
	})
}

// ClearSourceInstance clears the value of the "source_instance" field.
func (u *TicketPullRequestUpsertBulk) ClearSourceInstance() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearSourceInstance()
	})
}

// SetExternalKind sets the "external_kind" field.
func (u *TicketPullRequestUpsertBulk) SetExternalKind(v string) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetExternalKind(v)
	})
}

// UpdateExternalKind sets the "external_kind" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateExternalKind() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateExternalKind()
	})
}

// ClearExternalKind clears the value of the "external_kind" field.
func (u *TicketPullRequestUpsertBulk) ClearExternalKind() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearExternalKind()
	})
}

// SetExternalID sets the "external_id" field.
func (u *TicketPullRequestUpsertBulk) SetExternalID(v string) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetExternalID(v)
	})
}

// UpdateExternalID sets the "external_id" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateExternalID() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateExternalID()
	})
}

// ClearExternalID clears the value of the "external_id" field.
func (u *TicketPullRequestUpsertBulk) ClearExternalID() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearExternalID()
	})
}

// SetSourceURL sets the "source_url" field.
func (u *TicketPullRequestUpsertBulk) SetSourceURL(v string) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetSourceURL(v)
	})
}

// UpdateSourceURL sets the "source_url" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateSourceURL() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateSourceURL()
	})
}

// ClearSourceURL clears the value of the "source_url" field.
func (u *TicketPullRequestUpsertBulk) ClearSourceURL() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearSourceURL()
	})
}

// SetSourceVersion sets the "source_version" field.
func (u *TicketPullRequestUpsertBulk) SetSourceVersion(v string) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetSourceVersion(v)
	})
}

// UpdateSourceVersion sets the "source_version" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateSourceVersion() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateSourceVersion()
	})
}

// ClearSourceVersion clears the value of the "source_version" field.
func (u *TicketPullRequestUpsertBulk) ClearSourceVersion() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearSourceVersion()
	})
}

// SetSourceUpdatedAt sets the "source_updated_at" field.
func (u *TicketPullRequestUpsertBulk) SetSourceUpdatedAt(v time.Time) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetSourceUpdatedAt(v)
	})
}

// UpdateSourceUpdatedAt sets the "source_updated_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateSourceUpdatedAt() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateSourceUpdatedAt()
	})
}

// ClearSourceUpdatedAt clears the value of the "source_updated_at" field.
func (u *TicketPullRequestUpsertBulk) ClearSourceUpdatedAt() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearSourceUpdatedAt()
	})
}

// SetContentHash sets the "content_hash" field.
func (u *TicketPullRequestUpsertBulk) SetContentHash(v string) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetContentHash(v)
	})
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateContentHash() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateContentHash()
	})
}

// ClearContentHash clears the value of the "content_hash" field.
func (u *TicketPullRequestUpsertBulk) ClearContentHash() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearContentHash()
	})
}

// SetDeletionState sets the "deletion_state" field.
func (u *TicketPullRequestUpsertBulk) SetDeletionState(v ticketpullrequest.DeletionState) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetDeletionState(v)
	})
}

// UpdateDeletionState sets the "deletion_state" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateDeletionState() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateDeletionState()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TicketPullRequestUpsertBulk) SetDeletedAt(v time.Time) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateDeletedAt() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TicketPullRequestUpsertBulk) ClearDeletedAt() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearDeletedAt()
	})
}

// SetACLPolicyKey sets the "acl_policy_key" field.
func (u *TicketPullRequestUpsertBulk) SetACLPolicyKey(v string) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetACLPolicyKey(v)
	})
}

// UpdateACLPolicyKey sets the "acl_policy_key" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateACLPolicyKey() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateACLPolicyKey()
	})
}

// ClearACLPolicyKey clears the value of the "acl_policy_key" field.
func (u *TicketPullRequestUpsertBulk) ClearACLPolicyKey() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearACLPolicyKey()
	})
}

// SetVisibilityHash sets the "visibility_hash" field.
func (u *TicketPullRequestUpsertBulk) SetVisibilityHash(v string) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetVisibilityHash(v)
	})
}

// UpdateVisibilityHash sets the "visibility_hash" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateVisibilityHash() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateVisibilityHash()
	})
}

// ClearVisibilityHash clears the value of the "visibility_hash" field.
func (u *TicketPullRequestUpsertBulk) ClearVisibilityHash() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearVisibilityHash()
	})
}

// SetACLState sets the "acl_state" field.
func (u *TicketPullRequestUpsertBulk) SetACLState(v ticketpullrequest.ACLState) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetACLState(v)
	})
}

// UpdateACLState sets the "acl_state" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateACLState() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateACLState()
	})
}

// SetACLCheckedAt sets the "acl_checked_at" field.
func (u *TicketPullRequestUpsertBulk) SetACLCheckedAt(v time.Time) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetACLCheckedAt(v)
	})
}

// UpdateACLCheckedAt sets the "acl_checked_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateACLCheckedAt() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateACLCheckedAt()
	})
}

// ClearACLCheckedAt clears the value of the "acl_checked_at" field.
func (u *TicketPullRequestUpsertBulk) ClearACLCheckedAt() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearACLCheckedAt()
	})
}

// SetFreshnessCheckedAt sets the "freshness_checked_at" field.
func (u *TicketPullRequestUpsertBulk) SetFreshnessCheckedAt(v time.Time) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetFreshnessCheckedAt(v)
	})
}

// UpdateFreshnessCheckedAt sets the "freshness_checked_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateFreshnessCheckedAt() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateFreshnessCheckedAt()
	})
}

// ClearFreshnessCheckedAt clears the value of the "freshness_checked_at" field.
func (u *TicketPullRequestUpsertBulk) ClearFreshnessCheckedAt() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearFreshnessCheckedAt()
	})
}

// SetSourceScopeStateID sets the "source_scope_state_id" field.
func (u *TicketPullRequestUpsertBulk) SetSourceScopeStateID(v int) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetSourceScopeStateID(v)
	})
}

// AddSourceScopeStateID adds v to the "source_scope_state_id" field.
func (u *TicketPullRequestUpsertBulk) AddSourceScopeStateID(v int) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.AddSourceScopeStateID(v)
	})
}

// UpdateSourceScopeStateID sets the "source_scope_state_id" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateSourceScopeStateID() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateSourceScopeStateID()
	})
}

// ClearSourceScopeStateID clears the value of the "source_scope_state_id" field.
func (u *TicketPullRequestUpsertBulk) ClearSourceScopeStateID() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearSourceScopeStateID()
	})
}

// SetLastConfirmedAt sets the "last_confirmed_at" field.
func (u *TicketPullRequestUpsertBulk) SetLastConfirmedAt(v time.Time) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetLastConfirmedAt(v)
	})
}

// UpdateLastConfirmedAt sets the "last_confirmed_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateLastConfirmedAt() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateLastConfirmedAt()
	})
}

// ClearLastConfirmedAt clears the value of the "last_confirmed_at" field.
func (u *TicketPullRequestUpsertBulk) ClearLastConfirmedAt() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearLastConfirmedAt()
	})
}

// SetLastChangedAt sets the "last_changed_at" field.
func (u *TicketPullRequestUpsertBulk) SetLastChangedAt(v time.Time) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetLastChangedAt(v)
	})
}

// UpdateLastChangedAt sets the "last_changed_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateLastChangedAt() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateLastChangedAt()
	})
}

// ClearLastChangedAt clears the value of the "last_changed_at" field.
func (u *TicketPullRequestUpsertBulk) ClearLastChangedAt() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.ClearLastChangedAt()
	})
}

// SetFreshnessState sets the "freshness_state" field.
func (u *TicketPullRequestUpsertBulk) SetFreshnessState(v ticketpullrequest.FreshnessState) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetFreshnessState(v)
	})
}

// UpdateFreshnessState sets the "freshness_state" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateFreshnessState() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateFreshnessState()
	})
}

// SetVisibility sets the "visibility" field.
func (u *TicketPullRequestUpsertBulk) SetVisibility(v ticketpullrequest.Visibility) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetVisibility(v)
	})
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateVisibility() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateVisibility()
	})
}

// SetConfidence sets the "confidence" field.
func (u *TicketPullRequestUpsertBulk) SetConfidence(v float64) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetConfidence(v)
	})
}

// AddConfidence adds v to the "confidence" field.
func (u *TicketPullRequestUpsertBulk) AddConfidence(v float64) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.AddConfidence(v)
	})
}

// UpdateConfidence sets the "confidence" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateConfidence() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateConfidence()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TicketPullRequestUpsertBulk) SetUpdatedAt(v time.Time) *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TicketPullRequestUpsertBulk) UpdateUpdatedAt() *TicketPullRequestUpsertBulk {
	return u.Update(func(s *TicketPullRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TicketPullRequestUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TicketPullRequestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketPullRequestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketPullRequestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
