// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cubicle/services/ontology-service/ent/predicate"
	"cubicle/services/ontology-service/ent/workprogramrun"
	"cubicle/services/ontology-service/ent/workprogramrunmember"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkProgramRunMemberUpdate is the builder for updating WorkProgramRunMember entities.
type WorkProgramRunMemberUpdate struct {
	config
	hooks    []Hook
	mutation *WorkProgramRunMemberMutation
}

// Where appends a list predicates to the WorkProgramRunMemberUpdate builder.
func (_u *WorkProgramRunMemberUpdate) Where(ps ...predicate.WorkProgramRunMember) *WorkProgramRunMemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetWorkProgramRunID sets the "work_program_run_id" field.
func (_u *WorkProgramRunMemberUpdate) SetWorkProgramRunID(v int) *WorkProgramRunMemberUpdate {
	_u.mutation.SetWorkProgramRunID(v)
	return _u
}

// SetNillableWorkProgramRunID sets the "work_program_run_id" field if the given value is not nil.
func (_u *WorkProgramRunMemberUpdate) SetNillableWorkProgramRunID(v *int) *WorkProgramRunMemberUpdate {
	if v != nil {
		_u.SetWorkProgramRunID(*v)
	}
	return _u
}

// ClearWorkProgramRunID clears the value of the "work_program_run_id" field.
func (_u *WorkProgramRunMemberUpdate) ClearWorkProgramRunID() *WorkProgramRunMemberUpdate {
	_u.mutation.ClearWorkProgramRunID()
	return _u
}

// SetRunKey sets the "run_key" field.
func (_u *WorkProgramRunMemberUpdate) SetRunKey(v string) *WorkProgramRunMemberUpdate {
	_u.mutation.SetRunKey(v)
	return _u
}

// SetNillableRunKey sets the "run_key" field if the given value is not nil.
func (_u *WorkProgramRunMemberUpdate) SetNillableRunKey(v *string) *WorkProgramRunMemberUpdate {
	if v != nil {
		_u.SetRunKey(*v)
	}
	return _u
}

// SetMemberTable sets the "member_table" field.
func (_u *WorkProgramRunMemberUpdate) SetMemberTable(v string) *WorkProgramRunMemberUpdate {
	_u.mutation.SetMemberTable(v)
	return _u
}

// SetNillableMemberTable sets the "member_table" field if the given value is not nil.
func (_u *WorkProgramRunMemberUpdate) SetNillableMemberTable(v *string) *WorkProgramRunMemberUpdate {
	if v != nil {
		_u.SetMemberTable(*v)
	}
	return _u
}

// SetMemberID sets the "member_id" field.
func (_u *WorkProgramRunMemberUpdate) SetMemberID(v int) *WorkProgramRunMemberUpdate {
	_u.mutation.ResetMemberID()
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *WorkProgramRunMemberUpdate) SetNillableMemberID(v *int) *WorkProgramRunMemberUpdate {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// AddMemberID adds value to the "member_id" field.
func (_u *WorkProgramRunMemberUpdate) AddMemberID(v int) *WorkProgramRunMemberUpdate {
	_u.mutation.AddMemberID(v)
	return _u
}

// SetMemberKey sets the "member_key" field.
func (_u *WorkProgramRunMemberUpdate) SetMemberKey(v string) *WorkProgramRunMemberUpdate {
	_u.mutation.SetMemberKey(v)
	return _u
}

// SetNillableMemberKey sets the "member_key" field if the given value is not nil.
func (_u *WorkProgramRunMemberUpdate) SetNillableMemberKey(v *string) *WorkProgramRunMemberUpdate {
	if v != nil {
		_u.SetMemberKey(*v)
	}
	return _u
}

// ClearMemberKey clears the value of the "member_key" field.
func (_u *WorkProgramRunMemberUpdate) ClearMemberKey() *WorkProgramRunMemberUpdate {
	_u.mutation.ClearMemberKey()
	return _u
}

// SetMemberExternalKind sets the "member_external_kind" field.
func (_u *WorkProgramRunMemberUpdate) SetMemberExternalKind(v string) *WorkProgramRunMemberUpdate {
	_u.mutation.SetMemberExternalKind(v)
	return _u
}

// SetNillableMemberExternalKind sets the "member_external_kind" field if the given value is not nil.
func (_u *WorkProgramRunMemberUpdate) SetNillableMemberExternalKind(v *string) *WorkProgramRunMemberUpdate {
	if v != nil {
		_u.SetMemberExternalKind(*v)
	}
	return _u
}

// ClearMemberExternalKind clears the value of the "member_external_kind" field.
func (_u *WorkProgramRunMemberUpdate) ClearMemberExternalKind() *WorkProgramRunMemberUpdate {
	_u.mutation.ClearMemberExternalKind()
	return _u
}

// SetMemberExternalID sets the "member_external_id" field.
func (_u *WorkProgramRunMemberUpdate) SetMemberExternalID(v string) *WorkProgramRunMemberUpdate {
	_u.mutation.SetMemberExternalID(v)
	return _u
}

// SetNillableMemberExternalID sets the "member_external_id" field if the given value is not nil.
func (_u *WorkProgramRunMemberUpdate) SetNillableMemberExternalID(v *string) *WorkProgramRunMemberUpdate {
	if v != nil {
		_u.SetMemberExternalID(*v)
	}
	return _u
}

// ClearMemberExternalID clears the value of the "member_external_id" field.
func (_u *WorkProgramRunMemberUpdate) ClearMemberExternalID() *WorkProgramRunMemberUpdate {
	_u.mutation.ClearMemberExternalID()
	return _u
}

// SetMemberRankScore sets the "member_rank_score" field.
func (_u *WorkProgramRunMemberUpdate) SetMemberRankScore(v float64) *WorkProgramRunMemberUpdate {
	_u.mutation.ResetMemberRankScore()
	_u.mutation.SetMemberRankScore(v)
	return _u
}

// SetNillableMemberRankScore sets the "member_rank_score" field if the given value is not nil.
func (_u *WorkProgramRunMemberUpdate) SetNillableMemberRankScore(v *float64) *WorkProgramRunMemberUpdate {
	if v != nil {
		_u.SetMemberRankScore(*v)
	}
	return _u
}

// AddMemberRankScore adds value to the "member_rank_score" field.
func (_u *WorkProgramRunMemberUpdate) AddMemberRankScore(v float64) *WorkProgramRunMemberUpdate {
	_u.mutation.AddMemberRankScore(v)
	return _u
}

// ClearMemberRankScore clears the value of the "member_rank_score" field.
func (_u *WorkProgramRunMemberUpdate) ClearMemberRankScore() *WorkProgramRunMemberUpdate {
	_u.mutation.ClearMemberRankScore()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *WorkProgramRunMemberUpdate) SetCreatedAt(v time.Time) *WorkProgramRunMemberUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *WorkProgramRunMemberUpdate) SetNillableCreatedAt(v *time.Time) *WorkProgramRunMemberUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetWorkProgramRun sets the "work_program_run" edge to the WorkProgramRun entity.
func (_u *WorkProgramRunMemberUpdate) SetWorkProgramRun(v *WorkProgramRun) *WorkProgramRunMemberUpdate {
	return _u.SetWorkProgramRunID(v.ID)
}

// Mutation returns the WorkProgramRunMemberMutation object of the builder.
func (_u *WorkProgramRunMemberUpdate) Mutation() *WorkProgramRunMemberMutation {
	return _u.mutation
}

// ClearWorkProgramRun clears the "work_program_run" edge to the WorkProgramRun entity.
func (_u *WorkProgramRunMemberUpdate) ClearWorkProgramRun() *WorkProgramRunMemberUpdate {
	_u.mutation.ClearWorkProgramRun()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkProgramRunMemberUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkProgramRunMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkProgramRunMemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkProgramRunMemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkProgramRunMemberUpdate) check() error {
	if v, ok := _u.mutation.RunKey(); ok {
		if err := workprogramrunmember.RunKeyValidator(v); err != nil {
			return &ValidationError{Name: "run_key", err: fmt.Errorf(`ent: validator failed for field "WorkProgramRunMember.run_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MemberTable(); ok {
		if err := workprogramrunmember.MemberTableValidator(v); err != nil {
			return &ValidationError{Name: "member_table", err: fmt.Errorf(`ent: validator failed for field "WorkProgramRunMember.member_table": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkProgramRunMemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workprogramrunmember.Table, workprogramrunmember.Columns, sqlgraph.NewFieldSpec(workprogramrunmember.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RunKey(); ok {
		_spec.SetField(workprogramrunmember.FieldRunKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.MemberTable(); ok {
		_spec.SetField(workprogramrunmember.FieldMemberTable, field.TypeString, value)
	}
	if value, ok := _u.mutation.MemberID(); ok {
		_spec.SetField(workprogramrunmember.FieldMemberID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMemberID(); ok {
		_spec.AddField(workprogramrunmember.FieldMemberID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MemberKey(); ok {
		_spec.SetField(workprogramrunmember.FieldMemberKey, field.TypeString, value)
	}
	if _u.mutation.MemberKeyCleared() {
		_spec.ClearField(workprogramrunmember.FieldMemberKey, field.TypeString)
	}
	if value, ok := _u.mutation.MemberExternalKind(); ok {
		_spec.SetField(workprogramrunmember.FieldMemberExternalKind, field.TypeString, value)
	}
	if _u.mutation.MemberExternalKindCleared() {
		_spec.ClearField(workprogramrunmember.FieldMemberExternalKind, field.TypeString)
	}
	if value, ok := _u.mutation.MemberExternalID(); ok {
		_spec.SetField(workprogramrunmember.FieldMemberExternalID, field.TypeString, value)
	}
	if _u.mutation.MemberExternalIDCleared() {
		_spec.ClearField(workprogramrunmember.FieldMemberExternalID, field.TypeString)
	}
	if value, ok := _u.mutation.MemberRankScore(); ok {
		_spec.SetField(workprogramrunmember.FieldMemberRankScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMemberRankScore(); ok {
		_spec.AddField(workprogramrunmember.FieldMemberRankScore, field.TypeFloat64, value)
	}
	if _u.mutation.MemberRankScoreCleared() {
		_spec.ClearField(workprogramrunmember.FieldMemberRankScore, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(workprogramrunmember.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.WorkProgramRunCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workprogramrunmember.WorkProgramRunTable,
			Columns: []string{workprogramrunmember.WorkProgramRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workprogramrun.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkProgramRunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workprogramrunmember.WorkProgramRunTable,
			Columns: []string{workprogramrunmember.WorkProgramRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workprogramrun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workprogramrunmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkProgramRunMemberUpdateOne is the builder for updating a single WorkProgramRunMember entity.
type WorkProgramRunMemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkProgramRunMemberMutation
}

// SetWorkProgramRunID sets the "work_program_run_id" field.
func (_u *WorkProgramRunMemberUpdateOne) SetWorkProgramRunID(v int) *WorkProgramRunMemberUpdateOne {
	_u.mutation.SetWorkProgramRunID(v)
	return _u
}

// SetNillableWorkProgramRunID sets the "work_program_run_id" field if the given value is not nil.
func (_u *WorkProgramRunMemberUpdateOne) SetNillableWorkProgramRunID(v *int) *WorkProgramRunMemberUpdateOne {
	if v != nil {
		_u.SetWorkProgramRunID(*v)
	}
	return _u
}

// ClearWorkProgramRunID clears the value of the "work_program_run_id" field.
func (_u *WorkProgramRunMemberUpdateOne) ClearWorkProgramRunID() *WorkProgramRunMemberUpdateOne {
	_u.mutation.ClearWorkProgramRunID()
	return _u
}

// SetRunKey sets the "run_key" field.
func (_u *WorkProgramRunMemberUpdateOne) SetRunKey(v string) *WorkProgramRunMemberUpdateOne {
	_u.mutation.SetRunKey(v)
	return _u
}

// SetNillableRunKey sets the "run_key" field if the given value is not nil.
func (_u *WorkProgramRunMemberUpdateOne) SetNillableRunKey(v *string) *WorkProgramRunMemberUpdateOne {
	if v != nil {
		_u.SetRunKey(*v)
	}
	return _u
}

// SetMemberTable sets the "member_table" field.
func (_u *WorkProgramRunMemberUpdateOne) SetMemberTable(v string) *WorkProgramRunMemberUpdateOne {
	_u.mutation.SetMemberTable(v)
	return _u
}

// SetNillableMemberTable sets the "member_table" field if the given value is not nil.
func (_u *WorkProgramRunMemberUpdateOne) SetNillableMemberTable(v *string) *WorkProgramRunMemberUpdateOne {
	if v != nil {
		_u.SetMemberTable(*v)
	}
	return _u
}

// SetMemberID sets the "member_id" field.
func (_u *WorkProgramRunMemberUpdateOne) SetMemberID(v int) *WorkProgramRunMemberUpdateOne {
	_u.mutation.ResetMemberID()
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *WorkProgramRunMemberUpdateOne) SetNillableMemberID(v *int) *WorkProgramRunMemberUpdateOne {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// AddMemberID adds value to the "member_id" field.
func (_u *WorkProgramRunMemberUpdateOne) AddMemberID(v int) *WorkProgramRunMemberUpdateOne {
	_u.mutation.AddMemberID(v)
	return _u
}

// SetMemberKey sets the "member_key" field.
func (_u *WorkProgramRunMemberUpdateOne) SetMemberKey(v string) *WorkProgramRunMemberUpdateOne {
	_u.mutation.SetMemberKey(v)
	return _u
}

// SetNillableMemberKey sets the "member_key" field if the given value is not nil.
func (_u *WorkProgramRunMemberUpdateOne) SetNillableMemberKey(v *string) *WorkProgramRunMemberUpdateOne {
	if v != nil {
		_u.SetMemberKey(*v)
	}
	return _u
}

// ClearMemberKey clears the value of the "member_key" field.
func (_u *WorkProgramRunMemberUpdateOne) ClearMemberKey() *WorkProgramRunMemberUpdateOne {
	_u.mutation.ClearMemberKey()
	return _u
}

// SetMemberExternalKind sets the "member_external_kind" field.
func (_u *WorkProgramRunMemberUpdateOne) SetMemberExternalKind(v string) *WorkProgramRunMemberUpdateOne {
	_u.mutation.SetMemberExternalKind(v)
	return _u
}

// SetNillableMemberExternalKind sets the "member_external_kind" field if the given value is not nil.
func (_u *WorkProgramRunMemberUpdateOne) SetNillableMemberExternalKind(v *string) *WorkProgramRunMemberUpdateOne {
	if v != nil {
		_u.SetMemberExternalKind(*v)
	}
	return _u
}

// ClearMemberExternalKind clears the value of the "member_external_kind" field.
func (_u *WorkProgramRunMemberUpdateOne) ClearMemberExternalKind() *WorkProgramRunMemberUpdateOne {
	_u.mutation.ClearMemberExternalKind()
	return _u
}

// SetMemberExternalID sets the "member_external_id" field.
func (_u *WorkProgramRunMemberUpdateOne) SetMemberExternalID(v string) *WorkProgramRunMemberUpdateOne {
	_u.mutation.SetMemberExternalID(v)
	return _u
}

// SetNillableMemberExternalID sets the "member_external_id" field if the given value is not nil.
func (_u *WorkProgramRunMemberUpdateOne) SetNillableMemberExternalID(v *string) *WorkProgramRunMemberUpdateOne {
	if v != nil {
		_u.SetMemberExternalID(*v)
	}
	return _u
}

// ClearMemberExternalID clears the value of the "member_external_id" field.
func (_u *WorkProgramRunMemberUpdateOne) ClearMemberExternalID() *WorkProgramRunMemberUpdateOne {
	_u.mutation.ClearMemberExternalID()
	return _u
}

// SetMemberRankScore sets the "member_rank_score" field.
func (_u *WorkProgramRunMemberUpdateOne) SetMemberRankScore(v float64) *WorkProgramRunMemberUpdateOne {
	_u.mutation.ResetMemberRankScore()
	_u.mutation.SetMemberRankScore(v)
	return _u
}

// SetNillableMemberRankScore sets the "member_rank_score" field if the given value is not nil.
func (_u *WorkProgramRunMemberUpdateOne) SetNillableMemberRankScore(v *float64) *WorkProgramRunMemberUpdateOne {
	if v != nil {
		_u.SetMemberRankScore(*v)
	}
	return _u
}

// AddMemberRankScore adds value to the "member_rank_score" field.
func (_u *WorkProgramRunMemberUpdateOne) AddMemberRankScore(v float64) *WorkProgramRunMemberUpdateOne {
	_u.mutation.AddMemberRankScore(v)
	return _u
}

// ClearMemberRankScore clears the value of the "member_rank_score" field.
func (_u *WorkProgramRunMemberUpdateOne) ClearMemberRankScore() *WorkProgramRunMemberUpdateOne {
	_u.mutation.ClearMemberRankScore()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *WorkProgramRunMemberUpdateOne) SetCreatedAt(v time.Time) *WorkProgramRunMemberUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *WorkProgramRunMemberUpdateOne) SetNillableCreatedAt(v *time.Time) *WorkProgramRunMemberUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetWorkProgramRun sets the "work_program_run" edge to the WorkProgramRun entity.
func (_u *WorkProgramRunMemberUpdateOne) SetWorkProgramRun(v *WorkProgramRun) *WorkProgramRunMemberUpdateOne {
	return _u.SetWorkProgramRunID(v.ID)
}

// Mutation returns the WorkProgramRunMemberMutation object of the builder.
func (_u *WorkProgramRunMemberUpdateOne) Mutation() *WorkProgramRunMemberMutation {
	return _u.mutation
}

// ClearWorkProgramRun clears the "work_program_run" edge to the WorkProgramRun entity.
func (_u *WorkProgramRunMemberUpdateOne) ClearWorkProgramRun() *WorkProgramRunMemberUpdateOne {
	_u.mutation.ClearWorkProgramRun()
	return _u
}

// Where appends a list predicates to the WorkProgramRunMemberUpdate builder.
func (_u *WorkProgramRunMemberUpdateOne) Where(ps ...predicate.WorkProgramRunMember) *WorkProgramRunMemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkProgramRunMemberUpdateOne) Select(field string, fields ...string) *WorkProgramRunMemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkProgramRunMember entity.
func (_u *WorkProgramRunMemberUpdateOne) Save(ctx context.Context) (*WorkProgramRunMember, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkProgramRunMemberUpdateOne) SaveX(ctx context.Context) *WorkProgramRunMember {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkProgramRunMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkProgramRunMemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkProgramRunMemberUpdateOne) check() error {
	if v, ok := _u.mutation.RunKey(); ok {
		if err := workprogramrunmember.RunKeyValidator(v); err != nil {
			return &ValidationError{Name: "run_key", err: fmt.Errorf(`ent: validator failed for field "WorkProgramRunMember.run_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MemberTable(); ok {
		if err := workprogramrunmember.MemberTableValidator(v); err != nil {
			return &ValidationError{Name: "member_table", err: fmt.Errorf(`ent: validator failed for field "WorkProgramRunMember.member_table": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkProgramRunMemberUpdateOne) sqlSave(ctx context.Context) (_node *WorkProgramRunMember, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workprogramrunmember.Table, workprogramrunmember.Columns, sqlgraph.NewFieldSpec(workprogramrunmember.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkProgramRunMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workprogramrunmember.FieldID)
		for _, f := range fields {
			if !workprogramrunmember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workprogramrunmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RunKey(); ok {
		_spec.SetField(workprogramrunmember.FieldRunKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.MemberTable(); ok {
		_spec.SetField(workprogramrunmember.FieldMemberTable, field.TypeString, value)
	}
	if value, ok := _u.mutation.MemberID(); ok {
		_spec.SetField(workprogramrunmember.FieldMemberID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMemberID(); ok {
		_spec.AddField(workprogramrunmember.FieldMemberID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MemberKey(); ok {
		_spec.SetField(workprogramrunmember.FieldMemberKey, field.TypeString, value)
	}
	if _u.mutation.MemberKeyCleared() {
		_spec.ClearField(workprogramrunmember.FieldMemberKey, field.TypeString)
	}
	if value, ok := _u.mutation.MemberExternalKind(); ok {
		_spec.SetField(workprogramrunmember.FieldMemberExternalKind, field.TypeString, value)
	}
	if _u.mutation.MemberExternalKindCleared() {
		_spec.ClearField(workprogramrunmember.FieldMemberExternalKind, field.TypeString)
	}
	if value, ok := _u.mutation.MemberExternalID(); ok {
		_spec.SetField(workprogramrunmember.FieldMemberExternalID, field.TypeString, value)
	}
	if _u.mutation.MemberExternalIDCleared() {
		_spec.ClearField(workprogramrunmember.FieldMemberExternalID, field.TypeString)
	}
	if value, ok := _u.mutation.MemberRankScore(); ok {
		_spec.SetField(workprogramrunmember.FieldMemberRankScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMemberRankScore(); ok {
		_spec.AddField(workprogramrunmember.FieldMemberRankScore, field.TypeFloat64, value)
	}
	if _u.mutation.MemberRankScoreCleared() {
		_spec.ClearField(workprogramrunmember.FieldMemberRankScore, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(workprogramrunmember.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.WorkProgramRunCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workprogramrunmember.WorkProgramRunTable,
			Columns: []string{workprogramrunmember.WorkProgramRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workprogramrun.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkProgramRunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workprogramrunmember.WorkProgramRunTable,
			Columns: []string{workprogramrunmember.WorkProgramRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workprogramrun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WorkProgramRunMember{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workprogramrunmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
