// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cubicle/services/ontology-service/ent/evidence"
	"cubicle/services/ontology-service/ent/predicate"
	"cubicle/services/ontology-service/ent/pullrequest"
	"cubicle/services/ontology-service/ent/ticket"
	"cubicle/services/ontology-service/ent/workprogrammilestone"
	"cubicle/services/ontology-service/ent/workstream"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkProgramMilestoneUpdate is the builder for updating WorkProgramMilestone entities.
type WorkProgramMilestoneUpdate struct {
	config
	hooks    []Hook
	mutation *WorkProgramMilestoneMutation
}

// Where appends a list predicates to the WorkProgramMilestoneUpdate builder.
func (_u *WorkProgramMilestoneUpdate) Where(ps ...predicate.WorkProgramMilestone) *WorkProgramMilestoneUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *WorkProgramMilestoneUpdate) SetKey(v string) *WorkProgramMilestoneUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableKey(v *string) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetWorkstreamID sets the "workstream_id" field.
func (_u *WorkProgramMilestoneUpdate) SetWorkstreamID(v int) *WorkProgramMilestoneUpdate {
	_u.mutation.SetWorkstreamID(v)
	return _u
}

// SetNillableWorkstreamID sets the "workstream_id" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableWorkstreamID(v *int) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetWorkstreamID(*v)
	}
	return _u
}

// ClearWorkstreamID clears the value of the "workstream_id" field.
func (_u *WorkProgramMilestoneUpdate) ClearWorkstreamID() *WorkProgramMilestoneUpdate {
	_u.mutation.ClearWorkstreamID()
	return _u
}

// SetPullRequestID sets the "pull_request_id" field.
func (_u *WorkProgramMilestoneUpdate) SetPullRequestID(v int) *WorkProgramMilestoneUpdate {
	_u.mutation.SetPullRequestID(v)
	return _u
}

// SetNillablePullRequestID sets the "pull_request_id" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillablePullRequestID(v *int) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetPullRequestID(*v)
	}
	return _u
}

// ClearPullRequestID clears the value of the "pull_request_id" field.
func (_u *WorkProgramMilestoneUpdate) ClearPullRequestID() *WorkProgramMilestoneUpdate {
	_u.mutation.ClearPullRequestID()
	return _u
}

// SetTicketID sets the "ticket_id" field.
func (_u *WorkProgramMilestoneUpdate) SetTicketID(v int) *WorkProgramMilestoneUpdate {
	_u.mutation.SetTicketID(v)
	return _u
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableTicketID(v *int) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetTicketID(*v)
	}
	return _u
}

// ClearTicketID clears the value of the "ticket_id" field.
func (_u *WorkProgramMilestoneUpdate) ClearTicketID() *WorkProgramMilestoneUpdate {
	_u.mutation.ClearTicketID()
	return _u
}

// SetWorkstreamKey sets the "workstream_key" field.
func (_u *WorkProgramMilestoneUpdate) SetWorkstreamKey(v string) *WorkProgramMilestoneUpdate {
	_u.mutation.SetWorkstreamKey(v)
	return _u
}

// SetNillableWorkstreamKey sets the "workstream_key" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableWorkstreamKey(v *string) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetWorkstreamKey(*v)
	}
	return _u
}

// SetSubjectKind sets the "subject_kind" field.
func (_u *WorkProgramMilestoneUpdate) SetSubjectKind(v workprogrammilestone.SubjectKind) *WorkProgramMilestoneUpdate {
	_u.mutation.SetSubjectKind(v)
	return _u
}

// SetNillableSubjectKind sets the "subject_kind" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableSubjectKind(v *workprogrammilestone.SubjectKind) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetSubjectKind(*v)
	}
	return _u
}

// SetSubjectKey sets the "subject_key" field.
func (_u *WorkProgramMilestoneUpdate) SetSubjectKey(v string) *WorkProgramMilestoneUpdate {
	_u.mutation.SetSubjectKey(v)
	return _u
}

// SetNillableSubjectKey sets the "subject_key" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableSubjectKey(v *string) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetSubjectKey(*v)
	}
	return _u
}

// SetMilestoneKind sets the "milestone_kind" field.
func (_u *WorkProgramMilestoneUpdate) SetMilestoneKind(v workprogrammilestone.MilestoneKind) *WorkProgramMilestoneUpdate {
	_u.mutation.SetMilestoneKind(v)
	return _u
}

// SetNillableMilestoneKind sets the "milestone_kind" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableMilestoneKind(v *workprogrammilestone.MilestoneKind) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetMilestoneKind(*v)
	}
	return _u
}

// SetMilestoneName sets the "milestone_name" field.
func (_u *WorkProgramMilestoneUpdate) SetMilestoneName(v string) *WorkProgramMilestoneUpdate {
	_u.mutation.SetMilestoneName(v)
	return _u
}

// SetNillableMilestoneName sets the "milestone_name" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableMilestoneName(v *string) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetMilestoneName(*v)
	}
	return _u
}

// SetTargetDate sets the "target_date" field.
func (_u *WorkProgramMilestoneUpdate) SetTargetDate(v time.Time) *WorkProgramMilestoneUpdate {
	_u.mutation.SetTargetDate(v)
	return _u
}

// SetNillableTargetDate sets the "target_date" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableTargetDate(v *time.Time) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetTargetDate(*v)
	}
	return _u
}

// ClearTargetDate clears the value of the "target_date" field.
func (_u *WorkProgramMilestoneUpdate) ClearTargetDate() *WorkProgramMilestoneUpdate {
	_u.mutation.ClearTargetDate()
	return _u
}

// SetOutcomeDate sets the "outcome_date" field.
func (_u *WorkProgramMilestoneUpdate) SetOutcomeDate(v time.Time) *WorkProgramMilestoneUpdate {
	_u.mutation.SetOutcomeDate(v)
	return _u
}

// SetNillableOutcomeDate sets the "outcome_date" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableOutcomeDate(v *time.Time) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetOutcomeDate(*v)
	}
	return _u
}

// ClearOutcomeDate clears the value of the "outcome_date" field.
func (_u *WorkProgramMilestoneUpdate) ClearOutcomeDate() *WorkProgramMilestoneUpdate {
	_u.mutation.ClearOutcomeDate()
	return _u
}

// SetMilestoneState sets the "milestone_state" field.
func (_u *WorkProgramMilestoneUpdate) SetMilestoneState(v workprogrammilestone.MilestoneState) *WorkProgramMilestoneUpdate {
	_u.mutation.SetMilestoneState(v)
	return _u
}

// SetNillableMilestoneState sets the "milestone_state" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableMilestoneState(v *workprogrammilestone.MilestoneState) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetMilestoneState(*v)
	}
	return _u
}

// SetCommitmentStrength sets the "commitment_strength" field.
func (_u *WorkProgramMilestoneUpdate) SetCommitmentStrength(v workprogrammilestone.CommitmentStrength) *WorkProgramMilestoneUpdate {
	_u.mutation.SetCommitmentStrength(v)
	return _u
}

// SetNillableCommitmentStrength sets the "commitment_strength" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableCommitmentStrength(v *workprogrammilestone.CommitmentStrength) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetCommitmentStrength(*v)
	}
	return _u
}

// SetDateClaimAllowed sets the "date_claim_allowed" field.
func (_u *WorkProgramMilestoneUpdate) SetDateClaimAllowed(v bool) *WorkProgramMilestoneUpdate {
	_u.mutation.SetDateClaimAllowed(v)
	return _u
}

// SetNillableDateClaimAllowed sets the "date_claim_allowed" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableDateClaimAllowed(v *bool) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetDateClaimAllowed(*v)
	}
	return _u
}

// SetDeliveryCommitmentAllowed sets the "delivery_commitment_allowed" field.
func (_u *WorkProgramMilestoneUpdate) SetDeliveryCommitmentAllowed(v bool) *WorkProgramMilestoneUpdate {
	_u.mutation.SetDeliveryCommitmentAllowed(v)
	return _u
}

// SetNillableDeliveryCommitmentAllowed sets the "delivery_commitment_allowed" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableDeliveryCommitmentAllowed(v *bool) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetDeliveryCommitmentAllowed(*v)
	}
	return _u
}

// SetClaimGateReason sets the "claim_gate_reason" field.
func (_u *WorkProgramMilestoneUpdate) SetClaimGateReason(v string) *WorkProgramMilestoneUpdate {
	_u.mutation.SetClaimGateReason(v)
	return _u
}

// SetNillableClaimGateReason sets the "claim_gate_reason" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableClaimGateReason(v *string) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetClaimGateReason(*v)
	}
	return _u
}

// SetSourceField sets the "source_field" field.
func (_u *WorkProgramMilestoneUpdate) SetSourceField(v string) *WorkProgramMilestoneUpdate {
	_u.mutation.SetSourceField(v)
	return _u
}

// SetNillableSourceField sets the "source_field" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableSourceField(v *string) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetSourceField(*v)
	}
	return _u
}

// SetSourcePayloadKey sets the "source_payload_key" field.
func (_u *WorkProgramMilestoneUpdate) SetSourcePayloadKey(v string) *WorkProgramMilestoneUpdate {
	_u.mutation.SetSourcePayloadKey(v)
	return _u
}

// SetNillableSourcePayloadKey sets the "source_payload_key" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableSourcePayloadKey(v *string) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetSourcePayloadKey(*v)
	}
	return _u
}

// ClearSourcePayloadKey clears the value of the "source_payload_key" field.
func (_u *WorkProgramMilestoneUpdate) ClearSourcePayloadKey() *WorkProgramMilestoneUpdate {
	_u.mutation.ClearSourcePayloadKey()
	return _u
}

// SetCapturedAt sets the "captured_at" field.
func (_u *WorkProgramMilestoneUpdate) SetCapturedAt(v time.Time) *WorkProgramMilestoneUpdate {
	_u.mutation.SetCapturedAt(v)
	return _u
}

// SetNillableCapturedAt sets the "captured_at" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableCapturedAt(v *time.Time) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetCapturedAt(*v)
	}
	return _u
}

// ClearCapturedAt clears the value of the "captured_at" field.
func (_u *WorkProgramMilestoneUpdate) ClearCapturedAt() *WorkProgramMilestoneUpdate {
	_u.mutation.ClearCapturedAt()
	return _u
}

// SetGeneratedAt sets the "generated_at" field.
func (_u *WorkProgramMilestoneUpdate) SetGeneratedAt(v time.Time) *WorkProgramMilestoneUpdate {
	_u.mutation.SetGeneratedAt(v)
	return _u
}

// SetNillableGeneratedAt sets the "generated_at" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableGeneratedAt(v *time.Time) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetGeneratedAt(*v)
	}
	return _u
}

// ClearGeneratedAt clears the value of the "generated_at" field.
func (_u *WorkProgramMilestoneUpdate) ClearGeneratedAt() *WorkProgramMilestoneUpdate {
	_u.mutation.ClearGeneratedAt()
	return _u
}

// SetSourceSystem sets the "source_system" field.
func (_u *WorkProgramMilestoneUpdate) SetSourceSystem(v string) *WorkProgramMilestoneUpdate {
	_u.mutation.SetSourceSystem(v)
	return _u
}

// SetNillableSourceSystem sets the "source_system" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableSourceSystem(v *string) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetSourceSystem(*v)
	}
	return _u
}

// ClearSourceSystem clears the value of the "source_system" field.
func (_u *WorkProgramMilestoneUpdate) ClearSourceSystem() *WorkProgramMilestoneUpdate {
	_u.mutation.ClearSourceSystem()
	return _u
}

// SetSourceInstance sets the "source_instance" field.
func (_u *WorkProgramMilestoneUpdate) SetSourceInstance(v string) *WorkProgramMilestoneUpdate {
	_u.mutation.SetSourceInstance(v)
	return _u
}

// SetNillableSourceInstance sets the "source_instance" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableSourceInstance(v *string) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetSourceInstance(*v)
	}
	return _u
}

// ClearSourceInstance clears the value of the "source_instance" field.
func (_u *WorkProgramMilestoneUpdate) ClearSourceInstance() *WorkProgramMilestoneUpdate {
	_u.mutation.ClearSourceInstance()
	return _u
}

// SetExternalKind sets the "external_kind" field.
func (_u *WorkProgramMilestoneUpdate) SetExternalKind(v string) *WorkProgramMilestoneUpdate {
	_u.mutation.SetExternalKind(v)
	return _u
}

// SetNillableExternalKind sets the "external_kind" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableExternalKind(v *string) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetExternalKind(*v)
	}
	return _u
}

// ClearExternalKind clears the value of the "external_kind" field.
func (_u *WorkProgramMilestoneUpdate) ClearExternalKind() *WorkProgramMilestoneUpdate {
	_u.mutation.ClearExternalKind()
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *WorkProgramMilestoneUpdate) SetExternalID(v string) *WorkProgramMilestoneUpdate {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableExternalID(v *string) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// ClearExternalID clears the value of the "external_id" field.
func (_u *WorkProgramMilestoneUpdate) ClearExternalID() *WorkProgramMilestoneUpdate {
	_u.mutation.ClearExternalID()
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *WorkProgramMilestoneUpdate) SetSourceURL(v string) *WorkProgramMilestoneUpdate {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableSourceURL(v *string) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// ClearSourceURL clears the value of the "source_url" field.
func (_u *WorkProgramMilestoneUpdate) ClearSourceURL() *WorkProgramMilestoneUpdate {
	_u.mutation.ClearSourceURL()
	return _u
}

// SetLatestEvidenceID sets the "latest_evidence_id" field.
func (_u *WorkProgramMilestoneUpdate) SetLatestEvidenceID(v int) *WorkProgramMilestoneUpdate {
	_u.mutation.SetLatestEvidenceID(v)
	return _u
}

// SetNillableLatestEvidenceID sets the "latest_evidence_id" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableLatestEvidenceID(v *int) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetLatestEvidenceID(*v)
	}
	return _u
}

// ClearLatestEvidenceID clears the value of the "latest_evidence_id" field.
func (_u *WorkProgramMilestoneUpdate) ClearLatestEvidenceID() *WorkProgramMilestoneUpdate {
	_u.mutation.ClearLatestEvidenceID()
	return _u
}

// SetEvidenceCount sets the "evidence_count" field.
func (_u *WorkProgramMilestoneUpdate) SetEvidenceCount(v int) *WorkProgramMilestoneUpdate {
	_u.mutation.ResetEvidenceCount()
	_u.mutation.SetEvidenceCount(v)
	return _u
}

// SetNillableEvidenceCount sets the "evidence_count" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableEvidenceCount(v *int) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetEvidenceCount(*v)
	}
	return _u
}

// AddEvidenceCount adds value to the "evidence_count" field.
func (_u *WorkProgramMilestoneUpdate) AddEvidenceCount(v int) *WorkProgramMilestoneUpdate {
	_u.mutation.AddEvidenceCount(v)
	return _u
}

// SetFreshnessState sets the "freshness_state" field.
func (_u *WorkProgramMilestoneUpdate) SetFreshnessState(v workprogrammilestone.FreshnessState) *WorkProgramMilestoneUpdate {
	_u.mutation.SetFreshnessState(v)
	return _u
}

// SetNillableFreshnessState sets the "freshness_state" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableFreshnessState(v *workprogrammilestone.FreshnessState) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetFreshnessState(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *WorkProgramMilestoneUpdate) SetVisibility(v workprogrammilestone.Visibility) *WorkProgramMilestoneUpdate {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableVisibility(v *workprogrammilestone.Visibility) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetConfidence sets the "confidence" field.
func (_u *WorkProgramMilestoneUpdate) SetConfidence(v float64) *WorkProgramMilestoneUpdate {
	_u.mutation.ResetConfidence()
	_u.mutation.SetConfidence(v)
	return _u
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableConfidence(v *float64) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetConfidence(*v)
	}
	return _u
}

// AddConfidence adds value to the "confidence" field.
func (_u *WorkProgramMilestoneUpdate) AddConfidence(v float64) *WorkProgramMilestoneUpdate {
	_u.mutation.AddConfidence(v)
	return _u
}

// SetEventCount sets the "event_count" field.
func (_u *WorkProgramMilestoneUpdate) SetEventCount(v int) *WorkProgramMilestoneUpdate {
	_u.mutation.ResetEventCount()
	_u.mutation.SetEventCount(v)
	return _u
}

// SetNillableEventCount sets the "event_count" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableEventCount(v *int) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetEventCount(*v)
	}
	return _u
}

// AddEventCount adds value to the "event_count" field.
func (_u *WorkProgramMilestoneUpdate) AddEventCount(v int) *WorkProgramMilestoneUpdate {
	_u.mutation.AddEventCount(v)
	return _u
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_u *WorkProgramMilestoneUpdate) SetFirstSeenAt(v time.Time) *WorkProgramMilestoneUpdate {
	_u.mutation.SetFirstSeenAt(v)
	return _u
}

// SetNillableFirstSeenAt sets the "first_seen_at" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableFirstSeenAt(v *time.Time) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetFirstSeenAt(*v)
	}
	return _u
}

// ClearFirstSeenAt clears the value of the "first_seen_at" field.
func (_u *WorkProgramMilestoneUpdate) ClearFirstSeenAt() *WorkProgramMilestoneUpdate {
	_u.mutation.ClearFirstSeenAt()
	return _u
}

// SetLastActivityAt sets the "last_activity_at" field.
func (_u *WorkProgramMilestoneUpdate) SetLastActivityAt(v time.Time) *WorkProgramMilestoneUpdate {
	_u.mutation.SetLastActivityAt(v)
	return _u
}

// SetNillableLastActivityAt sets the "last_activity_at" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableLastActivityAt(v *time.Time) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetLastActivityAt(*v)
	}
	return _u
}

// ClearLastActivityAt clears the value of the "last_activity_at" field.
func (_u *WorkProgramMilestoneUpdate) ClearLastActivityAt() *WorkProgramMilestoneUpdate {
	_u.mutation.ClearLastActivityAt()
	return _u
}

// SetRankScore sets the "rank_score" field.
func (_u *WorkProgramMilestoneUpdate) SetRankScore(v float64) *WorkProgramMilestoneUpdate {
	_u.mutation.ResetRankScore()
	_u.mutation.SetRankScore(v)
	return _u
}

// SetNillableRankScore sets the "rank_score" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdate) SetNillableRankScore(v *float64) *WorkProgramMilestoneUpdate {
	if v != nil {
		_u.SetRankScore(*v)
	}
	return _u
}

// AddRankScore adds value to the "rank_score" field.
func (_u *WorkProgramMilestoneUpdate) AddRankScore(v float64) *WorkProgramMilestoneUpdate {
	_u.mutation.AddRankScore(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkProgramMilestoneUpdate) SetUpdatedAt(v time.Time) *WorkProgramMilestoneUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkstream sets the "workstream" edge to the Workstream entity.
func (_u *WorkProgramMilestoneUpdate) SetWorkstream(v *Workstream) *WorkProgramMilestoneUpdate {
	return _u.SetWorkstreamID(v.ID)
}

// SetPullRequest sets the "pull_request" edge to the PullRequest entity.
func (_u *WorkProgramMilestoneUpdate) SetPullRequest(v *PullRequest) *WorkProgramMilestoneUpdate {
	return _u.SetPullRequestID(v.ID)
}

// SetTicket sets the "ticket" edge to the Ticket entity.
func (_u *WorkProgramMilestoneUpdate) SetTicket(v *Ticket) *WorkProgramMilestoneUpdate {
	return _u.SetTicketID(v.ID)
}

// SetLatestEvidence sets the "latest_evidence" edge to the Evidence entity.
func (_u *WorkProgramMilestoneUpdate) SetLatestEvidence(v *Evidence) *WorkProgramMilestoneUpdate {
	return _u.SetLatestEvidenceID(v.ID)
}

// Mutation returns the WorkProgramMilestoneMutation object of the builder.
func (_u *WorkProgramMilestoneUpdate) Mutation() *WorkProgramMilestoneMutation {
	return _u.mutation
}

// ClearWorkstream clears the "workstream" edge to the Workstream entity.
func (_u *WorkProgramMilestoneUpdate) ClearWorkstream() *WorkProgramMilestoneUpdate {
	_u.mutation.ClearWorkstream()
	return _u
}

// ClearPullRequest clears the "pull_request" edge to the PullRequest entity.
func (_u *WorkProgramMilestoneUpdate) ClearPullRequest() *WorkProgramMilestoneUpdate {
	_u.mutation.ClearPullRequest()
	return _u
}

// ClearTicket clears the "ticket" edge to the Ticket entity.
func (_u *WorkProgramMilestoneUpdate) ClearTicket() *WorkProgramMilestoneUpdate {
	_u.mutation.ClearTicket()
	return _u
}

// ClearLatestEvidence clears the "latest_evidence" edge to the Evidence entity.
func (_u *WorkProgramMilestoneUpdate) ClearLatestEvidence() *WorkProgramMilestoneUpdate {
	_u.mutation.ClearLatestEvidence()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkProgramMilestoneUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkProgramMilestoneUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkProgramMilestoneUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkProgramMilestoneUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkProgramMilestoneUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workprogrammilestone.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkProgramMilestoneUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := workprogrammilestone.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WorkstreamKey(); ok {
		if err := workprogrammilestone.WorkstreamKeyValidator(v); err != nil {
			return &ValidationError{Name: "workstream_key", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.workstream_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubjectKind(); ok {
		if err := workprogrammilestone.SubjectKindValidator(v); err != nil {
			return &ValidationError{Name: "subject_kind", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.subject_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubjectKey(); ok {
		if err := workprogrammilestone.SubjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "subject_key", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.subject_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MilestoneKind(); ok {
		if err := workprogrammilestone.MilestoneKindValidator(v); err != nil {
			return &ValidationError{Name: "milestone_kind", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.milestone_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MilestoneName(); ok {
		if err := workprogrammilestone.MilestoneNameValidator(v); err != nil {
			return &ValidationError{Name: "milestone_name", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.milestone_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MilestoneState(); ok {
		if err := workprogrammilestone.MilestoneStateValidator(v); err != nil {
			return &ValidationError{Name: "milestone_state", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.milestone_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CommitmentStrength(); ok {
		if err := workprogrammilestone.CommitmentStrengthValidator(v); err != nil {
			return &ValidationError{Name: "commitment_strength", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.commitment_strength": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClaimGateReason(); ok {
		if err := workprogrammilestone.ClaimGateReasonValidator(v); err != nil {
			return &ValidationError{Name: "claim_gate_reason", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.claim_gate_reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceField(); ok {
		if err := workprogrammilestone.SourceFieldValidator(v); err != nil {
			return &ValidationError{Name: "source_field", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.source_field": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FreshnessState(); ok {
		if err := workprogrammilestone.FreshnessStateValidator(v); err != nil {
			return &ValidationError{Name: "freshness_state", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.freshness_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visibility(); ok {
		if err := workprogrammilestone.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.visibility": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkProgramMilestoneUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workprogrammilestone.Table, workprogrammilestone.Columns, sqlgraph.NewFieldSpec(workprogrammilestone.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(workprogrammilestone.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.WorkstreamKey(); ok {
		_spec.SetField(workprogrammilestone.FieldWorkstreamKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubjectKind(); ok {
		_spec.SetField(workprogrammilestone.FieldSubjectKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SubjectKey(); ok {
		_spec.SetField(workprogrammilestone.FieldSubjectKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.MilestoneKind(); ok {
		_spec.SetField(workprogrammilestone.FieldMilestoneKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.MilestoneName(); ok {
		_spec.SetField(workprogrammilestone.FieldMilestoneName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetDate(); ok {
		_spec.SetField(workprogrammilestone.FieldTargetDate, field.TypeTime, value)
	}
	if _u.mutation.TargetDateCleared() {
		_spec.ClearField(workprogrammilestone.FieldTargetDate, field.TypeTime)
	}
	if value, ok := _u.mutation.OutcomeDate(); ok {
		_spec.SetField(workprogrammilestone.FieldOutcomeDate, field.TypeTime, value)
	}
	if _u.mutation.OutcomeDateCleared() {
		_spec.ClearField(workprogrammilestone.FieldOutcomeDate, field.TypeTime)
	}
	if value, ok := _u.mutation.MilestoneState(); ok {
		_spec.SetField(workprogrammilestone.FieldMilestoneState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CommitmentStrength(); ok {
		_spec.SetField(workprogrammilestone.FieldCommitmentStrength, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DateClaimAllowed(); ok {
		_spec.SetField(workprogrammilestone.FieldDateClaimAllowed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DeliveryCommitmentAllowed(); ok {
		_spec.SetField(workprogrammilestone.FieldDeliveryCommitmentAllowed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ClaimGateReason(); ok {
		_spec.SetField(workprogrammilestone.FieldClaimGateReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceField(); ok {
		_spec.SetField(workprogrammilestone.FieldSourceField, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourcePayloadKey(); ok {
		_spec.SetField(workprogrammilestone.FieldSourcePayloadKey, field.TypeString, value)
	}
	if _u.mutation.SourcePayloadKeyCleared() {
		_spec.ClearField(workprogrammilestone.FieldSourcePayloadKey, field.TypeString)
	}
	if value, ok := _u.mutation.CapturedAt(); ok {
		_spec.SetField(workprogrammilestone.FieldCapturedAt, field.TypeTime, value)
	}
	if _u.mutation.CapturedAtCleared() {
		_spec.ClearField(workprogrammilestone.FieldCapturedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GeneratedAt(); ok {
		_spec.SetField(workprogrammilestone.FieldGeneratedAt, field.TypeTime, value)
	}
	if _u.mutation.GeneratedAtCleared() {
		_spec.ClearField(workprogrammilestone.FieldGeneratedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SourceSystem(); ok {
		_spec.SetField(workprogrammilestone.FieldSourceSystem, field.TypeString, value)
	}
	if _u.mutation.SourceSystemCleared() {
		_spec.ClearField(workprogrammilestone.FieldSourceSystem, field.TypeString)
	}
	if value, ok := _u.mutation.SourceInstance(); ok {
		_spec.SetField(workprogrammilestone.FieldSourceInstance, field.TypeString, value)
	}
	if _u.mutation.SourceInstanceCleared() {
		_spec.ClearField(workprogrammilestone.FieldSourceInstance, field.TypeString)
	}
	if value, ok := _u.mutation.ExternalKind(); ok {
		_spec.SetField(workprogrammilestone.FieldExternalKind, field.TypeString, value)
	}
	if _u.mutation.ExternalKindCleared() {
		_spec.ClearField(workprogrammilestone.FieldExternalKind, field.TypeString)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(workprogrammilestone.FieldExternalID, field.TypeString, value)
	}
	if _u.mutation.ExternalIDCleared() {
		_spec.ClearField(workprogrammilestone.FieldExternalID, field.TypeString)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(workprogrammilestone.FieldSourceURL, field.TypeString, value)
	}
	if _u.mutation.SourceURLCleared() {
		_spec.ClearField(workprogrammilestone.FieldSourceURL, field.TypeString)
	}
	if value, ok := _u.mutation.EvidenceCount(); ok {
		_spec.SetField(workprogrammilestone.FieldEvidenceCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEvidenceCount(); ok {
		_spec.AddField(workprogrammilestone.FieldEvidenceCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FreshnessState(); ok {
		_spec.SetField(workprogrammilestone.FieldFreshnessState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(workprogrammilestone.FieldVisibility, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Confidence(); ok {
		_spec.SetField(workprogrammilestone.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConfidence(); ok {
		_spec.AddField(workprogrammilestone.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EventCount(); ok {
		_spec.SetField(workprogrammilestone.FieldEventCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEventCount(); ok {
		_spec.AddField(workprogrammilestone.FieldEventCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FirstSeenAt(); ok {
		_spec.SetField(workprogrammilestone.FieldFirstSeenAt, field.TypeTime, value)
	}
	if _u.mutation.FirstSeenAtCleared() {
		_spec.ClearField(workprogrammilestone.FieldFirstSeenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastActivityAt(); ok {
		_spec.SetField(workprogrammilestone.FieldLastActivityAt, field.TypeTime, value)
	}
	if _u.mutation.LastActivityAtCleared() {
		_spec.ClearField(workprogrammilestone.FieldLastActivityAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RankScore(); ok {
		_spec.SetField(workprogrammilestone.FieldRankScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRankScore(); ok {
		_spec.AddField(workprogrammilestone.FieldRankScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workprogrammilestone.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.WorkstreamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workprogrammilestone.WorkstreamTable,
			Columns: []string{workprogrammilestone.WorkstreamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workstream.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkstreamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workprogrammilestone.WorkstreamTable,
			Columns: []string{workprogrammilestone.WorkstreamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workstream.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PullRequestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workprogrammilestone.PullRequestTable,
			Columns: []string{workprogrammilestone.PullRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pullrequest.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PullRequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workprogrammilestone.PullRequestTable,
			Columns: []string{workprogrammilestone.PullRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pullrequest.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TicketCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workprogrammilestone.TicketTable,
			Columns: []string{workprogrammilestone.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workprogrammilestone.TicketTable,
			Columns: []string{workprogrammilestone.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LatestEvidenceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workprogrammilestone.LatestEvidenceTable,
			Columns: []string{workprogrammilestone.LatestEvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LatestEvidenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workprogrammilestone.LatestEvidenceTable,
			Columns: []string{workprogrammilestone.LatestEvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workprogrammilestone.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkProgramMilestoneUpdateOne is the builder for updating a single WorkProgramMilestone entity.
type WorkProgramMilestoneUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkProgramMilestoneMutation
}

// SetKey sets the "key" field.
func (_u *WorkProgramMilestoneUpdateOne) SetKey(v string) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableKey(v *string) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetWorkstreamID sets the "workstream_id" field.
func (_u *WorkProgramMilestoneUpdateOne) SetWorkstreamID(v int) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetWorkstreamID(v)
	return _u
}

// SetNillableWorkstreamID sets the "workstream_id" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableWorkstreamID(v *int) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetWorkstreamID(*v)
	}
	return _u
}

// ClearWorkstreamID clears the value of the "workstream_id" field.
func (_u *WorkProgramMilestoneUpdateOne) ClearWorkstreamID() *WorkProgramMilestoneUpdateOne {
	_u.mutation.ClearWorkstreamID()
	return _u
}

// SetPullRequestID sets the "pull_request_id" field.
func (_u *WorkProgramMilestoneUpdateOne) SetPullRequestID(v int) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetPullRequestID(v)
	return _u
}

// SetNillablePullRequestID sets the "pull_request_id" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillablePullRequestID(v *int) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetPullRequestID(*v)
	}
	return _u
}

// ClearPullRequestID clears the value of the "pull_request_id" field.
func (_u *WorkProgramMilestoneUpdateOne) ClearPullRequestID() *WorkProgramMilestoneUpdateOne {
	_u.mutation.ClearPullRequestID()
	return _u
}

// SetTicketID sets the "ticket_id" field.
func (_u *WorkProgramMilestoneUpdateOne) SetTicketID(v int) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetTicketID(v)
	return _u
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableTicketID(v *int) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetTicketID(*v)
	}
	return _u
}

// ClearTicketID clears the value of the "ticket_id" field.
func (_u *WorkProgramMilestoneUpdateOne) ClearTicketID() *WorkProgramMilestoneUpdateOne {
	_u.mutation.ClearTicketID()
	return _u
}

// SetWorkstreamKey sets the "workstream_key" field.
func (_u *WorkProgramMilestoneUpdateOne) SetWorkstreamKey(v string) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetWorkstreamKey(v)
	return _u
}

// SetNillableWorkstreamKey sets the "workstream_key" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableWorkstreamKey(v *string) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetWorkstreamKey(*v)
	}
	return _u
}

// SetSubjectKind sets the "subject_kind" field.
func (_u *WorkProgramMilestoneUpdateOne) SetSubjectKind(v workprogrammilestone.SubjectKind) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetSubjectKind(v)
	return _u
}

// SetNillableSubjectKind sets the "subject_kind" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableSubjectKind(v *workprogrammilestone.SubjectKind) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetSubjectKind(*v)
	}
	return _u
}

// SetSubjectKey sets the "subject_key" field.
func (_u *WorkProgramMilestoneUpdateOne) SetSubjectKey(v string) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetSubjectKey(v)
	return _u
}

// SetNillableSubjectKey sets the "subject_key" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableSubjectKey(v *string) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetSubjectKey(*v)
	}
	return _u
}

// SetMilestoneKind sets the "milestone_kind" field.
func (_u *WorkProgramMilestoneUpdateOne) SetMilestoneKind(v workprogrammilestone.MilestoneKind) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetMilestoneKind(v)
	return _u
}

// SetNillableMilestoneKind sets the "milestone_kind" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableMilestoneKind(v *workprogrammilestone.MilestoneKind) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetMilestoneKind(*v)
	}
	return _u
}

// SetMilestoneName sets the "milestone_name" field.
func (_u *WorkProgramMilestoneUpdateOne) SetMilestoneName(v string) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetMilestoneName(v)
	return _u
}

// SetNillableMilestoneName sets the "milestone_name" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableMilestoneName(v *string) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetMilestoneName(*v)
	}
	return _u
}

// SetTargetDate sets the "target_date" field.
func (_u *WorkProgramMilestoneUpdateOne) SetTargetDate(v time.Time) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetTargetDate(v)
	return _u
}

// SetNillableTargetDate sets the "target_date" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableTargetDate(v *time.Time) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetTargetDate(*v)
	}
	return _u
}

// ClearTargetDate clears the value of the "target_date" field.
func (_u *WorkProgramMilestoneUpdateOne) ClearTargetDate() *WorkProgramMilestoneUpdateOne {
	_u.mutation.ClearTargetDate()
	return _u
}

// SetOutcomeDate sets the "outcome_date" field.
func (_u *WorkProgramMilestoneUpdateOne) SetOutcomeDate(v time.Time) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetOutcomeDate(v)
	return _u
}

// SetNillableOutcomeDate sets the "outcome_date" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableOutcomeDate(v *time.Time) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetOutcomeDate(*v)
	}
	return _u
}

// ClearOutcomeDate clears the value of the "outcome_date" field.
func (_u *WorkProgramMilestoneUpdateOne) ClearOutcomeDate() *WorkProgramMilestoneUpdateOne {
	_u.mutation.ClearOutcomeDate()
	return _u
}

// SetMilestoneState sets the "milestone_state" field.
func (_u *WorkProgramMilestoneUpdateOne) SetMilestoneState(v workprogrammilestone.MilestoneState) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetMilestoneState(v)
	return _u
}

// SetNillableMilestoneState sets the "milestone_state" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableMilestoneState(v *workprogrammilestone.MilestoneState) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetMilestoneState(*v)
	}
	return _u
}

// SetCommitmentStrength sets the "commitment_strength" field.
func (_u *WorkProgramMilestoneUpdateOne) SetCommitmentStrength(v workprogrammilestone.CommitmentStrength) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetCommitmentStrength(v)
	return _u
}

// SetNillableCommitmentStrength sets the "commitment_strength" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableCommitmentStrength(v *workprogrammilestone.CommitmentStrength) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetCommitmentStrength(*v)
	}
	return _u
}

// SetDateClaimAllowed sets the "date_claim_allowed" field.
func (_u *WorkProgramMilestoneUpdateOne) SetDateClaimAllowed(v bool) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetDateClaimAllowed(v)
	return _u
}

// SetNillableDateClaimAllowed sets the "date_claim_allowed" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableDateClaimAllowed(v *bool) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetDateClaimAllowed(*v)
	}
	return _u
}

// SetDeliveryCommitmentAllowed sets the "delivery_commitment_allowed" field.
func (_u *WorkProgramMilestoneUpdateOne) SetDeliveryCommitmentAllowed(v bool) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetDeliveryCommitmentAllowed(v)
	return _u
}

// SetNillableDeliveryCommitmentAllowed sets the "delivery_commitment_allowed" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableDeliveryCommitmentAllowed(v *bool) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetDeliveryCommitmentAllowed(*v)
	}
	return _u
}

// SetClaimGateReason sets the "claim_gate_reason" field.
func (_u *WorkProgramMilestoneUpdateOne) SetClaimGateReason(v string) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetClaimGateReason(v)
	return _u
}

// SetNillableClaimGateReason sets the "claim_gate_reason" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableClaimGateReason(v *string) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetClaimGateReason(*v)
	}
	return _u
}

// SetSourceField sets the "source_field" field.
func (_u *WorkProgramMilestoneUpdateOne) SetSourceField(v string) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetSourceField(v)
	return _u
}

// SetNillableSourceField sets the "source_field" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableSourceField(v *string) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetSourceField(*v)
	}
	return _u
}

// SetSourcePayloadKey sets the "source_payload_key" field.
func (_u *WorkProgramMilestoneUpdateOne) SetSourcePayloadKey(v string) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetSourcePayloadKey(v)
	return _u
}

// SetNillableSourcePayloadKey sets the "source_payload_key" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableSourcePayloadKey(v *string) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetSourcePayloadKey(*v)
	}
	return _u
}

// ClearSourcePayloadKey clears the value of the "source_payload_key" field.
func (_u *WorkProgramMilestoneUpdateOne) ClearSourcePayloadKey() *WorkProgramMilestoneUpdateOne {
	_u.mutation.ClearSourcePayloadKey()
	return _u
}

// SetCapturedAt sets the "captured_at" field.
func (_u *WorkProgramMilestoneUpdateOne) SetCapturedAt(v time.Time) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetCapturedAt(v)
	return _u
}

// SetNillableCapturedAt sets the "captured_at" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableCapturedAt(v *time.Time) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetCapturedAt(*v)
	}
	return _u
}

// ClearCapturedAt clears the value of the "captured_at" field.
func (_u *WorkProgramMilestoneUpdateOne) ClearCapturedAt() *WorkProgramMilestoneUpdateOne {
	_u.mutation.ClearCapturedAt()
	return _u
}

// SetGeneratedAt sets the "generated_at" field.
func (_u *WorkProgramMilestoneUpdateOne) SetGeneratedAt(v time.Time) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetGeneratedAt(v)
	return _u
}

// SetNillableGeneratedAt sets the "generated_at" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableGeneratedAt(v *time.Time) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetGeneratedAt(*v)
	}
	return _u
}

// ClearGeneratedAt clears the value of the "generated_at" field.
func (_u *WorkProgramMilestoneUpdateOne) ClearGeneratedAt() *WorkProgramMilestoneUpdateOne {
	_u.mutation.ClearGeneratedAt()
	return _u
}

// SetSourceSystem sets the "source_system" field.
func (_u *WorkProgramMilestoneUpdateOne) SetSourceSystem(v string) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetSourceSystem(v)
	return _u
}

// SetNillableSourceSystem sets the "source_system" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableSourceSystem(v *string) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetSourceSystem(*v)
	}
	return _u
}

// ClearSourceSystem clears the value of the "source_system" field.
func (_u *WorkProgramMilestoneUpdateOne) ClearSourceSystem() *WorkProgramMilestoneUpdateOne {
	_u.mutation.ClearSourceSystem()
	return _u
}

// SetSourceInstance sets the "source_instance" field.
func (_u *WorkProgramMilestoneUpdateOne) SetSourceInstance(v string) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetSourceInstance(v)
	return _u
}

// SetNillableSourceInstance sets the "source_instance" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableSourceInstance(v *string) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetSourceInstance(*v)
	}
	return _u
}

// ClearSourceInstance clears the value of the "source_instance" field.
func (_u *WorkProgramMilestoneUpdateOne) ClearSourceInstance() *WorkProgramMilestoneUpdateOne {
	_u.mutation.ClearSourceInstance()
	return _u
}

// SetExternalKind sets the "external_kind" field.
func (_u *WorkProgramMilestoneUpdateOne) SetExternalKind(v string) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetExternalKind(v)
	return _u
}

// SetNillableExternalKind sets the "external_kind" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableExternalKind(v *string) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetExternalKind(*v)
	}
	return _u
}

// ClearExternalKind clears the value of the "external_kind" field.
func (_u *WorkProgramMilestoneUpdateOne) ClearExternalKind() *WorkProgramMilestoneUpdateOne {
	_u.mutation.ClearExternalKind()
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *WorkProgramMilestoneUpdateOne) SetExternalID(v string) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableExternalID(v *string) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// ClearExternalID clears the value of the "external_id" field.
func (_u *WorkProgramMilestoneUpdateOne) ClearExternalID() *WorkProgramMilestoneUpdateOne {
	_u.mutation.ClearExternalID()
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *WorkProgramMilestoneUpdateOne) SetSourceURL(v string) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableSourceURL(v *string) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// ClearSourceURL clears the value of the "source_url" field.
func (_u *WorkProgramMilestoneUpdateOne) ClearSourceURL() *WorkProgramMilestoneUpdateOne {
	_u.mutation.ClearSourceURL()
	return _u
}

// SetLatestEvidenceID sets the "latest_evidence_id" field.
func (_u *WorkProgramMilestoneUpdateOne) SetLatestEvidenceID(v int) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetLatestEvidenceID(v)
	return _u
}

// SetNillableLatestEvidenceID sets the "latest_evidence_id" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableLatestEvidenceID(v *int) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetLatestEvidenceID(*v)
	}
	return _u
}

// ClearLatestEvidenceID clears the value of the "latest_evidence_id" field.
func (_u *WorkProgramMilestoneUpdateOne) ClearLatestEvidenceID() *WorkProgramMilestoneUpdateOne {
	_u.mutation.ClearLatestEvidenceID()
	return _u
}

// SetEvidenceCount sets the "evidence_count" field.
func (_u *WorkProgramMilestoneUpdateOne) SetEvidenceCount(v int) *WorkProgramMilestoneUpdateOne {
	_u.mutation.ResetEvidenceCount()
	_u.mutation.SetEvidenceCount(v)
	return _u
}

// SetNillableEvidenceCount sets the "evidence_count" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableEvidenceCount(v *int) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetEvidenceCount(*v)
	}
	return _u
}

// AddEvidenceCount adds value to the "evidence_count" field.
func (_u *WorkProgramMilestoneUpdateOne) AddEvidenceCount(v int) *WorkProgramMilestoneUpdateOne {
	_u.mutation.AddEvidenceCount(v)
	return _u
}

// SetFreshnessState sets the "freshness_state" field.
func (_u *WorkProgramMilestoneUpdateOne) SetFreshnessState(v workprogrammilestone.FreshnessState) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetFreshnessState(v)
	return _u
}

// SetNillableFreshnessState sets the "freshness_state" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableFreshnessState(v *workprogrammilestone.FreshnessState) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetFreshnessState(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *WorkProgramMilestoneUpdateOne) SetVisibility(v workprogrammilestone.Visibility) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableVisibility(v *workprogrammilestone.Visibility) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetConfidence sets the "confidence" field.
func (_u *WorkProgramMilestoneUpdateOne) SetConfidence(v float64) *WorkProgramMilestoneUpdateOne {
	_u.mutation.ResetConfidence()
	_u.mutation.SetConfidence(v)
	return _u
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableConfidence(v *float64) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetConfidence(*v)
	}
	return _u
}

// AddConfidence adds value to the "confidence" field.
func (_u *WorkProgramMilestoneUpdateOne) AddConfidence(v float64) *WorkProgramMilestoneUpdateOne {
	_u.mutation.AddConfidence(v)
	return _u
}

// SetEventCount sets the "event_count" field.
func (_u *WorkProgramMilestoneUpdateOne) SetEventCount(v int) *WorkProgramMilestoneUpdateOne {
	_u.mutation.ResetEventCount()
	_u.mutation.SetEventCount(v)
	return _u
}

// SetNillableEventCount sets the "event_count" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableEventCount(v *int) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetEventCount(*v)
	}
	return _u
}

// AddEventCount adds value to the "event_count" field.
func (_u *WorkProgramMilestoneUpdateOne) AddEventCount(v int) *WorkProgramMilestoneUpdateOne {
	_u.mutation.AddEventCount(v)
	return _u
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_u *WorkProgramMilestoneUpdateOne) SetFirstSeenAt(v time.Time) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetFirstSeenAt(v)
	return _u
}

// SetNillableFirstSeenAt sets the "first_seen_at" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableFirstSeenAt(v *time.Time) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetFirstSeenAt(*v)
	}
	return _u
}

// ClearFirstSeenAt clears the value of the "first_seen_at" field.
func (_u *WorkProgramMilestoneUpdateOne) ClearFirstSeenAt() *WorkProgramMilestoneUpdateOne {
	_u.mutation.ClearFirstSeenAt()
	return _u
}

// SetLastActivityAt sets the "last_activity_at" field.
func (_u *WorkProgramMilestoneUpdateOne) SetLastActivityAt(v time.Time) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetLastActivityAt(v)
	return _u
}

// SetNillableLastActivityAt sets the "last_activity_at" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableLastActivityAt(v *time.Time) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetLastActivityAt(*v)
	}
	return _u
}

// ClearLastActivityAt clears the value of the "last_activity_at" field.
func (_u *WorkProgramMilestoneUpdateOne) ClearLastActivityAt() *WorkProgramMilestoneUpdateOne {
	_u.mutation.ClearLastActivityAt()
	return _u
}

// SetRankScore sets the "rank_score" field.
func (_u *WorkProgramMilestoneUpdateOne) SetRankScore(v float64) *WorkProgramMilestoneUpdateOne {
	_u.mutation.ResetRankScore()
	_u.mutation.SetRankScore(v)
	return _u
}

// SetNillableRankScore sets the "rank_score" field if the given value is not nil.
func (_u *WorkProgramMilestoneUpdateOne) SetNillableRankScore(v *float64) *WorkProgramMilestoneUpdateOne {
	if v != nil {
		_u.SetRankScore(*v)
	}
	return _u
}

// AddRankScore adds value to the "rank_score" field.
func (_u *WorkProgramMilestoneUpdateOne) AddRankScore(v float64) *WorkProgramMilestoneUpdateOne {
	_u.mutation.AddRankScore(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkProgramMilestoneUpdateOne) SetUpdatedAt(v time.Time) *WorkProgramMilestoneUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkstream sets the "workstream" edge to the Workstream entity.
func (_u *WorkProgramMilestoneUpdateOne) SetWorkstream(v *Workstream) *WorkProgramMilestoneUpdateOne {
	return _u.SetWorkstreamID(v.ID)
}

// SetPullRequest sets the "pull_request" edge to the PullRequest entity.
func (_u *WorkProgramMilestoneUpdateOne) SetPullRequest(v *PullRequest) *WorkProgramMilestoneUpdateOne {
	return _u.SetPullRequestID(v.ID)
}

// SetTicket sets the "ticket" edge to the Ticket entity.
func (_u *WorkProgramMilestoneUpdateOne) SetTicket(v *Ticket) *WorkProgramMilestoneUpdateOne {
	return _u.SetTicketID(v.ID)
}

// SetLatestEvidence sets the "latest_evidence" edge to the Evidence entity.
func (_u *WorkProgramMilestoneUpdateOne) SetLatestEvidence(v *Evidence) *WorkProgramMilestoneUpdateOne {
	return _u.SetLatestEvidenceID(v.ID)
}

// Mutation returns the WorkProgramMilestoneMutation object of the builder.
func (_u *WorkProgramMilestoneUpdateOne) Mutation() *WorkProgramMilestoneMutation {
	return _u.mutation
}

// ClearWorkstream clears the "workstream" edge to the Workstream entity.
func (_u *WorkProgramMilestoneUpdateOne) ClearWorkstream() *WorkProgramMilestoneUpdateOne {
	_u.mutation.ClearWorkstream()
	return _u
}

// ClearPullRequest clears the "pull_request" edge to the PullRequest entity.
func (_u *WorkProgramMilestoneUpdateOne) ClearPullRequest() *WorkProgramMilestoneUpdateOne {
	_u.mutation.ClearPullRequest()
	return _u
}

// ClearTicket clears the "ticket" edge to the Ticket entity.
func (_u *WorkProgramMilestoneUpdateOne) ClearTicket() *WorkProgramMilestoneUpdateOne {
	_u.mutation.ClearTicket()
	return _u
}

// ClearLatestEvidence clears the "latest_evidence" edge to the Evidence entity.
func (_u *WorkProgramMilestoneUpdateOne) ClearLatestEvidence() *WorkProgramMilestoneUpdateOne {
	_u.mutation.ClearLatestEvidence()
	return _u
}

// Where appends a list predicates to the WorkProgramMilestoneUpdate builder.
func (_u *WorkProgramMilestoneUpdateOne) Where(ps ...predicate.WorkProgramMilestone) *WorkProgramMilestoneUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkProgramMilestoneUpdateOne) Select(field string, fields ...string) *WorkProgramMilestoneUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkProgramMilestone entity.
func (_u *WorkProgramMilestoneUpdateOne) Save(ctx context.Context) (*WorkProgramMilestone, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkProgramMilestoneUpdateOne) SaveX(ctx context.Context) *WorkProgramMilestone {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkProgramMilestoneUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkProgramMilestoneUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkProgramMilestoneUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workprogrammilestone.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkProgramMilestoneUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := workprogrammilestone.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WorkstreamKey(); ok {
		if err := workprogrammilestone.WorkstreamKeyValidator(v); err != nil {
			return &ValidationError{Name: "workstream_key", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.workstream_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubjectKind(); ok {
		if err := workprogrammilestone.SubjectKindValidator(v); err != nil {
			return &ValidationError{Name: "subject_kind", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.subject_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubjectKey(); ok {
		if err := workprogrammilestone.SubjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "subject_key", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.subject_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MilestoneKind(); ok {
		if err := workprogrammilestone.MilestoneKindValidator(v); err != nil {
			return &ValidationError{Name: "milestone_kind", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.milestone_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MilestoneName(); ok {
		if err := workprogrammilestone.MilestoneNameValidator(v); err != nil {
			return &ValidationError{Name: "milestone_name", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.milestone_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MilestoneState(); ok {
		if err := workprogrammilestone.MilestoneStateValidator(v); err != nil {
			return &ValidationError{Name: "milestone_state", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.milestone_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CommitmentStrength(); ok {
		if err := workprogrammilestone.CommitmentStrengthValidator(v); err != nil {
			return &ValidationError{Name: "commitment_strength", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.commitment_strength": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClaimGateReason(); ok {
		if err := workprogrammilestone.ClaimGateReasonValidator(v); err != nil {
			return &ValidationError{Name: "claim_gate_reason", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.claim_gate_reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceField(); ok {
		if err := workprogrammilestone.SourceFieldValidator(v); err != nil {
			return &ValidationError{Name: "source_field", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.source_field": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FreshnessState(); ok {
		if err := workprogrammilestone.FreshnessStateValidator(v); err != nil {
			return &ValidationError{Name: "freshness_state", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.freshness_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visibility(); ok {
		if err := workprogrammilestone.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "WorkProgramMilestone.visibility": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkProgramMilestoneUpdateOne) sqlSave(ctx context.Context) (_node *WorkProgramMilestone, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workprogrammilestone.Table, workprogrammilestone.Columns, sqlgraph.NewFieldSpec(workprogrammilestone.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkProgramMilestone.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workprogrammilestone.FieldID)
		for _, f := range fields {
			if !workprogrammilestone.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workprogrammilestone.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(workprogrammilestone.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.WorkstreamKey(); ok {
		_spec.SetField(workprogrammilestone.FieldWorkstreamKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubjectKind(); ok {
		_spec.SetField(workprogrammilestone.FieldSubjectKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SubjectKey(); ok {
		_spec.SetField(workprogrammilestone.FieldSubjectKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.MilestoneKind(); ok {
		_spec.SetField(workprogrammilestone.FieldMilestoneKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.MilestoneName(); ok {
		_spec.SetField(workprogrammilestone.FieldMilestoneName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetDate(); ok {
		_spec.SetField(workprogrammilestone.FieldTargetDate, field.TypeTime, value)
	}
	if _u.mutation.TargetDateCleared() {
		_spec.ClearField(workprogrammilestone.FieldTargetDate, field.TypeTime)
	}
	if value, ok := _u.mutation.OutcomeDate(); ok {
		_spec.SetField(workprogrammilestone.FieldOutcomeDate, field.TypeTime, value)
	}
	if _u.mutation.OutcomeDateCleared() {
		_spec.ClearField(workprogrammilestone.FieldOutcomeDate, field.TypeTime)
	}
	if value, ok := _u.mutation.MilestoneState(); ok {
		_spec.SetField(workprogrammilestone.FieldMilestoneState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CommitmentStrength(); ok {
		_spec.SetField(workprogrammilestone.FieldCommitmentStrength, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DateClaimAllowed(); ok {
		_spec.SetField(workprogrammilestone.FieldDateClaimAllowed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DeliveryCommitmentAllowed(); ok {
		_spec.SetField(workprogrammilestone.FieldDeliveryCommitmentAllowed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ClaimGateReason(); ok {
		_spec.SetField(workprogrammilestone.FieldClaimGateReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceField(); ok {
		_spec.SetField(workprogrammilestone.FieldSourceField, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourcePayloadKey(); ok {
		_spec.SetField(workprogrammilestone.FieldSourcePayloadKey, field.TypeString, value)
	}
	if _u.mutation.SourcePayloadKeyCleared() {
		_spec.ClearField(workprogrammilestone.FieldSourcePayloadKey, field.TypeString)
	}
	if value, ok := _u.mutation.CapturedAt(); ok {
		_spec.SetField(workprogrammilestone.FieldCapturedAt, field.TypeTime, value)
	}
	if _u.mutation.CapturedAtCleared() {
		_spec.ClearField(workprogrammilestone.FieldCapturedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GeneratedAt(); ok {
		_spec.SetField(workprogrammilestone.FieldGeneratedAt, field.TypeTime, value)
	}
	if _u.mutation.GeneratedAtCleared() {
		_spec.ClearField(workprogrammilestone.FieldGeneratedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SourceSystem(); ok {
		_spec.SetField(workprogrammilestone.FieldSourceSystem, field.TypeString, value)
	}
	if _u.mutation.SourceSystemCleared() {
		_spec.ClearField(workprogrammilestone.FieldSourceSystem, field.TypeString)
	}
	if value, ok := _u.mutation.SourceInstance(); ok {
		_spec.SetField(workprogrammilestone.FieldSourceInstance, field.TypeString, value)
	}
	if _u.mutation.SourceInstanceCleared() {
		_spec.ClearField(workprogrammilestone.FieldSourceInstance, field.TypeString)
	}
	if value, ok := _u.mutation.ExternalKind(); ok {
		_spec.SetField(workprogrammilestone.FieldExternalKind, field.TypeString, value)
	}
	if _u.mutation.ExternalKindCleared() {
		_spec.ClearField(workprogrammilestone.FieldExternalKind, field.TypeString)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(workprogrammilestone.FieldExternalID, field.TypeString, value)
	}
	if _u.mutation.ExternalIDCleared() {
		_spec.ClearField(workprogrammilestone.FieldExternalID, field.TypeString)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(workprogrammilestone.FieldSourceURL, field.TypeString, value)
	}
	if _u.mutation.SourceURLCleared() {
		_spec.ClearField(workprogrammilestone.FieldSourceURL, field.TypeString)
	}
	if value, ok := _u.mutation.EvidenceCount(); ok {
		_spec.SetField(workprogrammilestone.FieldEvidenceCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEvidenceCount(); ok {
		_spec.AddField(workprogrammilestone.FieldEvidenceCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FreshnessState(); ok {
		_spec.SetField(workprogrammilestone.FieldFreshnessState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(workprogrammilestone.FieldVisibility, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Confidence(); ok {
		_spec.SetField(workprogrammilestone.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConfidence(); ok {
		_spec.AddField(workprogrammilestone.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EventCount(); ok {
		_spec.SetField(workprogrammilestone.FieldEventCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEventCount(); ok {
		_spec.AddField(workprogrammilestone.FieldEventCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FirstSeenAt(); ok {
		_spec.SetField(workprogrammilestone.FieldFirstSeenAt, field.TypeTime, value)
	}
	if _u.mutation.FirstSeenAtCleared() {
		_spec.ClearField(workprogrammilestone.FieldFirstSeenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastActivityAt(); ok {
		_spec.SetField(workprogrammilestone.FieldLastActivityAt, field.TypeTime, value)
	}
	if _u.mutation.LastActivityAtCleared() {
		_spec.ClearField(workprogrammilestone.FieldLastActivityAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RankScore(); ok {
		_spec.SetField(workprogrammilestone.FieldRankScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRankScore(); ok {
		_spec.AddField(workprogrammilestone.FieldRankScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workprogrammilestone.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.WorkstreamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workprogrammilestone.WorkstreamTable,
			Columns: []string{workprogrammilestone.WorkstreamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workstream.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkstreamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workprogrammilestone.WorkstreamTable,
			Columns: []string{workprogrammilestone.WorkstreamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workstream.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PullRequestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workprogrammilestone.PullRequestTable,
			Columns: []string{workprogrammilestone.PullRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pullrequest.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PullRequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workprogrammilestone.PullRequestTable,
			Columns: []string{workprogrammilestone.PullRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pullrequest.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TicketCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workprogrammilestone.TicketTable,
			Columns: []string{workprogrammilestone.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workprogrammilestone.TicketTable,
			Columns: []string{workprogrammilestone.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LatestEvidenceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workprogrammilestone.LatestEvidenceTable,
			Columns: []string{workprogrammilestone.LatestEvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LatestEvidenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workprogrammilestone.LatestEvidenceTable,
			Columns: []string{workprogrammilestone.LatestEvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WorkProgramMilestone{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workprogrammilestone.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
