// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cubicle/services/ontology-service/ent/worklens"
	"cubicle/services/ontology-service/ent/worklenswindow"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkLensWindowCreate is the builder for creating a WorkLensWindow entity.
type WorkLensWindowCreate struct {
	config
	mutation *WorkLensWindowMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKey sets the "key" field.
func (_c *WorkLensWindowCreate) SetKey(v string) *WorkLensWindowCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetWorkLensID sets the "work_lens_id" field.
func (_c *WorkLensWindowCreate) SetWorkLensID(v int) *WorkLensWindowCreate {
	_c.mutation.SetWorkLensID(v)
	return _c
}

// SetLensWindowKind sets the "lens_window_kind" field.
func (_c *WorkLensWindowCreate) SetLensWindowKind(v worklenswindow.LensWindowKind) *WorkLensWindowCreate {
	_c.mutation.SetLensWindowKind(v)
	return _c
}

// SetNillableLensWindowKind sets the "lens_window_kind" field if the given value is not nil.
func (_c *WorkLensWindowCreate) SetNillableLensWindowKind(v *worklenswindow.LensWindowKind) *WorkLensWindowCreate {
	if v != nil {
		_c.SetLensWindowKind(*v)
	}
	return _c
}

// SetWindowStartAt sets the "window_start_at" field.
func (_c *WorkLensWindowCreate) SetWindowStartAt(v time.Time) *WorkLensWindowCreate {
	_c.mutation.SetWindowStartAt(v)
	return _c
}

// SetNillableWindowStartAt sets the "window_start_at" field if the given value is not nil.
func (_c *WorkLensWindowCreate) SetNillableWindowStartAt(v *time.Time) *WorkLensWindowCreate {
	if v != nil {
		_c.SetWindowStartAt(*v)
	}
	return _c
}

// SetWindowEndAt sets the "window_end_at" field.
func (_c *WorkLensWindowCreate) SetWindowEndAt(v time.Time) *WorkLensWindowCreate {
	_c.mutation.SetWindowEndAt(v)
	return _c
}

// SetNillableWindowEndAt sets the "window_end_at" field if the given value is not nil.
func (_c *WorkLensWindowCreate) SetNillableWindowEndAt(v *time.Time) *WorkLensWindowCreate {
	if v != nil {
		_c.SetWindowEndAt(*v)
	}
	return _c
}

// SetRankStart sets the "rank_start" field.
func (_c *WorkLensWindowCreate) SetRankStart(v int) *WorkLensWindowCreate {
	_c.mutation.SetRankStart(v)
	return _c
}

// SetNillableRankStart sets the "rank_start" field if the given value is not nil.
func (_c *WorkLensWindowCreate) SetNillableRankStart(v *int) *WorkLensWindowCreate {
	if v != nil {
		_c.SetRankStart(*v)
	}
	return _c
}

// SetRankEnd sets the "rank_end" field.
func (_c *WorkLensWindowCreate) SetRankEnd(v int) *WorkLensWindowCreate {
	_c.mutation.SetRankEnd(v)
	return _c
}

// SetNillableRankEnd sets the "rank_end" field if the given value is not nil.
func (_c *WorkLensWindowCreate) SetNillableRankEnd(v *int) *WorkLensWindowCreate {
	if v != nil {
		_c.SetRankEnd(*v)
	}
	return _c
}

// SetCheckpoint sets the "checkpoint" field.
func (_c *WorkLensWindowCreate) SetCheckpoint(v string) *WorkLensWindowCreate {
	_c.mutation.SetCheckpoint(v)
	return _c
}

// SetNillableCheckpoint sets the "checkpoint" field if the given value is not nil.
func (_c *WorkLensWindowCreate) SetNillableCheckpoint(v *string) *WorkLensWindowCreate {
	if v != nil {
		_c.SetCheckpoint(*v)
	}
	return _c
}

// SetResultCount sets the "result_count" field.
func (_c *WorkLensWindowCreate) SetResultCount(v int) *WorkLensWindowCreate {
	_c.mutation.SetResultCount(v)
	return _c
}

// SetNillableResultCount sets the "result_count" field if the given value is not nil.
func (_c *WorkLensWindowCreate) SetNillableResultCount(v *int) *WorkLensWindowCreate {
	if v != nil {
		_c.SetResultCount(*v)
	}
	return _c
}

// SetIsComplete sets the "is_complete" field.
func (_c *WorkLensWindowCreate) SetIsComplete(v bool) *WorkLensWindowCreate {
	_c.mutation.SetIsComplete(v)
	return _c
}

// SetNillableIsComplete sets the "is_complete" field if the given value is not nil.
func (_c *WorkLensWindowCreate) SetNillableIsComplete(v *bool) *WorkLensWindowCreate {
	if v != nil {
		_c.SetIsComplete(*v)
	}
	return _c
}

// SetLastIndexedAt sets the "last_indexed_at" field.
func (_c *WorkLensWindowCreate) SetLastIndexedAt(v time.Time) *WorkLensWindowCreate {
	_c.mutation.SetLastIndexedAt(v)
	return _c
}

// SetNillableLastIndexedAt sets the "last_indexed_at" field if the given value is not nil.
func (_c *WorkLensWindowCreate) SetNillableLastIndexedAt(v *time.Time) *WorkLensWindowCreate {
	if v != nil {
		_c.SetLastIndexedAt(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *WorkLensWindowCreate) SetSource(v string) *WorkLensWindowCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *WorkLensWindowCreate) SetNillableSource(v *string) *WorkLensWindowCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetSourceInstance sets the "source_instance" field.
func (_c *WorkLensWindowCreate) SetSourceInstance(v string) *WorkLensWindowCreate {
	_c.mutation.SetSourceInstance(v)
	return _c
}

// SetNillableSourceInstance sets the "source_instance" field if the given value is not nil.
func (_c *WorkLensWindowCreate) SetNillableSourceInstance(v *string) *WorkLensWindowCreate {
	if v != nil {
		_c.SetSourceInstance(*v)
	}
	return _c
}

// SetExternalID sets the "external_id" field.
func (_c *WorkLensWindowCreate) SetExternalID(v string) *WorkLensWindowCreate {
	_c.mutation.SetExternalID(v)
	return _c
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_c *WorkLensWindowCreate) SetNillableExternalID(v *string) *WorkLensWindowCreate {
	if v != nil {
		_c.SetExternalID(*v)
	}
	return _c
}

// SetSourceURL sets the "source_url" field.
func (_c *WorkLensWindowCreate) SetSourceURL(v string) *WorkLensWindowCreate {
	_c.mutation.SetSourceURL(v)
	return _c
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_c *WorkLensWindowCreate) SetNillableSourceURL(v *string) *WorkLensWindowCreate {
	if v != nil {
		_c.SetSourceURL(*v)
	}
	return _c
}

// SetEventCount sets the "event_count" field.
func (_c *WorkLensWindowCreate) SetEventCount(v int) *WorkLensWindowCreate {
	_c.mutation.SetEventCount(v)
	return _c
}

// SetNillableEventCount sets the "event_count" field if the given value is not nil.
func (_c *WorkLensWindowCreate) SetNillableEventCount(v *int) *WorkLensWindowCreate {
	if v != nil {
		_c.SetEventCount(*v)
	}
	return _c
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_c *WorkLensWindowCreate) SetFirstSeenAt(v time.Time) *WorkLensWindowCreate {
	_c.mutation.SetFirstSeenAt(v)
	return _c
}

// SetNillableFirstSeenAt sets the "first_seen_at" field if the given value is not nil.
func (_c *WorkLensWindowCreate) SetNillableFirstSeenAt(v *time.Time) *WorkLensWindowCreate {
	if v != nil {
		_c.SetFirstSeenAt(*v)
	}
	return _c
}

// SetLastActivityAt sets the "last_activity_at" field.
func (_c *WorkLensWindowCreate) SetLastActivityAt(v time.Time) *WorkLensWindowCreate {
	_c.mutation.SetLastActivityAt(v)
	return _c
}

// SetNillableLastActivityAt sets the "last_activity_at" field if the given value is not nil.
func (_c *WorkLensWindowCreate) SetNillableLastActivityAt(v *time.Time) *WorkLensWindowCreate {
	if v != nil {
		_c.SetLastActivityAt(*v)
	}
	return _c
}

// SetRankScore sets the "rank_score" field.
func (_c *WorkLensWindowCreate) SetRankScore(v float64) *WorkLensWindowCreate {
	_c.mutation.SetRankScore(v)
	return _c
}

// SetNillableRankScore sets the "rank_score" field if the given value is not nil.
func (_c *WorkLensWindowCreate) SetNillableRankScore(v *float64) *WorkLensWindowCreate {
	if v != nil {
		_c.SetRankScore(*v)
	}
	return _c
}

// SetFreshnessState sets the "freshness_state" field.
func (_c *WorkLensWindowCreate) SetFreshnessState(v worklenswindow.FreshnessState) *WorkLensWindowCreate {
	_c.mutation.SetFreshnessState(v)
	return _c
}

// SetNillableFreshnessState sets the "freshness_state" field if the given value is not nil.
func (_c *WorkLensWindowCreate) SetNillableFreshnessState(v *worklenswindow.FreshnessState) *WorkLensWindowCreate {
	if v != nil {
		_c.SetFreshnessState(*v)
	}
	return _c
}

// SetVisibility sets the "visibility" field.
func (_c *WorkLensWindowCreate) SetVisibility(v worklenswindow.Visibility) *WorkLensWindowCreate {
	_c.mutation.SetVisibility(v)
	return _c
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_c *WorkLensWindowCreate) SetNillableVisibility(v *worklenswindow.Visibility) *WorkLensWindowCreate {
	if v != nil {
		_c.SetVisibility(*v)
	}
	return _c
}

// SetConfidence sets the "confidence" field.
func (_c *WorkLensWindowCreate) SetConfidence(v float64) *WorkLensWindowCreate {
	_c.mutation.SetConfidence(v)
	return _c
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_c *WorkLensWindowCreate) SetNillableConfidence(v *float64) *WorkLensWindowCreate {
	if v != nil {
		_c.SetConfidence(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WorkLensWindowCreate) SetCreatedAt(v time.Time) *WorkLensWindowCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WorkLensWindowCreate) SetNillableCreatedAt(v *time.Time) *WorkLensWindowCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WorkLensWindowCreate) SetUpdatedAt(v time.Time) *WorkLensWindowCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WorkLensWindowCreate) SetNillableUpdatedAt(v *time.Time) *WorkLensWindowCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetLensID sets the "lens" edge to the WorkLens entity by ID.
func (_c *WorkLensWindowCreate) SetLensID(id int) *WorkLensWindowCreate {
	_c.mutation.SetLensID(id)
	return _c
}

// SetLens sets the "lens" edge to the WorkLens entity.
func (_c *WorkLensWindowCreate) SetLens(v *WorkLens) *WorkLensWindowCreate {
	return _c.SetLensID(v.ID)
}

// Mutation returns the WorkLensWindowMutation object of the builder.
func (_c *WorkLensWindowCreate) Mutation() *WorkLensWindowMutation {
	return _c.mutation
}

// Save creates the WorkLensWindow in the database.
func (_c *WorkLensWindowCreate) Save(ctx context.Context) (*WorkLensWindow, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WorkLensWindowCreate) SaveX(ctx context.Context) *WorkLensWindow {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkLensWindowCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkLensWindowCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WorkLensWindowCreate) defaults() {
	if _, ok := _c.mutation.LensWindowKind(); !ok {
		v := worklenswindow.DefaultLensWindowKind
		_c.mutation.SetLensWindowKind(v)
	}
	if _, ok := _c.mutation.ResultCount(); !ok {
		v := worklenswindow.DefaultResultCount
		_c.mutation.SetResultCount(v)
	}
	if _, ok := _c.mutation.IsComplete(); !ok {
		v := worklenswindow.DefaultIsComplete
		_c.mutation.SetIsComplete(v)
	}
	if _, ok := _c.mutation.EventCount(); !ok {
		v := worklenswindow.DefaultEventCount
		_c.mutation.SetEventCount(v)
	}
	if _, ok := _c.mutation.RankScore(); !ok {
		v := worklenswindow.DefaultRankScore
		_c.mutation.SetRankScore(v)
	}
	if _, ok := _c.mutation.FreshnessState(); !ok {
		v := worklenswindow.DefaultFreshnessState
		_c.mutation.SetFreshnessState(v)
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		v := worklenswindow.DefaultVisibility
		_c.mutation.SetVisibility(v)
	}
	if _, ok := _c.mutation.Confidence(); !ok {
		v := worklenswindow.DefaultConfidence
		_c.mutation.SetConfidence(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := worklenswindow.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := worklenswindow.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WorkLensWindowCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "WorkLensWindow.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := worklenswindow.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "WorkLensWindow.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WorkLensID(); !ok {
		return &ValidationError{Name: "work_lens_id", err: errors.New(`ent: missing required field "WorkLensWindow.work_lens_id"`)}
	}
	if _, ok := _c.mutation.LensWindowKind(); !ok {
		return &ValidationError{Name: "lens_window_kind", err: errors.New(`ent: missing required field "WorkLensWindow.lens_window_kind"`)}
	}
	if v, ok := _c.mutation.LensWindowKind(); ok {
		if err := worklenswindow.LensWindowKindValidator(v); err != nil {
			return &ValidationError{Name: "lens_window_kind", err: fmt.Errorf(`ent: validator failed for field "WorkLensWindow.lens_window_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResultCount(); !ok {
		return &ValidationError{Name: "result_count", err: errors.New(`ent: missing required field "WorkLensWindow.result_count"`)}
	}
	if _, ok := _c.mutation.IsComplete(); !ok {
		return &ValidationError{Name: "is_complete", err: errors.New(`ent: missing required field "WorkLensWindow.is_complete"`)}
	}
	if _, ok := _c.mutation.EventCount(); !ok {
		return &ValidationError{Name: "event_count", err: errors.New(`ent: missing required field "WorkLensWindow.event_count"`)}
	}
	if _, ok := _c.mutation.RankScore(); !ok {
		return &ValidationError{Name: "rank_score", err: errors.New(`ent: missing required field "WorkLensWindow.rank_score"`)}
	}
	if _, ok := _c.mutation.FreshnessState(); !ok {
		return &ValidationError{Name: "freshness_state", err: errors.New(`ent: missing required field "WorkLensWindow.freshness_state"`)}
	}
	if v, ok := _c.mutation.FreshnessState(); ok {
		if err := worklenswindow.FreshnessStateValidator(v); err != nil {
			return &ValidationError{Name: "freshness_state", err: fmt.Errorf(`ent: validator failed for field "WorkLensWindow.freshness_state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		return &ValidationError{Name: "visibility", err: errors.New(`ent: missing required field "WorkLensWindow.visibility"`)}
	}
	if v, ok := _c.mutation.Visibility(); ok {
		if err := worklenswindow.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "WorkLensWindow.visibility": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Confidence(); !ok {
		return &ValidationError{Name: "confidence", err: errors.New(`ent: missing required field "WorkLensWindow.confidence"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WorkLensWindow.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WorkLensWindow.updated_at"`)}
	}
	if len(_c.mutation.LensIDs()) == 0 {
		return &ValidationError{Name: "lens", err: errors.New(`ent: missing required edge "WorkLensWindow.lens"`)}
	}
	return nil
}

func (_c *WorkLensWindowCreate) sqlSave(ctx context.Context) (*WorkLensWindow, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WorkLensWindowCreate) createSpec() (*WorkLensWindow, *sqlgraph.CreateSpec) {
	var (
		_node = &WorkLensWindow{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(worklenswindow.Table, sqlgraph.NewFieldSpec(worklenswindow.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(worklenswindow.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.LensWindowKind(); ok {
		_spec.SetField(worklenswindow.FieldLensWindowKind, field.TypeEnum, value)
		_node.LensWindowKind = value
	}
	if value, ok := _c.mutation.WindowStartAt(); ok {
		_spec.SetField(worklenswindow.FieldWindowStartAt, field.TypeTime, value)
		_node.WindowStartAt = value
	}
	if value, ok := _c.mutation.WindowEndAt(); ok {
		_spec.SetField(worklenswindow.FieldWindowEndAt, field.TypeTime, value)
		_node.WindowEndAt = value
	}
	if value, ok := _c.mutation.RankStart(); ok {
		_spec.SetField(worklenswindow.FieldRankStart, field.TypeInt, value)
		_node.RankStart = value
	}
	if value, ok := _c.mutation.RankEnd(); ok {
		_spec.SetField(worklenswindow.FieldRankEnd, field.TypeInt, value)
		_node.RankEnd = value
	}
	if value, ok := _c.mutation.Checkpoint(); ok {
		_spec.SetField(worklenswindow.FieldCheckpoint, field.TypeString, value)
		_node.Checkpoint = value
	}
	if value, ok := _c.mutation.ResultCount(); ok {
		_spec.SetField(worklenswindow.FieldResultCount, field.TypeInt, value)
		_node.ResultCount = value
	}
	if value, ok := _c.mutation.IsComplete(); ok {
		_spec.SetField(worklenswindow.FieldIsComplete, field.TypeBool, value)
		_node.IsComplete = value
	}
	if value, ok := _c.mutation.LastIndexedAt(); ok {
		_spec.SetField(worklenswindow.FieldLastIndexedAt, field.TypeTime, value)
		_node.LastIndexedAt = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(worklenswindow.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.SourceInstance(); ok {
		_spec.SetField(worklenswindow.FieldSourceInstance, field.TypeString, value)
		_node.SourceInstance = value
	}
	if value, ok := _c.mutation.ExternalID(); ok {
		_spec.SetField(worklenswindow.FieldExternalID, field.TypeString, value)
		_node.ExternalID = value
	}
	if value, ok := _c.mutation.SourceURL(); ok {
		_spec.SetField(worklenswindow.FieldSourceURL, field.TypeString, value)
		_node.SourceURL = value
	}
	if value, ok := _c.mutation.EventCount(); ok {
		_spec.SetField(worklenswindow.FieldEventCount, field.TypeInt, value)
		_node.EventCount = value
	}
	if value, ok := _c.mutation.FirstSeenAt(); ok {
		_spec.SetField(worklenswindow.FieldFirstSeenAt, field.TypeTime, value)
		_node.FirstSeenAt = value
	}
	if value, ok := _c.mutation.LastActivityAt(); ok {
		_spec.SetField(worklenswindow.FieldLastActivityAt, field.TypeTime, value)
		_node.LastActivityAt = value
	}
	if value, ok := _c.mutation.RankScore(); ok {
		_spec.SetField(worklenswindow.FieldRankScore, field.TypeFloat64, value)
		_node.RankScore = value
	}
	if value, ok := _c.mutation.FreshnessState(); ok {
		_spec.SetField(worklenswindow.FieldFreshnessState, field.TypeEnum, value)
		_node.FreshnessState = value
	}
	if value, ok := _c.mutation.Visibility(); ok {
		_spec.SetField(worklenswindow.FieldVisibility, field.TypeEnum, value)
		_node.Visibility = value
	}
	if value, ok := _c.mutation.Confidence(); ok {
		_spec.SetField(worklenswindow.FieldConfidence, field.TypeFloat64, value)
		_node.Confidence = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(worklenswindow.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(worklenswindow.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.LensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   worklenswindow.LensTable,
			Columns: []string{worklenswindow.LensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(worklens.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WorkLensID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WorkLensWindow.Create().
//		SetKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WorkLensWindowUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (_c *WorkLensWindowCreate) OnConflict(opts ...sql.ConflictOption) *WorkLensWindowUpsertOne {
	_c.conflict = opts
	return &WorkLensWindowUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WorkLensWindow.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WorkLensWindowCreate) OnConflictColumns(columns ...string) *WorkLensWindowUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WorkLensWindowUpsertOne{
		create: _c,
	}
}

type (
	// WorkLensWindowUpsertOne is the builder for "upsert"-ing
	//  one WorkLensWindow node.
	WorkLensWindowUpsertOne struct {
		create *WorkLensWindowCreate
	}

	// WorkLensWindowUpsert is the "OnConflict" setter.
	WorkLensWindowUpsert struct {
		*sql.UpdateSet
	}
)

// SetKey sets the "key" field.
func (u *WorkLensWindowUpsert) SetKey(v string) *WorkLensWindowUpsert {
	u.Set(worklenswindow.FieldKey, v)
	return u
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *WorkLensWindowUpsert) UpdateKey() *WorkLensWindowUpsert {
	u.SetExcluded(worklenswindow.FieldKey)
	return u
}

// SetLensWindowKind sets the "lens_window_kind" field.
func (u *WorkLensWindowUpsert) SetLensWindowKind(v worklenswindow.LensWindowKind) *WorkLensWindowUpsert {
	u.Set(worklenswindow.FieldLensWindowKind, v)
	return u
}

// UpdateLensWindowKind sets the "lens_window_kind" field to the value that was provided on create.
func (u *WorkLensWindowUpsert) UpdateLensWindowKind() *WorkLensWindowUpsert {
	u.SetExcluded(worklenswindow.FieldLensWindowKind)
	return u
}

// SetWindowStartAt sets the "window_start_at" field.
func (u *WorkLensWindowUpsert) SetWindowStartAt(v time.Time) *WorkLensWindowUpsert {
	u.Set(worklenswindow.FieldWindowStartAt, v)
	return u
}

// UpdateWindowStartAt sets the "window_start_at" field to the value that was provided on create.
func (u *WorkLensWindowUpsert) UpdateWindowStartAt() *WorkLensWindowUpsert {
	u.SetExcluded(worklenswindow.FieldWindowStartAt)
	return u
}

// ClearWindowStartAt clears the value of the "window_start_at" field.
func (u *WorkLensWindowUpsert) ClearWindowStartAt() *WorkLensWindowUpsert {
	u.SetNull(worklenswindow.FieldWindowStartAt)
	return u
}

// SetWindowEndAt sets the "window_end_at" field.
func (u *WorkLensWindowUpsert) SetWindowEndAt(v time.Time) *WorkLensWindowUpsert {
	u.Set(worklenswindow.FieldWindowEndAt, v)
	return u
}

// UpdateWindowEndAt sets the "window_end_at" field to the value that was provided on create.
func (u *WorkLensWindowUpsert) UpdateWindowEndAt() *WorkLensWindowUpsert {
	u.SetExcluded(worklenswindow.FieldWindowEndAt)
	return u
}

// ClearWindowEndAt clears the value of the "window_end_at" field.
func (u *WorkLensWindowUpsert) ClearWindowEndAt() *WorkLensWindowUpsert {
	u.SetNull(worklenswindow.FieldWindowEndAt)
	return u
}

// SetRankStart sets the "rank_start" field.
func (u *WorkLensWindowUpsert) SetRankStart(v int) *WorkLensWindowUpsert {
	u.Set(worklenswindow.FieldRankStart, v)
	return u
}

// UpdateRankStart sets the "rank_start" field to the value that was provided on create.
func (u *WorkLensWindowUpsert) UpdateRankStart() *WorkLensWindowUpsert {
	u.SetExcluded(worklenswindow.FieldRankStart)
	return u
}

// AddRankStart adds v to the "rank_start" field.
func (u *WorkLensWindowUpsert) AddRankStart(v int) *WorkLensWindowUpsert {
	u.Add(worklenswindow.FieldRankStart, v)
	return u
}

// ClearRankStart clears the value of the "rank_start" field.
func (u *WorkLensWindowUpsert) ClearRankStart() *WorkLensWindowUpsert {
	u.SetNull(worklenswindow.FieldRankStart)
	return u
}

// SetRankEnd sets the "rank_end" field.
func (u *WorkLensWindowUpsert) SetRankEnd(v int) *WorkLensWindowUpsert {
	u.Set(worklenswindow.FieldRankEnd, v)
	return u
}

// UpdateRankEnd sets the "rank_end" field to the value that was provided on create.
func (u *WorkLensWindowUpsert) UpdateRankEnd() *WorkLensWindowUpsert {
	u.SetExcluded(worklenswindow.FieldRankEnd)
	return u
}

// AddRankEnd adds v to the "rank_end" field.
func (u *WorkLensWindowUpsert) AddRankEnd(v int) *WorkLensWindowUpsert {
	u.Add(worklenswindow.FieldRankEnd, v)
	return u
}

// ClearRankEnd clears the value of the "rank_end" field.
func (u *WorkLensWindowUpsert) ClearRankEnd() *WorkLensWindowUpsert {
	u.SetNull(worklenswindow.FieldRankEnd)
	return u
}

// SetCheckpoint sets the "checkpoint" field.
func (u *WorkLensWindowUpsert) SetCheckpoint(v string) *WorkLensWindowUpsert {
	u.Set(worklenswindow.FieldCheckpoint, v)
	return u
}

// UpdateCheckpoint sets the "checkpoint" field to the value that was provided on create.
func (u *WorkLensWindowUpsert) UpdateCheckpoint() *WorkLensWindowUpsert {
	u.SetExcluded(worklenswindow.FieldCheckpoint)
	return u
}

// ClearCheckpoint clears the value of the "checkpoint" field.
func (u *WorkLensWindowUpsert) ClearCheckpoint() *WorkLensWindowUpsert {
	u.SetNull(worklenswindow.FieldCheckpoint)
	return u
}

// SetResultCount sets the "result_count" field.
func (u *WorkLensWindowUpsert) SetResultCount(v int) *WorkLensWindowUpsert {
	u.Set(worklenswindow.FieldResultCount, v)
	return u
}

// UpdateResultCount sets the "result_count" field to the value that was provided on create.
func (u *WorkLensWindowUpsert) UpdateResultCount() *WorkLensWindowUpsert {
	u.SetExcluded(worklenswindow.FieldResultCount)
	return u
}

// AddResultCount adds v to the "result_count" field.
func (u *WorkLensWindowUpsert) AddResultCount(v int) *WorkLensWindowUpsert {
	u.Add(worklenswindow.FieldResultCount, v)
	return u
}

// SetIsComplete sets the "is_complete" field.
func (u *WorkLensWindowUpsert) SetIsComplete(v bool) *WorkLensWindowUpsert {
	u.Set(worklenswindow.FieldIsComplete, v)
	return u
}

// UpdateIsComplete sets the "is_complete" field to the value that was provided on create.
func (u *WorkLensWindowUpsert) UpdateIsComplete() *WorkLensWindowUpsert {
	u.SetExcluded(worklenswindow.FieldIsComplete)
	return u
}

// SetLastIndexedAt sets the "last_indexed_at" field.
func (u *WorkLensWindowUpsert) SetLastIndexedAt(v time.Time) *WorkLensWindowUpsert {
	u.Set(worklenswindow.FieldLastIndexedAt, v)
	return u
}

// UpdateLastIndexedAt sets the "last_indexed_at" field to the value that was provided on create.
func (u *WorkLensWindowUpsert) UpdateLastIndexedAt() *WorkLensWindowUpsert {
	u.SetExcluded(worklenswindow.FieldLastIndexedAt)
	return u
}

// ClearLastIndexedAt clears the value of the "last_indexed_at" field.
func (u *WorkLensWindowUpsert) ClearLastIndexedAt() *WorkLensWindowUpsert {
	u.SetNull(worklenswindow.FieldLastIndexedAt)
	return u
}

// SetSource sets the "source" field.
func (u *WorkLensWindowUpsert) SetSource(v string) *WorkLensWindowUpsert {
	u.Set(worklenswindow.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *WorkLensWindowUpsert) UpdateSource() *WorkLensWindowUpsert {
	u.SetExcluded(worklenswindow.FieldSource)
	return u
}

// ClearSource clears the value of the "source" field.
func (u *WorkLensWindowUpsert) ClearSource() *WorkLensWindowUpsert {
	u.SetNull(worklenswindow.FieldSource)
	return u
}

// SetSourceInstance sets the "source_instance" field.
func (u *WorkLensWindowUpsert) SetSourceInstance(v string) *WorkLensWindowUpsert {
	u.Set(worklenswindow.FieldSourceInstance, v)
	return u
}

// UpdateSourceInstance sets the "source_instance" field to the value that was provided on create.
func (u *WorkLensWindowUpsert) UpdateSourceInstance() *WorkLensWindowUpsert {
	u.SetExcluded(worklenswindow.FieldSourceInstance)
	return u
}

// ClearSourceInstance clears the value of the "source_instance" field.
func (u *WorkLensWindowUpsert) ClearSourceInstance() *WorkLensWindowUpsert {
	u.SetNull(worklenswindow.FieldSourceInstance)
	return u
}

// SetExternalID sets the "external_id" field.
func (u *WorkLensWindowUpsert) SetExternalID(v string) *WorkLensWindowUpsert {
	u.Set(worklenswindow.FieldExternalID, v)
	return u
}

// UpdateExternalID sets the "external_id" field to the value that was provided on create.
func (u *WorkLensWindowUpsert) UpdateExternalID() *WorkLensWindowUpsert {
	u.SetExcluded(worklenswindow.FieldExternalID)
	return u
}

// ClearExternalID clears the value of the "external_id" field.
func (u *WorkLensWindowUpsert) ClearExternalID() *WorkLensWindowUpsert {
	u.SetNull(worklenswindow.FieldExternalID)
	return u
}

// SetSourceURL sets the "source_url" field.
func (u *WorkLensWindowUpsert) SetSourceURL(v string) *WorkLensWindowUpsert {
	u.Set(worklenswindow.FieldSourceURL, v)
	return u
}

// UpdateSourceURL sets the "source_url" field to the value that was provided on create.
func (u *WorkLensWindowUpsert) UpdateSourceURL() *WorkLensWindowUpsert {
	u.SetExcluded(worklenswindow.FieldSourceURL)
	return u
}

// ClearSourceURL clears the value of the "source_url" field.
func (u *WorkLensWindowUpsert) ClearSourceURL() *WorkLensWindowUpsert {
	u.SetNull(worklenswindow.FieldSourceURL)
	return u
}

// SetEventCount sets the "event_count" field.
func (u *WorkLensWindowUpsert) SetEventCount(v int) *WorkLensWindowUpsert {
	u.Set(worklenswindow.FieldEventCount, v)
	return u
}

// UpdateEventCount sets the "event_count" field to the value that was provided on create.
func (u *WorkLensWindowUpsert) UpdateEventCount() *WorkLensWindowUpsert {
	u.SetExcluded(worklenswindow.FieldEventCount)
	return u
}

// AddEventCount adds v to the "event_count" field.
func (u *WorkLensWindowUpsert) AddEventCount(v int) *WorkLensWindowUpsert {
	u.Add(worklenswindow.FieldEventCount, v)
	return u
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (u *WorkLensWindowUpsert) SetFirstSeenAt(v time.Time) *WorkLensWindowUpsert {
	u.Set(worklenswindow.FieldFirstSeenAt, v)
	return u
}

// UpdateFirstSeenAt sets the "first_seen_at" field to the value that was provided on create.
func (u *WorkLensWindowUpsert) UpdateFirstSeenAt() *WorkLensWindowUpsert {
	u.SetExcluded(worklenswindow.FieldFirstSeenAt)
	return u
}

// ClearFirstSeenAt clears the value of the "first_seen_at" field.
func (u *WorkLensWindowUpsert) ClearFirstSeenAt() *WorkLensWindowUpsert {
	u.SetNull(worklenswindow.FieldFirstSeenAt)
	return u
}

// SetLastActivityAt sets the "last_activity_at" field.
func (u *WorkLensWindowUpsert) SetLastActivityAt(v time.Time) *WorkLensWindowUpsert {
	u.Set(worklenswindow.FieldLastActivityAt, v)
	return u
}

// UpdateLastActivityAt sets the "last_activity_at" field to the value that was provided on create.
func (u *WorkLensWindowUpsert) UpdateLastActivityAt() *WorkLensWindowUpsert {
	u.SetExcluded(worklenswindow.FieldLastActivityAt)
	return u
}

// ClearLastActivityAt clears the value of the "last_activity_at" field.
func (u *WorkLensWindowUpsert) ClearLastActivityAt() *WorkLensWindowUpsert {
	u.SetNull(worklenswindow.FieldLastActivityAt)
	return u
}

// SetRankScore sets the "rank_score" field.
func (u *WorkLensWindowUpsert) SetRankScore(v float64) *WorkLensWindowUpsert {
	u.Set(worklenswindow.FieldRankScore, v)
	return u
}

// UpdateRankScore sets the "rank_score" field to the value that was provided on create.
func (u *WorkLensWindowUpsert) UpdateRankScore() *WorkLensWindowUpsert {
	u.SetExcluded(worklenswindow.FieldRankScore)
	return u
}

// AddRankScore adds v to the "rank_score" field.
func (u *WorkLensWindowUpsert) AddRankScore(v float64) *WorkLensWindowUpsert {
	u.Add(worklenswindow.FieldRankScore, v)
	return u
}

// SetFreshnessState sets the "freshness_state" field.
func (u *WorkLensWindowUpsert) SetFreshnessState(v worklenswindow.FreshnessState) *WorkLensWindowUpsert {
	u.Set(worklenswindow.FieldFreshnessState, v)
	return u
}

// UpdateFreshnessState sets the "freshness_state" field to the value that was provided on create.
func (u *WorkLensWindowUpsert) UpdateFreshnessState() *WorkLensWindowUpsert {
	u.SetExcluded(worklenswindow.FieldFreshnessState)
	return u
}

// SetVisibility sets the "visibility" field.
func (u *WorkLensWindowUpsert) SetVisibility(v worklenswindow.Visibility) *WorkLensWindowUpsert {
	u.Set(worklenswindow.FieldVisibility, v)
	return u
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *WorkLensWindowUpsert) UpdateVisibility() *WorkLensWindowUpsert {
	u.SetExcluded(worklenswindow.FieldVisibility)
	return u
}

// SetConfidence sets the "confidence" field.
func (u *WorkLensWindowUpsert) SetConfidence(v float64) *WorkLensWindowUpsert {
	u.Set(worklenswindow.FieldConfidence, v)
	return u
}

// UpdateConfidence sets the "confidence" field to the value that was provided on create.
func (u *WorkLensWindowUpsert) UpdateConfidence() *WorkLensWindowUpsert {
	u.SetExcluded(worklenswindow.FieldConfidence)
	return u
}

// AddConfidence adds v to the "confidence" field.
func (u *WorkLensWindowUpsert) AddConfidence(v float64) *WorkLensWindowUpsert {
	u.Add(worklenswindow.FieldConfidence, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WorkLensWindowUpsert) SetUpdatedAt(v time.Time) *WorkLensWindowUpsert {
	u.Set(worklenswindow.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WorkLensWindowUpsert) UpdateUpdatedAt() *WorkLensWindowUpsert {
	u.SetExcluded(worklenswindow.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.WorkLensWindow.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WorkLensWindowUpsertOne) UpdateNewValues() *WorkLensWindowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.WorkLensID(); exists {
			s.SetIgnore(worklenswindow.FieldWorkLensID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(worklenswindow.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WorkLensWindow.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WorkLensWindowUpsertOne) Ignore() *WorkLensWindowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WorkLensWindowUpsertOne) DoNothing() *WorkLensWindowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WorkLensWindowCreate.OnConflict
// documentation for more info.
func (u *WorkLensWindowUpsertOne) Update(set func(*WorkLensWindowUpsert)) *WorkLensWindowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WorkLensWindowUpsert{UpdateSet: update})
	}))
	return u
}

// SetKey sets the "key" field.
func (u *WorkLensWindowUpsertOne) SetKey(v string) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *WorkLensWindowUpsertOne) UpdateKey() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateKey()
	})
}

// SetLensWindowKind sets the "lens_window_kind" field.
func (u *WorkLensWindowUpsertOne) SetLensWindowKind(v worklenswindow.LensWindowKind) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetLensWindowKind(v)
	})
}

// UpdateLensWindowKind sets the "lens_window_kind" field to the value that was provided on create.
func (u *WorkLensWindowUpsertOne) UpdateLensWindowKind() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateLensWindowKind()
	})
}

// SetWindowStartAt sets the "window_start_at" field.
func (u *WorkLensWindowUpsertOne) SetWindowStartAt(v time.Time) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetWindowStartAt(v)
	})
}

// UpdateWindowStartAt sets the "window_start_at" field to the value that was provided on create.
func (u *WorkLensWindowUpsertOne) UpdateWindowStartAt() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateWindowStartAt()
	})
}

// ClearWindowStartAt clears the value of the "window_start_at" field.
func (u *WorkLensWindowUpsertOne) ClearWindowStartAt() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearWindowStartAt()
	})
}

// SetWindowEndAt sets the "window_end_at" field.
func (u *WorkLensWindowUpsertOne) SetWindowEndAt(v time.Time) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetWindowEndAt(v)
	})
}

// UpdateWindowEndAt sets the "window_end_at" field to the value that was provided on create.
func (u *WorkLensWindowUpsertOne) UpdateWindowEndAt() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateWindowEndAt()
	})
}

// ClearWindowEndAt clears the value of the "window_end_at" field.
func (u *WorkLensWindowUpsertOne) ClearWindowEndAt() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearWindowEndAt()
	})
}

// SetRankStart sets the "rank_start" field.
func (u *WorkLensWindowUpsertOne) SetRankStart(v int) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetRankStart(v)
	})
}

// AddRankStart adds v to the "rank_start" field.
func (u *WorkLensWindowUpsertOne) AddRankStart(v int) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.AddRankStart(v)
	})
}

// UpdateRankStart sets the "rank_start" field to the value that was provided on create.
func (u *WorkLensWindowUpsertOne) UpdateRankStart() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateRankStart()
	})
}

// ClearRankStart clears the value of the "rank_start" field.
func (u *WorkLensWindowUpsertOne) ClearRankStart() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearRankStart()
	})
}

// SetRankEnd sets the "rank_end" field.
func (u *WorkLensWindowUpsertOne) SetRankEnd(v int) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetRankEnd(v)
	})
}

// AddRankEnd adds v to the "rank_end" field.
func (u *WorkLensWindowUpsertOne) AddRankEnd(v int) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.AddRankEnd(v)
	})
}

// UpdateRankEnd sets the "rank_end" field to the value that was provided on create.
func (u *WorkLensWindowUpsertOne) UpdateRankEnd() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateRankEnd()
	})
}

// ClearRankEnd clears the value of the "rank_end" field.
func (u *WorkLensWindowUpsertOne) ClearRankEnd() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearRankEnd()
	})
}

// SetCheckpoint sets the "checkpoint" field.
func (u *WorkLensWindowUpsertOne) SetCheckpoint(v string) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetCheckpoint(v)
	})
}

// UpdateCheckpoint sets the "checkpoint" field to the value that was provided on create.
func (u *WorkLensWindowUpsertOne) UpdateCheckpoint() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateCheckpoint()
	})
}

// ClearCheckpoint clears the value of the "checkpoint" field.
func (u *WorkLensWindowUpsertOne) ClearCheckpoint() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearCheckpoint()
	})
}

// SetResultCount sets the "result_count" field.
func (u *WorkLensWindowUpsertOne) SetResultCount(v int) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetResultCount(v)
	})
}

// AddResultCount adds v to the "result_count" field.
func (u *WorkLensWindowUpsertOne) AddResultCount(v int) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.AddResultCount(v)
	})
}

// UpdateResultCount sets the "result_count" field to the value that was provided on create.
func (u *WorkLensWindowUpsertOne) UpdateResultCount() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateResultCount()
	})
}

// SetIsComplete sets the "is_complete" field.
func (u *WorkLensWindowUpsertOne) SetIsComplete(v bool) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetIsComplete(v)
	})
}

// UpdateIsComplete sets the "is_complete" field to the value that was provided on create.
func (u *WorkLensWindowUpsertOne) UpdateIsComplete() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateIsComplete()
	})
}

// SetLastIndexedAt sets the "last_indexed_at" field.
func (u *WorkLensWindowUpsertOne) SetLastIndexedAt(v time.Time) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetLastIndexedAt(v)
	})
}

// UpdateLastIndexedAt sets the "last_indexed_at" field to the value that was provided on create.
func (u *WorkLensWindowUpsertOne) UpdateLastIndexedAt() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateLastIndexedAt()
	})
}

// ClearLastIndexedAt clears the value of the "last_indexed_at" field.
func (u *WorkLensWindowUpsertOne) ClearLastIndexedAt() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearLastIndexedAt()
	})
}

// SetSource sets the "source" field.
func (u *WorkLensWindowUpsertOne) SetSource(v string) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *WorkLensWindowUpsertOne) UpdateSource() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateSource()
	})
}

// ClearSource clears the value of the "source" field.
func (u *WorkLensWindowUpsertOne) ClearSource() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearSource()
	})
}

// SetSourceInstance sets the "source_instance" field.
func (u *WorkLensWindowUpsertOne) SetSourceInstance(v string) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetSourceInstance(v)
	})
}

// UpdateSourceInstance sets the "source_instance" field to the value that was provided on create.
func (u *WorkLensWindowUpsertOne) UpdateSourceInstance() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateSourceInstance()
	})
}

// ClearSourceInstance clears the value of the "source_instance" field.
func (u *WorkLensWindowUpsertOne) ClearSourceInstance() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearSourceInstance()
	})
}

// SetExternalID sets the "external_id" field.
func (u *WorkLensWindowUpsertOne) SetExternalID(v string) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetExternalID(v)
	})
}

// UpdateExternalID sets the "external_id" field to the value that was provided on create.
func (u *WorkLensWindowUpsertOne) UpdateExternalID() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateExternalID()
	})
}

// ClearExternalID clears the value of the "external_id" field.
func (u *WorkLensWindowUpsertOne) ClearExternalID() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearExternalID()
	})
}

// SetSourceURL sets the "source_url" field.
func (u *WorkLensWindowUpsertOne) SetSourceURL(v string) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetSourceURL(v)
	})
}

// UpdateSourceURL sets the "source_url" field to the value that was provided on create.
func (u *WorkLensWindowUpsertOne) UpdateSourceURL() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateSourceURL()
	})
}

// ClearSourceURL clears the value of the "source_url" field.
func (u *WorkLensWindowUpsertOne) ClearSourceURL() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearSourceURL()
	})
}

// SetEventCount sets the "event_count" field.
func (u *WorkLensWindowUpsertOne) SetEventCount(v int) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetEventCount(v)
	})
}

// AddEventCount adds v to the "event_count" field.
func (u *WorkLensWindowUpsertOne) AddEventCount(v int) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.AddEventCount(v)
	})
}

// UpdateEventCount sets the "event_count" field to the value that was provided on create.
func (u *WorkLensWindowUpsertOne) UpdateEventCount() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateEventCount()
	})
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (u *WorkLensWindowUpsertOne) SetFirstSeenAt(v time.Time) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetFirstSeenAt(v)
	})
}

// UpdateFirstSeenAt sets the "first_seen_at" field to the value that was provided on create.
func (u *WorkLensWindowUpsertOne) UpdateFirstSeenAt() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateFirstSeenAt()
	})
}

// ClearFirstSeenAt clears the value of the "first_seen_at" field.
func (u *WorkLensWindowUpsertOne) ClearFirstSeenAt() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearFirstSeenAt()
	})
}

// SetLastActivityAt sets the "last_activity_at" field.
func (u *WorkLensWindowUpsertOne) SetLastActivityAt(v time.Time) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetLastActivityAt(v)
	})
}

// UpdateLastActivityAt sets the "last_activity_at" field to the value that was provided on create.
func (u *WorkLensWindowUpsertOne) UpdateLastActivityAt() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateLastActivityAt()
	})
}

// ClearLastActivityAt clears the value of the "last_activity_at" field.
func (u *WorkLensWindowUpsertOne) ClearLastActivityAt() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearLastActivityAt()
	})
}

// SetRankScore sets the "rank_score" field.
func (u *WorkLensWindowUpsertOne) SetRankScore(v float64) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetRankScore(v)
	})
}

// AddRankScore adds v to the "rank_score" field.
func (u *WorkLensWindowUpsertOne) AddRankScore(v float64) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.AddRankScore(v)
	})
}

// UpdateRankScore sets the "rank_score" field to the value that was provided on create.
func (u *WorkLensWindowUpsertOne) UpdateRankScore() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateRankScore()
	})
}

// SetFreshnessState sets the "freshness_state" field.
func (u *WorkLensWindowUpsertOne) SetFreshnessState(v worklenswindow.FreshnessState) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetFreshnessState(v)
	})
}

// UpdateFreshnessState sets the "freshness_state" field to the value that was provided on create.
func (u *WorkLensWindowUpsertOne) UpdateFreshnessState() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateFreshnessState()
	})
}

// SetVisibility sets the "visibility" field.
func (u *WorkLensWindowUpsertOne) SetVisibility(v worklenswindow.Visibility) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetVisibility(v)
	})
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *WorkLensWindowUpsertOne) UpdateVisibility() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateVisibility()
	})
}

// SetConfidence sets the "confidence" field.
func (u *WorkLensWindowUpsertOne) SetConfidence(v float64) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetConfidence(v)
	})
}

// AddConfidence adds v to the "confidence" field.
func (u *WorkLensWindowUpsertOne) AddConfidence(v float64) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.AddConfidence(v)
	})
}

// UpdateConfidence sets the "confidence" field to the value that was provided on create.
func (u *WorkLensWindowUpsertOne) UpdateConfidence() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateConfidence()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WorkLensWindowUpsertOne) SetUpdatedAt(v time.Time) *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WorkLensWindowUpsertOne) UpdateUpdatedAt() *WorkLensWindowUpsertOne {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *WorkLensWindowUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WorkLensWindowCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WorkLensWindowUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WorkLensWindowUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WorkLensWindowUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WorkLensWindowCreateBulk is the builder for creating many WorkLensWindow entities in bulk.
type WorkLensWindowCreateBulk struct {
	config
	err      error
	builders []*WorkLensWindowCreate
	conflict []sql.ConflictOption
}

// Save creates the WorkLensWindow entities in the database.
func (_c *WorkLensWindowCreateBulk) Save(ctx context.Context) ([]*WorkLensWindow, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WorkLensWindow, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkLensWindowMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WorkLensWindowCreateBulk) SaveX(ctx context.Context) []*WorkLensWindow {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkLensWindowCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkLensWindowCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WorkLensWindow.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WorkLensWindowUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (_c *WorkLensWindowCreateBulk) OnConflict(opts ...sql.ConflictOption) *WorkLensWindowUpsertBulk {
	_c.conflict = opts
	return &WorkLensWindowUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WorkLensWindow.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WorkLensWindowCreateBulk) OnConflictColumns(columns ...string) *WorkLensWindowUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WorkLensWindowUpsertBulk{
		create: _c,
	}
}

// WorkLensWindowUpsertBulk is the builder for "upsert"-ing
// a bulk of WorkLensWindow nodes.
type WorkLensWindowUpsertBulk struct {
	create *WorkLensWindowCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WorkLensWindow.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WorkLensWindowUpsertBulk) UpdateNewValues() *WorkLensWindowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.WorkLensID(); exists {
				s.SetIgnore(worklenswindow.FieldWorkLensID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(worklenswindow.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WorkLensWindow.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WorkLensWindowUpsertBulk) Ignore() *WorkLensWindowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WorkLensWindowUpsertBulk) DoNothing() *WorkLensWindowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WorkLensWindowCreateBulk.OnConflict
// documentation for more info.
func (u *WorkLensWindowUpsertBulk) Update(set func(*WorkLensWindowUpsert)) *WorkLensWindowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WorkLensWindowUpsert{UpdateSet: update})
	}))
	return u
}

// SetKey sets the "key" field.
func (u *WorkLensWindowUpsertBulk) SetKey(v string) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *WorkLensWindowUpsertBulk) UpdateKey() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateKey()
	})
}

// SetLensWindowKind sets the "lens_window_kind" field.
func (u *WorkLensWindowUpsertBulk) SetLensWindowKind(v worklenswindow.LensWindowKind) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetLensWindowKind(v)
	})
}

// UpdateLensWindowKind sets the "lens_window_kind" field to the value that was provided on create.
func (u *WorkLensWindowUpsertBulk) UpdateLensWindowKind() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateLensWindowKind()
	})
}

// SetWindowStartAt sets the "window_start_at" field.
func (u *WorkLensWindowUpsertBulk) SetWindowStartAt(v time.Time) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetWindowStartAt(v)
	})
}

// UpdateWindowStartAt sets the "window_start_at" field to the value that was provided on create.
func (u *WorkLensWindowUpsertBulk) UpdateWindowStartAt() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateWindowStartAt()
	})
}

// ClearWindowStartAt clears the value of the "window_start_at" field.
func (u *WorkLensWindowUpsertBulk) ClearWindowStartAt() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearWindowStartAt()
	})
}

// SetWindowEndAt sets the "window_end_at" field.
func (u *WorkLensWindowUpsertBulk) SetWindowEndAt(v time.Time) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetWindowEndAt(v)
	})
}

// UpdateWindowEndAt sets the "window_end_at" field to the value that was provided on create.
func (u *WorkLensWindowUpsertBulk) UpdateWindowEndAt() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateWindowEndAt()
	})
}

// ClearWindowEndAt clears the value of the "window_end_at" field.
func (u *WorkLensWindowUpsertBulk) ClearWindowEndAt() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearWindowEndAt()
	})
}

// SetRankStart sets the "rank_start" field.
func (u *WorkLensWindowUpsertBulk) SetRankStart(v int) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetRankStart(v)
	})
}

// AddRankStart adds v to the "rank_start" field.
func (u *WorkLensWindowUpsertBulk) AddRankStart(v int) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.AddRankStart(v)
	})
}

// UpdateRankStart sets the "rank_start" field to the value that was provided on create.
func (u *WorkLensWindowUpsertBulk) UpdateRankStart() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateRankStart()
	})
}

// ClearRankStart clears the value of the "rank_start" field.
func (u *WorkLensWindowUpsertBulk) ClearRankStart() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearRankStart()
	})
}

// SetRankEnd sets the "rank_end" field.
func (u *WorkLensWindowUpsertBulk) SetRankEnd(v int) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetRankEnd(v)
	})
}

// AddRankEnd adds v to the "rank_end" field.
func (u *WorkLensWindowUpsertBulk) AddRankEnd(v int) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.AddRankEnd(v)
	})
}

// UpdateRankEnd sets the "rank_end" field to the value that was provided on create.
func (u *WorkLensWindowUpsertBulk) UpdateRankEnd() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateRankEnd()
	})
}

// ClearRankEnd clears the value of the "rank_end" field.
func (u *WorkLensWindowUpsertBulk) ClearRankEnd() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearRankEnd()
	})
}

// SetCheckpoint sets the "checkpoint" field.
func (u *WorkLensWindowUpsertBulk) SetCheckpoint(v string) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetCheckpoint(v)
	})
}

// UpdateCheckpoint sets the "checkpoint" field to the value that was provided on create.
func (u *WorkLensWindowUpsertBulk) UpdateCheckpoint() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateCheckpoint()
	})
}

// ClearCheckpoint clears the value of the "checkpoint" field.
func (u *WorkLensWindowUpsertBulk) ClearCheckpoint() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearCheckpoint()
	})
}

// SetResultCount sets the "result_count" field.
func (u *WorkLensWindowUpsertBulk) SetResultCount(v int) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetResultCount(v)
	})
}

// AddResultCount adds v to the "result_count" field.
func (u *WorkLensWindowUpsertBulk) AddResultCount(v int) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.AddResultCount(v)
	})
}

// UpdateResultCount sets the "result_count" field to the value that was provided on create.
func (u *WorkLensWindowUpsertBulk) UpdateResultCount() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateResultCount()
	})
}

// SetIsComplete sets the "is_complete" field.
func (u *WorkLensWindowUpsertBulk) SetIsComplete(v bool) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetIsComplete(v)
	})
}

// UpdateIsComplete sets the "is_complete" field to the value that was provided on create.
func (u *WorkLensWindowUpsertBulk) UpdateIsComplete() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateIsComplete()
	})
}

// SetLastIndexedAt sets the "last_indexed_at" field.
func (u *WorkLensWindowUpsertBulk) SetLastIndexedAt(v time.Time) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetLastIndexedAt(v)
	})
}

// UpdateLastIndexedAt sets the "last_indexed_at" field to the value that was provided on create.
func (u *WorkLensWindowUpsertBulk) UpdateLastIndexedAt() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateLastIndexedAt()
	})
}

// ClearLastIndexedAt clears the value of the "last_indexed_at" field.
func (u *WorkLensWindowUpsertBulk) ClearLastIndexedAt() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearLastIndexedAt()
	})
}

// SetSource sets the "source" field.
func (u *WorkLensWindowUpsertBulk) SetSource(v string) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *WorkLensWindowUpsertBulk) UpdateSource() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateSource()
	})
}

// ClearSource clears the value of the "source" field.
func (u *WorkLensWindowUpsertBulk) ClearSource() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearSource()
	})
}

// SetSourceInstance sets the "source_instance" field.
func (u *WorkLensWindowUpsertBulk) SetSourceInstance(v string) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetSourceInstance(v)
	})
}

// UpdateSourceInstance sets the "source_instance" field to the value that was provided on create.
func (u *WorkLensWindowUpsertBulk) UpdateSourceInstance() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateSourceInstance()
	})
}

// ClearSourceInstance clears the value of the "source_instance" field.
func (u *WorkLensWindowUpsertBulk) ClearSourceInstance() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearSourceInstance()
	})
}

// SetExternalID sets the "external_id" field.
func (u *WorkLensWindowUpsertBulk) SetExternalID(v string) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetExternalID(v)
	})
}

// UpdateExternalID sets the "external_id" field to the value that was provided on create.
func (u *WorkLensWindowUpsertBulk) UpdateExternalID() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateExternalID()
	})
}

// ClearExternalID clears the value of the "external_id" field.
func (u *WorkLensWindowUpsertBulk) ClearExternalID() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearExternalID()
	})
}

// SetSourceURL sets the "source_url" field.
func (u *WorkLensWindowUpsertBulk) SetSourceURL(v string) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetSourceURL(v)
	})
}

// UpdateSourceURL sets the "source_url" field to the value that was provided on create.
func (u *WorkLensWindowUpsertBulk) UpdateSourceURL() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateSourceURL()
	})
}

// ClearSourceURL clears the value of the "source_url" field.
func (u *WorkLensWindowUpsertBulk) ClearSourceURL() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearSourceURL()
	})
}

// SetEventCount sets the "event_count" field.
func (u *WorkLensWindowUpsertBulk) SetEventCount(v int) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetEventCount(v)
	})
}

// AddEventCount adds v to the "event_count" field.
func (u *WorkLensWindowUpsertBulk) AddEventCount(v int) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.AddEventCount(v)
	})
}

// UpdateEventCount sets the "event_count" field to the value that was provided on create.
func (u *WorkLensWindowUpsertBulk) UpdateEventCount() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateEventCount()
	})
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (u *WorkLensWindowUpsertBulk) SetFirstSeenAt(v time.Time) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetFirstSeenAt(v)
	})
}

// UpdateFirstSeenAt sets the "first_seen_at" field to the value that was provided on create.
func (u *WorkLensWindowUpsertBulk) UpdateFirstSeenAt() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateFirstSeenAt()
	})
}

// ClearFirstSeenAt clears the value of the "first_seen_at" field.
func (u *WorkLensWindowUpsertBulk) ClearFirstSeenAt() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearFirstSeenAt()
	})
}

// SetLastActivityAt sets the "last_activity_at" field.
func (u *WorkLensWindowUpsertBulk) SetLastActivityAt(v time.Time) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetLastActivityAt(v)
	})
}

// UpdateLastActivityAt sets the "last_activity_at" field to the value that was provided on create.
func (u *WorkLensWindowUpsertBulk) UpdateLastActivityAt() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateLastActivityAt()
	})
}

// ClearLastActivityAt clears the value of the "last_activity_at" field.
func (u *WorkLensWindowUpsertBulk) ClearLastActivityAt() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.ClearLastActivityAt()
	})
}

// SetRankScore sets the "rank_score" field.
func (u *WorkLensWindowUpsertBulk) SetRankScore(v float64) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetRankScore(v)
	})
}

// AddRankScore adds v to the "rank_score" field.
func (u *WorkLensWindowUpsertBulk) AddRankScore(v float64) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.AddRankScore(v)
	})
}

// UpdateRankScore sets the "rank_score" field to the value that was provided on create.
func (u *WorkLensWindowUpsertBulk) UpdateRankScore() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateRankScore()
	})
}

// SetFreshnessState sets the "freshness_state" field.
func (u *WorkLensWindowUpsertBulk) SetFreshnessState(v worklenswindow.FreshnessState) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetFreshnessState(v)
	})
}

// UpdateFreshnessState sets the "freshness_state" field to the value that was provided on create.
func (u *WorkLensWindowUpsertBulk) UpdateFreshnessState() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateFreshnessState()
	})
}

// SetVisibility sets the "visibility" field.
func (u *WorkLensWindowUpsertBulk) SetVisibility(v worklenswindow.Visibility) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetVisibility(v)
	})
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *WorkLensWindowUpsertBulk) UpdateVisibility() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateVisibility()
	})
}

// SetConfidence sets the "confidence" field.
func (u *WorkLensWindowUpsertBulk) SetConfidence(v float64) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetConfidence(v)
	})
}

// AddConfidence adds v to the "confidence" field.
func (u *WorkLensWindowUpsertBulk) AddConfidence(v float64) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.AddConfidence(v)
	})
}

// UpdateConfidence sets the "confidence" field to the value that was provided on create.
func (u *WorkLensWindowUpsertBulk) UpdateConfidence() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateConfidence()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WorkLensWindowUpsertBulk) SetUpdatedAt(v time.Time) *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WorkLensWindowUpsertBulk) UpdateUpdatedAt() *WorkLensWindowUpsertBulk {
	return u.Update(func(s *WorkLensWindowUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *WorkLensWindowUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WorkLensWindowCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WorkLensWindowCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WorkLensWindowUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
